/* Zenith Lab — Quiz Center question pools.
   Each module has an 8-question pool; a quiz attempt draws a random subset,
   in random order, with randomized option order, so repeat attempts differ. */
(function (global) {

function opt(t, correct, why) { return { t, correct, why: why || "" }; }

const POOLS = {
  1: { title: "Formal Models of Workflow Execution", questions: [
    { id: "m1q1", type: "scenario", difficulty: "medium",
      objective: "Detect cycles in a dependency graph",
      text: "A pipeline has steps: fetch→parse, parse→enrich, enrich→save, save→fetch. A teammate says 'it looks fine, every step has exactly one dependency.' Are they right?",
      opts: [ opt("No, save→fetch closes a cycle (fetch→parse→enrich→save→fetch), so no valid execution order exists", true),
        opt("Yes, one dependency per step is exactly what a DAG requires", false, "Degree-1 dependencies don't prevent a cycle, the cycle exists because the chain loops back to its own start."),
        opt("Yes, as long as every step eventually runs once", false, "A cyclic graph can never let every step run 'once', each step in the cycle is permanently waiting on another step in the same cycle.") ] },
    { id: "m1q2", type: "application", difficulty: "medium",
      objective: "Compute a topological order",
      text: "Tasks: A (no deps), B (no deps), C depends on A and B, D depends on C. Which of these is a VALID execution order?",
      opts: [ opt("A, B, C, D", true),
        opt("A, C, B, D", false, "C depends on both A and B, running C before B has been scheduled violates that dependency."),
        opt("D, C, B, A", false, "D depends on C, which depends on A and B, this order runs the most-dependent task first, exactly backwards.") ] },
    { id: "m1q3", type: "debugging", difficulty: "hard",
      objective: "Diagnose a missing-dependency bug",
      text: "A workflow's 'send_invoice' step runs before 'calculate_total' finishes, sometimes sending a $0 invoice. The DAG has no cycle. What's the actual bug?",
      opts: [ opt("A required dependency edge is missing, send_invoice was never declared to depend on calculate_total, so the scheduler treats them as independent and races them", true),
        opt("The DAG has a cycle", false, "A race between two unordered steps isn't a cycle, a cycle would make the workflow unable to start at all, not run out of order intermittently."),
        opt("The scheduler is broken", false, "A correct scheduler faithfully respects whatever dependencies you declare, an intermittent ordering bug with no cycle is almost always a missing edge in the graph itself.") ] },
    { id: "m1q4", type: "recall", difficulty: "easy",
      objective: "State the acyclicity requirement",
      text: "Why must a workflow's dependency graph be acyclic for it to be executable at all?",
      opts: [ opt("A cycle means at least one task would have to wait on itself, directly or transitively, so no starting point exists", true),
        opt("Because most schedulers are written in languages that can't express loops", false, "This is a mathematical property of the graph, not a limitation of any particular programming language or scheduler implementation."),
        opt("Because cycles make the graph too large to store in memory", false, "Cycle detection is about logical executability, not storage size, even a tiny 3-node cycle is unexecutable.") ] },
    { id: "m1q5", type: "engineering-decision", difficulty: "hard",
      objective: "Decide how to handle a detected cycle in production",
      text: "Your workflow engine detects a cycle in a customer-submitted pipeline definition at deploy time. What should it do?",
      opts: [ opt("Reject the deploy immediately with the specific cycle path shown to the customer, before any task runs", true),
        opt("Run the tasks in the order they were listed and hope for the best", false, "Running a cyclic graph 'as listed' means at least one dependency gets silently violated, this hides a real correctness bug instead of catching it."),
        opt("Silently drop one of the edges to break the cycle", false, "Silently dropping an edge the customer explicitly declared changes their workflow's meaning without telling them, likely producing wrong results downstream.") ] },
    { id: "m1q6", type: "application", difficulty: "medium",
      objective: "Recognize when multiple valid orders exist",
      text: "Tasks: A (no deps), B (no deps), C depends on A only. A and B have no dependency between each other. How many valid execution orders exist?",
      opts: [ opt("More than one, for example A,B,C and B,A,C are both valid since A and B are independent of each other", true),
        opt("Exactly one, DAGs always have a single correct order", false, "Only fully linear chains have one order, independent branches (like A and B here) can run in either relative order."),
        opt("Zero, C can't run until the graph is fully linear", false, "C only needs A to have run, B's position relative to A and C is unconstrained, so a valid order absolutely exists.") ] },
    { id: "m1q7", type: "scenario", difficulty: "medium",
      objective: "Distinguish a real cycle from a false alarm",
      text: "A monitoring tool flags 'possible cycle' because task X and task Y both depend on task Z. Is that actually a cycle?",
      opts: [ opt("No, two tasks sharing a common dependency (a 'diamond' shape) is completely normal and not a cycle at all", true),
        opt("Yes, any time two tasks share a dependency it's a cycle", false, "Shared dependencies (fan-out from one task to two) are one of the most common, totally valid DAG shapes, a cycle requires a path that loops back to its own start."),
        opt("It depends on which task runs first", false, "Cycle-ness is a structural property of the graph's edges, it doesn't depend on runtime execution order.") ] },
    { id: "m1q8", type: "calculation", difficulty: "medium",
      objective: "Reason about parallelizable structure",
      text: "In a DAG where A and B have no dependency on each other but both feed into C, and nothing depends on D (which is fully independent), how many tasks can safely start running at the very first moment, in parallel?",
      opts: [ opt("Three: A, B, and D can all start immediately since none of them depend on anything", true),
        opt("One: only the single first task in the DAG can start", false, "A DAG isn't required to be a single linear chain, any task with zero unmet dependencies can start immediately, and here that's three tasks."),
        opt("Four: A, B, C, and D can all start together", false, "C depends on both A and B finishing first, it cannot start until they're done, so it's not part of the initial parallel set.") ] },
  ]},
  2: { title: "Idempotency & Exactly-Once Semantics", questions: [
    { id: "m2q1", type: "scenario", difficulty: "hard",
      objective: "Apply idempotency-key handling to a timeout-retry scenario",
      text: "A client times out waiting for a payment response and retries with the same idempotency key. The original request actually succeeded server-side. What should the server do?",
      opts: [ opt("Look up the stored result for that idempotency key and return the original response, without charging again", true),
        opt("Process it as a brand-new payment, since the client's timeout means the first attempt clearly failed", false, "A client timeout only means the client didn't get a response in time, not that the server-side operation failed, treating it as new risks a double charge."),
        opt("Reject the retry outright, since the same key was already used once", false, "Rejecting outright defeats the entire purpose of an idempotency key, which is to let a client safely retry and get the original result back.") ] },
    { id: "m2q2", type: "debugging", difficulty: "hard",
      objective: "Diagnose an idempotency implementation bug",
      text: "Logs show two identical idempotency_key values producing two different order IDs a few seconds apart. What's the actual bug?",
      opts: [ opt("The idempotency-key lookup/store isn't atomic or isn't being checked at all before creating a new record, so a retry falls through to normal creation logic", true),
        opt("The client is misbehaving by sending the same key twice", false, "Sending the same key twice on retry is exactly correct client behavior, the server is supposed to treat that as 'give me my original result back.'"),
        opt("This is expected, a new order ID should be generated on every request", false, "That directly contradicts what an idempotency key is for, a retry with the same key must return the SAME result, not a new one.") ] },
    { id: "m2q3", type: "engineering-decision", difficulty: "medium",
      objective: "Design idempotency-key storage with a sensible lifetime",
      text: "You're implementing idempotency-key storage. Should keys be kept forever?",
      opts: [ opt("No, keep them for a bounded window (e.g. 24 hours) long enough to cover realistic retry scenarios, then expire them, unbounded storage growth isn't necessary or free", true),
        opt("Yes, keys must never expire or duplicate protection breaks completely", false, "Realistic client retries happen within minutes to hours, not months, a bounded, generous expiry window covers real retries without unbounded storage growth."),
        opt("No expiry is needed since idempotency keys are small strings", false, "Key size isn't the concern, storing every key from every request forever, across millions of requests, is unnecessary unbounded growth for a problem with a bounded real-world retry window.") ] },
    { id: "m2q4", type: "recall", difficulty: "easy",
      objective: "Define idempotency precisely",
      text: "Which statement most precisely defines what it means for an operation to be idempotent?",
      opts: [ opt("Performing it multiple times produces the same end result as performing it once", true),
        opt("It always returns the exact same HTTP status code every time it's called", false, "Status codes are an implementation detail, idempotency is about the resulting STATE, not which status code happens to be returned."),
        opt("It can only be used with GET requests", false, "GET is naturally idempotent (and safe), but idempotency applies to other methods too, PUT and DELETE are also expected to be idempotent by HTTP semantics.") ] },
    { id: "m2q5", type: "application", difficulty: "medium",
      objective: "Distinguish naturally-idempotent operations from ones that need a key",
      text: "Which of these operations is naturally idempotent WITHOUT needing a client-supplied idempotency key?",
      opts: [ opt("DELETE /users/42 — deleting an already-deleted user can just return the same 'not found' or 'deleted' result again", true),
        opt("POST /payments — charging a card, called twice with no key", false, "Without a key, the server has no way to recognize the second call as 'the same request', two calls naturally mean two charges."),
        opt("POST /orders — creating an order, called twice with no key", false, "Order creation is a create operation, without a key to recognize a duplicate, two calls create two separate orders.") ] },
    { id: "m2q6", type: "scenario", difficulty: "hard",
      objective: "Reason about the concurrent-duplicate race condition",
      text: "Two requests with the same idempotency key arrive at nearly the same instant, before either has finished processing. A naive implementation checks 'does this key exist?' then creates the record if not. What goes wrong?",
      opts: [ opt("Both requests can pass the 'does it exist' check before either has written its result, so both proceed to create duplicate side effects, a classic check-then-act race", true),
        opt("Nothing, idempotency keys prevent this by definition", false, "The key alone doesn't prevent a race, it's the ATOMICITY of the check-and-reserve step that prevents it, a naive non-atomic check is exactly what allows this race."),
        opt("The second request will always fail with an error automatically", false, "Without an atomic reservation step, there's no mechanism forcing the second request to fail, it can sail through the same 'not found yet' check as the first.") ] },
    { id: "m2q7", type: "engineering-decision", difficulty: "medium",
      objective: "Decide what to return when the same key is reused with different request bodies",
      text: "A client sends idempotency_key=abc123 with a $50 charge, then retries with the SAME key but a $75 charge (a bug on their end). What should the server do?",
      opts: [ opt("Reject the second request, the key was already used for a different request body, this is a conflict, not a legitimate retry", true),
        opt("Process the $75 charge, since the newer request should win", false, "Silently processing a different amount under a reused key defeats the safety guarantee entirely, the server can't tell whether this is a legitimate change or a client bug, so it should refuse rather than guess."),
        opt("Return the original $50 result and ignore the discrepancy", false, "Silently returning the old result without flagging the mismatch hides a real client-side bug that the client needs to know about.") ] },
    { id: "m2q8", type: "calculation", difficulty: "medium",
      objective: "Reason about retry-and-idempotency interaction volume",
      text: "A client retries up to 3 times on timeout, always with the same idempotency key. Under correct server-side idempotency handling, how many times does the underlying side effect (e.g. the actual charge) execute?",
      opts: [ opt("Exactly once, regardless of how many of the 3 attempts the client makes, since all of them carry the same key", true),
        opt("Up to 3 times, once per attempt", false, "That's exactly the bug idempotency keys exist to prevent, correct handling means only the FIRST attempt actually performs the side effect, the rest return the stored result."),
        opt("Zero times, retries are always rejected", false, "Retries with the same key are supposed to succeed and return the original result, not be rejected outright.") ] },
  ]},
  3: { title: "Failure Handling & Retry Theory", questions: [
    { id: "m3q1", type: "scenario", difficulty: "medium",
      objective: "Recognize a thundering-herd retry pattern",
      text: "1,000 clients all get a timeout from your API at 10:00:00 and all retry with a fixed 2-second delay. What happens at 10:00:02?",
      opts: [ opt("All 1,000 retries arrive again at nearly the same instant, a synchronized spike that can be worse than the original load", true),
        opt("The retries spread out naturally over a few seconds", false, "A FIXED delay with no jitter keeps every client synchronized, they all waited exactly 2 seconds, so they all retry at exactly the same moment."),
        opt("Nothing, retries don't add extra load since they're 'the same' request", false, "Each retry is a new request hitting the server, 1,000 synchronized retries is 1,000 requests landing in the same instant, real added load.") ] },
    { id: "m3q2", type: "calculation", difficulty: "medium",
      objective: "Compute a capped exponential backoff delay",
      text: "Base delay 200ms, multiplier 3, cap 3000ms. What is the delay (before jitter) for the 3rd retry attempt (attempt index 2, zero-indexed)? Formula: min(cap, base × multiplier^attempt).",
      opts: [ opt("1800ms (200 × 3^2 = 1800, which is under the 3000ms cap)", true),
        opt("3000ms, since the cap always applies after 2 attempts", false, "The cap only applies once the computed value exceeds it, 200×9=1800 is still under 3000, so the cap doesn't kick in yet at this attempt."),
        opt("600ms (200 × 3)", false, "That's the formula for attempt index 1, not index 2, at index 2 the multiplier is applied twice: 200 × 3 × 3 = 1800.") ] },
    { id: "m3q3", type: "debugging", difficulty: "hard",
      objective: "Diagnose a circuit breaker that never opens",
      text: "A circuit breaker is configured to open after 5 consecutive failures, but during an outage it logs 40 consecutive failed calls and never opens. What's the most likely bug?",
      opts: [ opt("The failure counter isn't actually being incremented on failure (or is being reset somewhere it shouldn't be), so the threshold is never reached", true),
        opt("The threshold of 5 is too low and should be raised", false, "A threshold that's never reached at all, even after 40 failures, isn't a tuning issue, the counting mechanism itself is broken."),
        opt("Circuit breakers can't open during real outages, only during tests", false, "The entire purpose of a circuit breaker is to open during a real outage, that's precisely when it's supposed to activate.") ] },
    { id: "m3q4", type: "engineering-decision", difficulty: "hard",
      objective: "Decide when NOT to retry",
      text: "A request fails with HTTP 400 (Bad Request, malformed input). Should your retry logic retry this automatically?",
      opts: [ opt("No, a 400 means the request itself is invalid, retrying identical invalid input will just fail identically every time, retries are for TRANSIENT failures, not client bugs", true),
        opt("Yes, always retry every failure a few times just in case", false, "Retrying a deterministic client error wastes calls and delays surfacing a real bug to the caller, it will never succeed no matter how many times you retry the same bad input."),
        opt("Yes, but only retry it once", false, "Even one retry of a guaranteed-to-fail malformed request is wasted, the fix is to correct the input, not to retry it.") ] },
    { id: "m3q5", type: "recall", difficulty: "easy",
      objective: "State the three circuit breaker states",
      text: "What are the three standard states of a circuit breaker, and what does the middle one do?",
      opts: [ opt("Closed (calls flow normally), Open (calls fail fast without hitting the dependency), Half-Open (a limited trial call checks if the dependency has recovered)", true),
        opt("On, Off, Retry, where Retry keeps calling until it succeeds", false, "That's not how circuit breakers are modeled, the standard three states are Closed/Open/Half-Open, and Half-Open sends a small number of TEST calls, it doesn't retry indefinitely."),
        opt("Fast, Medium, Slow, describing how quickly it responds", false, "Circuit breaker states describe whether calls are ALLOWED through, not response speed tiers.") ] },
    { id: "m3q6", type: "scenario", difficulty: "medium",
      objective: "Recognize retry storm warning signs",
      text: "Which observed pattern is the strongest warning sign of a retry storm actively happening right now?",
      opts: [ opt("Request volume to a downstream service spikes well above baseline at the exact moment that service's error rate also spiked", true),
        opt("CPU usage on the client is slightly elevated", false, "Mild client CPU usage is far too generic a signal, it doesn't specifically indicate a retry storm the way a synchronized volume spike tied to a downstream error spike does."),
        opt("The application's log file has grown larger than usual", false, "Log file size alone doesn't distinguish a retry storm from any other verbose-logging scenario, it's not a specific signal.") ] },
    { id: "m3q7", type: "application", difficulty: "medium",
      objective: "Apply jitter correctly",
      text: "What does adding jitter to a retry delay actually change?",
      opts: [ opt("It adds randomness to each client's delay so that synchronized clients spread their retries out over time instead of arriving in lockstep", true),
        opt("It makes retries happen faster overall", false, "Jitter doesn't change the average delay much, it changes the DISTRIBUTION across clients, spreading them out rather than speeding them up."),
        opt("It removes the need for a retry cap", false, "Jitter and a cap solve different problems, jitter desynchronizes clients, a cap bounds how long any single client waits, you need both.") ] },
    { id: "m3q8", type: "engineering-decision", difficulty: "hard",
      objective: "Combine retry and circuit breaker correctly",
      text: "You have both retry-with-backoff AND a circuit breaker on the same call. The breaker is currently Open. What should a retry attempt do?",
      opts: [ opt("Fail fast immediately without calling the dependency at all, that's the entire point of the breaker being Open, then let the retry logic's own backoff schedule decide when to try again", true),
        opt("Ignore the breaker state and call the dependency anyway, since a retry is a special case", false, "A retry is not a special case that bypasses the breaker, calling through an Open breaker defeats its purpose, which is to stop piling load on a confirmed-down dependency."),
        opt("Immediately close the breaker so the retry can go through", false, "Retries don't get to force the breaker closed, the breaker only transitions to Half-Open on its own schedule to test recovery, not on demand from a retry.") ] },
  ]},
  4: { title: "Queueing Theory for Job Systems", questions: [
    { id: "m4q1", type: "calculation", difficulty: "medium",
      objective: "Compute utilization ρ",
      text: "A single worker processes 20 jobs/min. Jobs arrive at 15/min. What is ρ?",
      opts: [ opt("0.75 (15/20)", true),
        opt("1.33 (20/15)", false, "ρ = λ/μ, arrival rate divided by service rate, not the other way around, inverting it gives a number above 1 that would (incorrectly) suggest instability."),
        opt("5 (20 − 15)", false, "That's the absolute spare capacity in jobs/min, not utilization, utilization is a ratio (λ/μ), not a difference.") ] },
    { id: "m4q2", type: "scenario", difficulty: "hard",
      objective: "Reason about the utilization cliff",
      text: "A queue's ρ moves from 0.75 to 0.85 (a 10-point increase). Another queue's ρ moves from 0.90 to 0.97 (a 7-point increase). Which sees the bigger increase in expected wait time, and why?",
      opts: [ opt("The second one, even though its point increase is smaller, it's much closer to the ρ=1 cliff where wait time grows hyperbolically, not linearly", true),
        opt("The first one, since its point increase (10) is numerically larger than the second's (7)", false, "Wait time isn't linear in ρ, near the cliff (ρ close to 1) even a small increase causes a disproportionately large jump in wait time, bigger than a larger point-increase far from the cliff."),
        opt("They're equal, since both are increases in utilization", false, "Equal point-increases in ρ do NOT produce equal increases in wait time, the nonlinearity near ρ=1 is exactly what makes this module's math matter.") ] },
    { id: "m4q3", type: "engineering-decision", difficulty: "hard",
      objective: "Decide on worker count under an SLA",
      text: "Traffic is 50 req/min, each worker handles 15 req/min, SLA requires ρ < 0.8. Is 4 workers enough?",
      opts: [ opt("No, 4 workers gives 60 req/min capacity, ρ = 50/60 ≈ 0.83, which fails the < 0.8 requirement, 5 workers (75 req/min, ρ≈0.67) is needed", true),
        opt("Yes, 4 workers gives more capacity (60) than traffic (50), so it's fine", false, "Having MORE raw capacity than traffic isn't the same as meeting a specific utilization target, ρ≈0.83 still exceeds the 0.8 SLA even though capacity nominally exceeds traffic."),
        opt("Yes, since ρ just needs to be under 1.0, not under 0.8", false, "The scenario explicitly states the SLA requires ρ < 0.8, not merely < 1.0, ρ≈0.83 fails that specific requirement even though the queue would technically still be stable.") ] },
    { id: "m4q4", type: "recall", difficulty: "easy",
      objective: "State Little's Law",
      text: "What does Little's Law state, in the form used in this course?",
      opts: [ opt("L = λW — the average number of items in a system equals the arrival rate times the average time each item spends in the system", true),
        opt("ρ = λ + μ — utilization is the sum of arrival and service rate", false, "Utilization is λ/μ, a RATIO, not a sum, this isn't Little's Law at all."),
        opt("W = ρ² — wait time is utilization squared", false, "Wait time's relationship to ρ is more complex (and grows toward infinity as ρ→1), it isn't simply ρ squared, and this isn't what Little's Law describes.") ] },
    { id: "m4q5", type: "debugging", difficulty: "medium",
      objective: "Diagnose why 'headroom' wasn't actually enough",
      text: "A team says 'we have headroom, we're only at 80% capacity' right before an outage caused by queue backup. Using this module's concepts, what did they misjudge?",
      opts: [ opt("ρ=0.8 is already on the steep part of the wait-time curve, 'only 80%' sounds comfortable in plain English but is actually close enough to the cliff that normal traffic variance can push wait times up sharply", true),
        opt("They must have miscounted their workers", false, "The scenario doesn't describe a counting error, it describes a correct utilization figure (80%) that was misjudged as 'safe' when it's actually already in the danger zone."),
        opt("80% utilization is always perfectly safe for any queue", false, "That's precisely the misconception this module addresses, 80% utilization is already deep into the region where wait time grows fast, not a safely comfortable number.") ] },
    { id: "m4q6", type: "application", difficulty: "medium",
      objective: "Identify the two levers that actually fix a queue near the cliff",
      text: "A queue is running dangerously close to ρ=1. Which two changes would actually help, according to this module?",
      opts: [ opt("Reduce λ (rate-limit or shed load) or increase μ (more/faster workers)", true),
        opt("Add more logging and increase the timeout duration", false, "More logging doesn't change the queue's throughput or arrival rate at all, and a longer timeout doesn't reduce load, it just lets jobs sit longer, neither addresses the actual utilization problem."),
        opt("Restart the service periodically", false, "A restart doesn't change the underlying arrival rate or service rate, the queue returns to the same dangerous ρ shortly after restarting.") ] },
    { id: "m4q7", type: "scenario", difficulty: "medium",
      objective: "Connect retry storms to queue theory",
      text: "Using this module's terms, what does a retry storm from Module 3 do to a queue's λ?",
      opts: [ opt("It temporarily spikes λ, since retried requests are additional arrivals on top of new traffic", true),
        opt("It has no effect on λ, only on μ", false, "Retries are additional incoming requests, that's exactly what λ (arrival rate) measures, a retry storm is a λ spike, not a service-rate change."),
        opt("It permanently increases μ", false, "μ is the service rate (how fast the SYSTEM processes work), a retry storm from clients doesn't change how fast your workers process jobs, it changes how many arrive.") ] },
    { id: "m4q8", type: "calculation", difficulty: "hard",
      objective: "Compute minimum workers for a tighter SLA",
      text: "Traffic is 90 req/min, each worker handles 18 req/min, SLA requires ρ < 0.75. What's the minimum whole number of workers required?",
      opts: [ opt("7 (90/0.75=120 req/min needed capacity, 120/18≈6.67, rounds up to 7; 6 workers gives 108 req/min, ρ=0.83, which fails)", true),
        opt("5, since 5×18=90 exactly matches traffic", false, "Matching traffic exactly gives ρ=1.0 (unstable), that ignores the 0.75 target completely, far too few workers."),
        opt("6, since 6×18=108 is comfortably above 90", false, "6 workers gives ρ=90/108≈0.83, which still exceeds the 0.75 SLA target, 'comfortably above traffic' isn't the same as meeting the specific ρ requirement.") ] },
  ]},
  5: { title: "Authentication & Secure Integration", questions: [
    { id: "m5q1", type: "scenario", difficulty: "hard",
      objective: "Apply correct webhook verification order",
      text: "A webhook handler parses the JSON body first, acts on the fields, and only verifies the HMAC signature afterward for logging purposes. What's wrong with this order?",
      opts: [ opt("The handler acts on unverified, potentially forged data before ever checking whether the request is legitimate, verification must happen BEFORE any field is trusted or acted on", true),
        opt("Nothing, as long as verification happens somewhere in the function", false, "Order matters enormously here, verifying AFTER acting means any forged payload has already had its effect by the time the (too-late) check would catch it."),
        opt("The bug is that JSON parsing should happen after verification instead", false, "Parsing the raw bytes isn't the problem, the problem is ACTING on the parsed fields (business logic) before the signature check has confirmed the payload is legitimate.") ] },
    { id: "m5q2", type: "debugging", difficulty: "hard",
      objective: "Identify a timing-attack vulnerability",
      text: "A signature check uses `if (receivedSig === expectedSig)`. What's the security concern, specifically?",
      opts: [ opt("Standard string equality short-circuits on the first mismatched character, leaking timing information an attacker can use to guess the correct signature byte by byte", true),
        opt("It's fine as long as the signature is long enough", false, "Signature length doesn't fix a timing side-channel, longer strings actually give an attacker MORE bytes to guess incrementally, the fix is a constant-time comparison function, not length."),
        opt("The bug is using === instead of ==", false, "The strict-vs-loose equality distinction is irrelevant here, the actual issue is that BOTH are non-constant-time string comparisons, vulnerable to timing attacks regardless of which equality operator is used.") ] },
    { id: "m5q3", type: "engineering-decision", difficulty: "medium",
      objective: "Design replay protection",
      text: "An attacker captures a legitimate, correctly-signed webhook payload and resends it an hour later. Signature verification alone won't catch this because the signature is genuinely valid. What additional defense is needed?",
      opts: [ opt("Check a timestamp field for staleness AND track already-seen request/event IDs to reject exact replays, signature validity alone doesn't prove freshness", true),
        opt("Use a longer HMAC secret", false, "Secret length doesn't address replay at all, a longer secret still produces a validly-signed replay of the exact same captured payload."),
        opt("Switch from HMAC to a different signing algorithm", false, "The choice of signing algorithm doesn't address replay either, ANY signature scheme validates a captured-and-resent payload as 'authentic' unless you separately check timestamp/nonce freshness.") ] },
    { id: "m5q4", type: "recall", difficulty: "easy",
      objective: "State what HMAC actually proves",
      text: "What does a valid HMAC signature on a message actually prove?",
      opts: [ opt("The message wasn't altered in transit AND it was signed by someone who possesses the shared secret", true),
        opt("The message is encrypted and unreadable to anyone who intercepts it", false, "HMAC provides integrity and authenticity, not confidentiality, an HMAC-signed payload is typically still sent in plaintext (over TLS for confidentiality), the signature doesn't hide the content."),
        opt("The message came from a specific IP address", false, "HMAC has nothing to do with network-layer origin, it proves possession of a shared secret, not a specific source IP.") ] },
    { id: "m5q5", type: "scenario", difficulty: "medium",
      objective: "Apply the HMAC verification flow correctly",
      text: "Which sequence correctly verifies an incoming webhook?",
      opts: [ opt("Read the raw request body bytes, compute HMAC over those exact raw bytes using the shared secret, compare (constant-time) to the signature header, only then parse and act on the JSON", true),
        opt("Parse the JSON, re-serialize it, compute HMAC over the re-serialized JSON, compare to the header", false, "Re-serializing can change whitespace, key order, or number formatting versus the original bytes, producing a different HMAC than what the sender actually signed, causing false verification failures (or, worse, being exploitable)."),
        opt("Trust the request if it arrived over HTTPS, HMAC isn't necessary on top of TLS", false, "TLS protects data in transit between the two parties, it does nothing to prove the request originated from the expected sender in the first place, that's exactly what HMAC verification is for.") ] },
    { id: "m5q6", type: "application", difficulty: "medium",
      objective: "Identify a real vulnerability from a code pattern",
      text: "A webhook handler skips HMAC verification entirely when the request has a valid-looking `X-Source: internal` header. What's the vulnerability?",
      opts: [ opt("Request headers are trivially spoofable by any external caller, this creates a complete authentication bypass for anyone who simply sets that header", true),
        opt("There's no vulnerability, internal traffic doesn't need verification", false, "The header doesn't actually PROVE the request is internal, it's just a string any external attacker can also set, so this 'internal' check provides no real security boundary."),
        opt("The vulnerability is that the header name is too predictable", false, "Renaming the header to something less predictable doesn't fix the underlying issue, ANY client-controlled header used as a trust signal is bypassable, regardless of its name.") ] },
    { id: "m5q7", type: "engineering-decision", difficulty: "medium",
      objective: "Decide what to do with an unverifiable webhook",
      text: "A webhook arrives with a signature header that doesn't match what you compute. What should the handler do?",
      opts: [ opt("Reject it (4xx) and do not process any of its fields, and log the failure for investigation", true),
        opt("Process it anyway but flag it in a log for later review", false, "Processing an unverified payload's fields means acting on data you cannot trust, 'flag for later' happens after any damage from acting on forged data is already done."),
        opt("Retry verification with a slightly different secret in case of rotation, then process if any match", false, "Silently trying multiple secrets to force a match is a workaround that weakens the security guarantee, secret rotation should be handled explicitly and deliberately, not by brute-force matching on every request.") ] },
    { id: "m5q8", type: "scenario", difficulty: "hard",
      objective: "Reason about defense in depth for webhook endpoints",
      text: "You've implemented correct HMAC verification with constant-time comparison and replay protection. Is the webhook endpoint now fully secure against all realistic risks?",
      opts: [ opt("It's much stronger, but 'fully secure' overclaims, e.g. rate limiting, secret rotation/storage, and input validation on the now-trusted payload still matter", true),
        opt("Yes, HMAC verification alone is the complete security model for any endpoint", false, "HMAC verification authenticates the SENDER, it says nothing about protecting against abuse volume (needs rate limiting), secret compromise (needs rotation), or malformed-but-authentically-signed data (still needs input validation)."),
        opt("No additional protection is ever needed once signatures are checked", false, "This overstates what signature verification covers, it's a critical layer, but real production systems still need rate limiting, secret management, and validation on top of it.") ] },
  ]},
  6: { title: "API Contract Design", questions: [
    { id: "m6q1", type: "application", difficulty: "medium",
      objective: "Classify a breaking vs non-breaking change",
      text: "V2 of an API renames a response field from \"user_name\" to \"username\" (same value, different key). Breaking or non-breaking?",
      opts: [ opt("Breaking, existing clients reading \"user_name\" now get undefined, even though the underlying value is unchanged", true),
        opt("Non-breaking, since the value itself didn't change", false, "The VALUE staying the same doesn't matter if the KEY a client is reading by has changed, clients access fields by name, not by value, renaming breaks that access."),
        opt("Non-breaking, since it's just a typo fix", false, "The reason for a rename doesn't change its effect on existing clients, whether it's a typo fix or a deliberate rename, any existing client reading the old key breaks.") ] },
    { id: "m6q2", type: "recall", difficulty: "easy",
      objective: "Classify HTTP methods by safety and idempotency",
      text: "Which HTTP method is idempotent but explicitly NOT safe (i.e. it has side effects)?",
      opts: [ opt("DELETE — repeating it has the same end state (resource gone), but it does modify server state, so it isn't 'safe'", true),
        opt("GET — it's idempotent and also safe", false, "GET is BOTH safe and idempotent, the question asks for a method that's idempotent but NOT safe, GET doesn't fit since it has no side effects at all."),
        opt("POST — it's idempotent by HTTP semantics", false, "POST is defined as NEITHER safe NOR idempotent by HTTP semantics, calling it twice can create two resources, this is the opposite of what the question asks for.") ] },
    { id: "m6q3", type: "engineering-decision", difficulty: "hard",
      objective: "Choose the non-breaking path for a needed behavior change",
      text: "You need to change how idempotency keys work, from a client-supplied header to a server-generated key, changing the meaning for existing clients. What's the correct path?",
      opts: [ opt("Ship it as a new API version, existing clients keep working against the old version while new clients opt into the new behavior", true),
        opt("Change it in place, since it's 'just an internal implementation detail'", false, "It's not internal, it changes observable behavior clients depend on (their supplied key stops mattering), that's a breaking change regardless of how it's implemented internally."),
        opt("Add a deprecation warning in the docs and change it immediately", false, "A docs warning doesn't prevent existing integrations from breaking the moment the behavior changes, a real migration path (new version, overlap period) is required for a change this significant.") ] },
    { id: "m6q4", type: "scenario", difficulty: "medium",
      objective: "Classify a validation-tightening change",
      text: "V2 makes a previously-optional \"email\" field required on account creation. Breaking or non-breaking?",
      opts: [ opt("Breaking, any existing client not sending email now gets rejected where it previously succeeded", true),
        opt("Non-breaking, since email is a reasonable thing to require", false, "Whether the requirement is 'reasonable' doesn't matter to compatibility, what matters is that requests that used to succeed now fail, that's the definition of breaking."),
        opt("Non-breaking, since the field already existed as optional", false, "Pre-existing as optional doesn't protect against making it mandatory, clients that never sent it will now fail, which is exactly a breaking change.") ] },
    { id: "m6q5", type: "application", difficulty: "medium",
      objective: "Classify an additive change",
      text: "V2 adds a new, optional query parameter that changes nothing about the default response when omitted. Breaking or non-breaking?",
      opts: [ opt("Non-breaking, existing clients that don't send the new parameter see no change in behavior at all", true),
        opt("Breaking, any new parameter is automatically breaking", false, "Purely additive, opt-in changes that don't alter default behavior are the textbook example of a SAFE, non-breaking change, not every new parameter is breaking."),
        opt("It depends on the HTTP method used", false, "Additive, opt-in parameters with unchanged defaults are non-breaking regardless of which HTTP method the endpoint uses.") ] },
    { id: "m6q6", type: "debugging", difficulty: "medium",
      objective: "Diagnose a contract violation from client error reports",
      text: "After a deploy, clients report their integration suddenly can't parse the response. The deploy only added a new optional field to the JSON. What's the likely real cause?",
      opts: [ opt("Some clients are using strict schema validation that rejects unknown fields, so even a purely additive change 'breaks' them in practice, this is why documenting a forward-compatible parsing expectation matters", true),
        opt("Adding an optional field is always 100% safe, so this must be an unrelated coincidence", false, "While additive changes are safe by the SPEC, some client implementations use strict/closed schema validation, treating any unexpected field as an error, that's a real, common cause worth investigating before assuming coincidence."),
        opt("JSON doesn't support optional fields, so this change was invalid", false, "JSON has no concept of 'required vs optional' at the format level, that's an application-level contract decision, not a JSON limitation.") ] },
    { id: "m6q7", type: "recall", difficulty: "easy",
      objective: "Recall the idempotency-relevant status codes",
      text: "A client retries a request that already succeeded, using the correct idempotency key. What status code should the server return?",
      opts: [ opt("The original success status (e.g. 200 or 201) with the original response body, since it's the same logical result, not a new occurrence", true),
        opt("409 Conflict, since the resource already exists", false, "409 signals a genuine conflict the client needs to resolve, a correctly-keyed retry isn't a conflict, it's the exact scenario idempotency keys are meant to handle gracefully by returning the original success."),
        opt("500 Internal Server Error, since this shouldn't happen twice", false, "A retry with the correct key is expected, normal client behavior (e.g. after a network timeout), not a server error condition.") ] },
    { id: "m6q8", type: "scenario", difficulty: "hard",
      objective: "Apply compatibility rules to a guarantee-strengthening change",
      text: "V2 changes a webhook's delivery guarantee from 'at-least-once' to 'exactly-once' for the same event type, no field names changed. Breaking or non-breaking?",
      opts: [ opt("Non-breaking, strengthening a guarantee (fewer duplicates, not more) is safe for consumers that were already built to tolerate the weaker at-least-once guarantee", true),
        opt("Breaking, any change to delivery semantics is automatically breaking", false, "The direction of the change matters, WEAKENING a guarantee breaks consumers relying on the stronger one, but STRENGTHENING it is safe for consumers already built to handle the weaker case, which is what idempotent consumers (Module 2) are designed for."),
        opt("It depends on whether the field names changed", false, "This is a behavioral/semantic contract change, not a structural one, field names being unchanged doesn't determine whether it's breaking, the delivery GUARANTEE itself is part of the contract.") ] },
  ]},
  7: { title: "Observability & SLOs", questions: [
    { id: "m7q1", type: "calculation", difficulty: "medium",
      objective: "Compute an error budget from an SLO",
      text: "A service has a 99.5% SLO measured over a 30-day (43,200-minute) window. How many minutes of full downtime does the error budget allow?",
      opts: [ opt("216 minutes (0.5% of 43,200)", true),
        opt("43,200 minutes, the entire window", false, "That would mean 0% success is acceptable, the SLO explicitly requires 99.5% SUCCESS, so only the remaining 0.5% is the allowed failure budget, not the whole window."),
        opt("21.6 minutes (0.05% of 43,200)", false, "That divides by 10 too many, 99.5% SLO means a 0.5% error budget, not 0.05%, the decimal point is off by one place.") ] },
    { id: "m7q2", type: "scenario", difficulty: "hard",
      objective: "Interpret a symptom pattern to rule out a capacity cause",
      text: "An incident shows error rate spiking, but queue depth and p50/p99 latency both stayed completely normal throughout. Which root cause is MOST consistent with this pattern?",
      opts: [ opt("A logic or validation bug causing fast failures, not a resource-exhaustion issue, capacity problems typically show up as elevated latency/queue depth too, which didn't happen here", true),
        opt("The queue hit its capacity limit", false, "Queue depth was explicitly reported as normal the whole time, that directly rules out a capacity-driven cause, which would show elevated queue depth."),
        opt("A retry storm overwhelming the system", false, "A retry storm typically manifests as elevated load, latency, and/or queue depth, none of which moved here, that pattern doesn't fit.") ] },
    { id: "m7q3", type: "debugging", difficulty: "hard",
      objective: "Use correlation IDs to trace a failure",
      text: "You need to find every log line related to one specific failed request across three microservices. What's the single most important field for doing this?",
      opts: [ opt("A correlation/request ID that's generated once and passed through every service the request touches", true),
        opt("The timestamp", false, "Timestamps alone can't distinguish between many concurrent requests happening at nearly the same time across services, you'd get a flood of unrelated log lines, not the one request's full path."),
        opt("The HTTP status code", false, "Status code tells you the outcome, not which specific request instance produced which log lines, many different requests can share the same status code.") ] },
    { id: "m7q4", type: "recall", difficulty: "easy",
      objective: "Distinguish SLI, SLO, and error budget",
      text: "Which statement correctly distinguishes an SLI from an SLO?",
      opts: [ opt("An SLI is the measured indicator (e.g. actual success rate), an SLO is the target threshold for that indicator (e.g. 99.9%)", true),
        opt("They're the same thing, just different names", false, "They're related but distinct, the SLI is what you MEASURE, the SLO is the TARGET you're measuring against, conflating them loses the distinction between 'what happened' and 'what we promised.'"),
        opt("An SLO is measured in real time, an SLI is set once a year", false, "This gets it backwards and adds a made-up constraint, SLIs are the continuously-measured indicators, SLOs are the target commitments, and neither is inherently tied to an annual cadence.") ] },
    { id: "m7q5", type: "engineering-decision", difficulty: "medium",
      objective: "Decide what telemetry confirms a suspected retry storm",
      text: "You suspect a Module-3-style retry storm is overwhelming a downstream API. What specific telemetry would let you confirm or rule this out, rather than guessing from a vague 'things feel slow' report?",
      opts: [ opt("Structured logs with correlation IDs and a retry-attempt-number field, so you can see whether many different traces' retries are clustering together in time", true),
        opt("A general CPU usage graph for the whole fleet", false, "Aggregate CPU usage is too coarse, it won't show you WHETHER retries from multiple traces are clustering in time, which is the specific signature of a retry storm."),
        opt("The total number of log lines written that day", false, "Raw log volume doesn't reveal retry clustering or timing patterns, it's not a diagnostic signal for this specific question.") ] },
    { id: "m7q6", type: "application", difficulty: "medium",
      objective: "Distinguish a trace from a span",
      text: "In distributed tracing, what's the relationship between a trace and a span?",
      opts: [ opt("A trace represents one end-to-end request across all services it touches, made up of multiple spans, each span representing one unit of work within one service", true),
        opt("They're interchangeable terms for the same concept", false, "They describe different levels of granularity, a trace is the whole request's journey, a span is one piece of work within it, treating them as interchangeable loses that structure."),
        opt("A span contains multiple traces", false, "This inverts the actual relationship, a TRACE is made up of multiple SPANS, not the other way around.") ] },
    { id: "m7q7", type: "scenario", difficulty: "medium",
      objective: "Reason about SLO breach response, not just detection",
      text: "Your SLO was just breached for the first time this quarter, with plenty of error budget still remaining. What's the appropriate response?",
      opts: [ opt("Investigate the root cause and fix it, since a single breach with budget remaining doesn't mean panic, but understanding WHY it happened prevents it recurring and eating into budget further", true),
        opt("Immediately loosen the SLO so it isn't breached again", false, "Loosening the target the moment it's inconvenient defeats the purpose of having an SLO at all, it should reflect real user expectations, not be adjusted reactively to avoid ever being breached."),
        opt("Ignore it completely since budget remains", false, "Having budget remaining means it's not an emergency, but ignoring the root cause risks it recurring and compounding, an SLO breach is a signal worth understanding even when not urgent.") ] },
    { id: "m7q8", type: "engineering-decision", difficulty: "hard",
      objective: "Prioritize what to fix first from a compound incident",
      text: "An incident report shows: a bad deploy broke idempotency-key compatibility (causing duplicate charges) AND separately broke signature verification (causing auth failures), both traced to the same 09:13:50 deploy. What should be fixed first?",
      opts: [ opt("Roll back (or hotfix) the deploy itself, since it's the single common root cause behind both symptoms, fixing either symptom individually leaves the other one live", true),
        opt("Fix the duplicate-charge bug first since it involves money, then separately investigate the auth failures later", false, "Since both symptoms trace to the SAME deploy, treating them as two separate problems to fix one at a time wastes time, addressing the shared root cause fixes both simultaneously and faster."),
        opt("Add more monitoring so you can catch this sooner next time, that's the real fix", false, "Better monitoring is valuable follow-up work, but it doesn't address the ACTIVE incident, the immediate priority is stopping the ongoing harm by addressing the deploy that caused it.") ] },
  ]},
  8: { title: "Capstone: Reliability & Architecture Synthesis", questions: [
    { id: "m8q1", type: "engineering-decision", difficulty: "hard",
      objective: "Combine retry and circuit-breaker fixes for a compounding failure",
      text: "Load testing shows that when a downstream dependency degrades, your service's own queue fills up within 90 seconds because of fixed-delay retries with no circuit breaker. What's the most complete fix?",
      opts: [ opt("Add jitter to retry delays AND add a circuit breaker that fails fast once the dependency is confirmed down, addressing both the synchronization problem and the pile-on problem", true),
        opt("Just add more queue workers to absorb the load", false, "More workers absorb symptoms without fixing the retry storm itself, if the dependency is genuinely down, more workers just means more simultaneously-failing calls in flight."),
        opt("Just increase the retry delay to 5 seconds", false, "A longer FIXED delay still synchronizes all clients' retries in lockstep and still calls a dependency confirmed to be down, it slows the problem down without solving either underlying cause.") ] },
    { id: "m8q2", type: "scenario", difficulty: "hard",
      objective: "Design idempotency correctly for a payment system",
      text: "In a payment pipeline, a client times out and retries with the same idempotency key, but the original charge actually succeeded. What must the system do to avoid a double charge, and where does that logic have to live?",
      opts: [ opt("The server must store the result keyed by idempotency key and return the ORIGINAL result on a matching retry, this logic must live server-side since the client's timeout doesn't tell it whether the original attempt succeeded", true),
        opt("The client should just wait longer before timing out", false, "A longer timeout reduces how OFTEN this happens, it doesn't prevent it, the client can never be certain enough to skip retrying safely, the server-side protection is still required."),
        opt("The database's unique constraint on order ID alone is sufficient protection", false, "A unique constraint can prevent an exact duplicate INSERT, but without idempotency-key lookup logic, a retry might still attempt to charge again before hitting that constraint, or use a different generated order ID entirely, key-based idempotency is the actual guarantee.") ] },
    { id: "m8q3", type: "calculation", difficulty: "medium",
      objective: "Combine capacity math with a real traffic scenario",
      text: "Baseline traffic 40 req/min needs 4 workers at 12 req/min/worker (ρ≈0.83, already tight). A campaign will TRIPLE traffic to 120 req/min. Target ρ < 0.8. Minimum workers needed?",
      opts: [ opt("13 (120/0.8=150 req/min needed capacity, 150/12=12.5, rounds up to 13)", true),
        opt("12, since 12×12=144 is comfortably above 120", false, "12 workers gives ρ=120/144≈0.83, which still exceeds the 0.8 target, 'comfortably above raw traffic' isn't the same as meeting the specific utilization requirement."),
        opt("4, the same as baseline, since 'we had headroom before'", false, "Baseline was already at ρ≈0.83 (already over target), tripling traffic without adding capacity would push ρ far higher, this ignores the entire premise of the traffic increase.") ] },
    { id: "m8q4", type: "engineering-decision", difficulty: "hard",
      objective: "Prioritize a fix using observability evidence, not guesses",
      text: "An incident shows duplicate charges, retry volume +340%, and auth failures, all traced via deploy-log correlation to one bad deploy that broke client/server compatibility for both idempotency keys and signatures. What should be fixed FIRST, and why?",
      opts: [ opt("Roll back or hotfix the deploy itself, it's the single common root cause behind both the duplicate charges and the auth failures, fixing it addresses both at once instead of chasing two symptoms separately", true),
        opt("Add more capacity to handle the retry volume", false, "More capacity absorbs the SYMPTOM (elevated retry volume) without fixing the actual bugs generating duplicate charges and auth failures, those bugs would keep producing load even with more capacity."),
        opt("Disable retries platform-wide until further notice", false, "That removes a real reliability mechanism for unrelated transient failures elsewhere in the system, and doesn't fix the specific compatibility bugs from this deploy, an overly broad response to a narrowly-caused incident.") ] },
    { id: "m8q5", type: "scenario", difficulty: "hard",
      objective: "Reason about defense in depth across the whole pipeline",
      text: "A payment pipeline has correct idempotency handling, jittered retries with a circuit breaker, and HMAC-verified webhooks. Is it now safe to skip API contract versioning discipline, since the other layers are solid?",
      opts: [ opt("No, contract discipline is a separate concern, an uncoordinated breaking change can still silently break integrations even when reliability and security are both handled correctly elsewhere", true),
        opt("Yes, reliability and security cover the important risks", false, "Contract stability protects against a DIFFERENT failure mode (integrations silently breaking on a schema change), reliability and security patterns don't substitute for it, an otherwise-perfect pipeline can still break every client with an uncoordinated breaking change."),
        opt("Yes, since HMAC verification implies the contract is also protected", false, "HMAC verification authenticates the SENDER, it says nothing about whether the payload SHAPE is changing in a way that breaks consumers, these are unrelated concerns.") ] },
    { id: "m8q6", type: "debugging", difficulty: "medium",
      objective: "Diagnose which module's concept explains a given symptom",
      text: "A postmortem states: 'the queue was fine, capacity was fine, but 12% of requests failed validation immediately with no retries logged at all.' Which module's failure mode does this NOT match, ruling it out?",
      opts: [ opt("Module 4 (queueing/capacity) — capacity issues show up as elevated queue depth or latency, neither of which occurred here, and 'failed immediately with no retries' doesn't match a capacity signature at all", true),
        opt("Module 6 (API contracts) — a validation failure is consistent with a contract/input-shape issue", false, "This one actually FITS, immediate validation failures are a classic API-contract symptom, so it's not the one being ruled out."),
        opt("This pattern doesn't rule out any module", false, "It specifically rules out a capacity explanation, immediate, non-retried validation failures with normal queue/latency numbers point at a logic/contract issue, not a queueing/capacity one.") ] },
    { id: "m8q7", type: "engineering-decision", difficulty: "hard",
      objective: "Decide what observability is minimally required for a new pipeline stage",
      text: "You're adding a new 'notification' stage to a pipeline where payment succeeds but notification can silently fail. What's the minimum observability needed to even find out this happens?",
      opts: [ opt("Structured logs with a correlation ID spanning the whole request, so a successful payment and a failed notification show up as two connected events under the same trace, not two unrelated log lines", true),
        opt("A daily summary email of total payments processed", false, "An aggregate daily rollup would never surface one silently-failed notification buried among many successful payments, per-request traceability is needed, not a summary number."),
        opt("Nothing extra, if the payment succeeded that's what matters", false, "That's exactly the blind spot the scenario describes, without connected, per-request observability, nobody finds out the notification silently failed at all.") ] },
    { id: "m8q8", type: "application", difficulty: "medium",
      objective: "Recognize which modules a given production bug spans",
      text: "A bug report: 'clients retrying a timed-out request got charged twice, and the retries also weren't spaced out, they all hit us again within the same second.' Which two modules' concepts does this bug span?",
      opts: [ opt("Module 2 (idempotency, the double-charge) and Module 3 (retry/jitter, the synchronized retry timing)", true),
        opt("Module 4 (queueing) and Module 7 (observability) only", false, "Neither queueing capacity math nor observability tooling is what's described here, the bug is specifically about a missing idempotency guarantee and missing retry jitter, not queue sizing or telemetry."),
        opt("Module 1 (DAGs) and Module 6 (API contracts) only", false, "Nothing in the bug description involves a dependency graph or a contract/schema issue, it's specifically about duplicate charging and synchronized retries, Modules 2 and 3's territory.") ] },
  ]},
};

const MIXED_QUIZZES = [
  { id: "mix_1_3", title: "Mixed Quiz: Modules 1–3", modules: [1, 2, 3], perModule: 3 },
  { id: "mix_4_5", title: "Mixed Quiz: Modules 4–5", modules: [4, 5], perModule: 4 },
  { id: "mix_6_8", title: "Mixed Quiz: Modules 6–8", modules: [6, 7, 8], perModule: 3 },
];

function shuffle(arr) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function masteryBand(pct) {
  if (pct >= 90) return { label: "Mastered", cls: "mastered" };
  if (pct >= 80) return { label: "Strong", cls: "strong" };
  if (pct >= 70) return { label: "Needs review", cls: "review" };
  return { label: "Revisit module", cls: "revisit" };
}

global.QuizData = { POOLS, MIXED_QUIZZES, shuffle, masteryBand };
})(window);
