import type { PracticeTask } from "./types";

/* 57 real practice tasks across all 11 modules - distinct from each
   module's checkpoint quiz (different questions, different framing),
   giving students repeated exposure beyond the one pass/fail gate.
   Calculation tasks are graded by real arithmetic (a numeric answer plus
   tolerance); interpretation/debugging/decision tasks are graded like the
   quiz's multiple-choice pattern but framed as untimed, retriable practice
   rather than a module-completion gate. */

export const PRACTICE_TASKS: PracticeTask[] = [
  // ---------------- Module 1: Vectors ----------------
  {
    id: "m1-calc-dot",
    moduleId: 1,
    type: "calculation",
    given: "a = (3, 4), b = (2, -1)",
    prompt: "Compute a · b.",
    answer: 2,
    tolerance: 0.01,
    hint: "a · b = a₁b₁ + a₂b₂.",
    explanation: "a · b = (3)(2) + (4)(-1) = 6 - 4 = 2.",
  },
  {
    id: "m1-calc-magnitude",
    moduleId: 1,
    type: "calculation",
    given: "v = (6, 8)",
    prompt: "Compute ‖v‖ (the magnitude of v).",
    answer: 10,
    tolerance: 0.01,
    hint: "‖v‖ = √(v₁² + v₂²).",
    explanation: "‖v‖ = √(36 + 64) = √100 = 10.",
  },
  {
    id: "m1-interp-cossim",
    moduleId: 1,
    type: "interpretation",
    prompt: "Two document embeddings have a cosine similarity of exactly -1. What does that tell a search engine?",
    options: [
      { text: "The documents are about exactly opposite things - as unrelated as this metric can express", correct: true, feedback: "Correct. -1 is the minimum possible cosine similarity, reached only at a perfect opposite direction." },
      { text: "The documents are identical", correct: false, feedback: "Identical documents would produce a cosine similarity of +1, not -1 - the two ends of the scale mean opposite things." },
      { text: "One document is much longer than the other", correct: false, feedback: "Cosine similarity is normalized specifically to remove any effect of length/magnitude - it says nothing about document length." },
    ],
  },
  {
    id: "m1-debug-dotproduct",
    moduleId: 1,
    type: "debugging",
    given: "a = (2, 3), b = (4, 1). A student computes a · b as 2 + 3 + 4 + 1 = 10.",
    prompt: "What did the student do wrong?",
    options: [
      { text: "They added all four numbers together instead of multiplying matching components and summing those products", correct: true, feedback: "Correct. The right computation is (2)(4) + (3)(1) = 8 + 3 = 11 - multiply matching components first, then add." },
      { text: "Nothing - 10 is correct", correct: false, feedback: "10 is not correct. The real dot product is (2)(4) + (3)(1) = 11." },
      { text: "They should have subtracted instead of added", correct: false, feedback: "The dot product does use addition - the error is that the student never multiplied the matching components first." },
    ],
  },

  {
    id: "m1-calc-cossim",
    moduleId: 1,
    type: "calculation",
    given: "a = (1, 0), b = (1, 1)",
    prompt: "Compute cos(θ) between a and b, rounded to 4 decimal places.",
    answer: 0.7071,
    tolerance: 0.001,
    hint: "cos(θ) = (a·b) / (‖a‖‖b‖).",
    explanation: "a·b = 1. ‖a‖=1, ‖b‖=√2. cos(θ) = 1/√2 ≈ 0.7071.",
  },
  {
    id: "m1-decision-search",
    moduleId: 1,
    type: "decision",
    given: "You're building a document search engine and deciding between ranking by raw dot product or by cosine similarity.",
    prompt: "Which should you pick, and why?",
    options: [
      { text: "Cosine similarity - it removes the bias where longer documents (bigger embedding magnitude) would otherwise rank higher purely for being long", correct: true, feedback: "Correct. This is the exact motivating example from Module 1: raw dot product confounds relevance with magnitude." },
      { text: "Raw dot product - it's a more complete measurement since it uses more information", correct: false, feedback: "Using more raw information isn't the goal here - dot product's extra sensitivity to magnitude is specifically a bias, not useful signal, for a relevance ranking." },
      { text: "It doesn't matter - both always produce the same ranking", correct: false, feedback: "They produce the same ranking only when every document embedding has equal magnitude - in general, dot product and cosine similarity can rank documents differently." },
    ],
  },

  // ---------------- Module 2: Matrices ----------------
  {
    id: "m2-calc-matvec",
    moduleId: 2,
    type: "calculation",
    given: "M = [[2, 0], [1, 3]], v = (1, 2)",
    prompt: "Compute the y-component (second entry) of Mv.",
    answer: 7,
    tolerance: 0.01,
    hint: "The second row of M gives the y-component: (row 2) · v.",
    explanation: "y-component = (1)(1) + (3)(2) = 1 + 6 = 7.",
  },
  {
    id: "m2-calc-det",
    moduleId: 2,
    type: "calculation",
    given: "M = [[3, 1], [2, 4]]",
    prompt: "Compute det(M).",
    answer: 10,
    tolerance: 0.01,
    hint: "det(M) = ad - bc.",
    explanation: "det(M) = (3)(4) - (1)(2) = 12 - 2 = 10.",
  },
  {
    id: "m2-interp-detzero",
    moduleId: 2,
    type: "interpretation",
    prompt: "A transformation matrix has det(M) = 0. What does this mean for the transformation?",
    options: [
      { text: "It collapses the plane onto a line (or a point) and cannot be undone by any other matrix", correct: true, feedback: "Correct. Zero determinant means the two columns are parallel (or zero) - a real dimension of information is destroyed." },
      { text: "It rotates everything by 90 degrees", correct: false, feedback: "A rotation preserves area and has determinant 1, not 0 - this is a very different effect." },
      { text: "It has no effect on any vector", correct: false, feedback: "That would be the identity matrix (det = 1), the opposite of a determinant-zero matrix." },
    ],
  },
  {
    id: "m2-debug-det",
    moduleId: 2,
    type: "debugging",
    given: "M = [[2, 5], [1, 3]]. A student computes det(M) as (2)(3) + (5)(1) = 11.",
    prompt: "What did the student do wrong?",
    options: [
      { text: "They added ad and bc instead of subtracting: det(M) = ad − bc, not ad + bc", correct: true, feedback: "Correct. det(M) = (2)(3) - (5)(1) = 6 - 5 = 1, not 11." },
      { text: "They should have multiplied all four numbers together", correct: false, feedback: "The determinant formula for a 2x2 matrix is ad - bc, never a product of all four entries." },
      { text: "Nothing - 11 is correct", correct: false, feedback: "11 is not correct. The determinant subtracts bc from ad: (2)(3) - (5)(1) = 1." },
    ],
  },

  {
    id: "m2-calc-matvec2",
    moduleId: 2,
    type: "calculation",
    given: "M = [[0, -1], [1, 0]], v = (3, 5)",
    prompt: "Compute the x-component (first entry) of Mv.",
    answer: -5,
    tolerance: 0.01,
    hint: "The first row of M gives the x-component: (row 1) · v.",
    explanation: "x-component = (0)(3) + (-1)(5) = -5. (This matrix is a 90° rotation.)",
  },
  {
    id: "m2-interp-columns",
    moduleId: 2,
    type: "interpretation",
    prompt: "A matrix's two columns are (1, 0) and (0, 1) - the identity matrix. What does it do to any input vector?",
    options: [
      { text: "Leaves it completely unchanged - every point maps to itself", correct: true, feedback: "Correct. Mv = x·(1,0) + y·(0,1) = (x, y), the original point exactly." },
      { text: "Reflects it across the origin", correct: false, feedback: "A reflection would require negative entries somewhere - the identity matrix's columns produce no change at all." },
      { text: "Scales it by the number of dimensions", correct: false, feedback: "There's no scaling here - each column has a single 1 and a single 0, which reconstructs the input exactly, not a scaled version of it." },
    ],
  },

  // ---------------- Module 3: PCA ----------------
  {
    id: "m3-interp-varexplained",
    moduleId: 3,
    type: "interpretation",
    prompt: "PC1 explains 95% of a dataset's variance. What's the most accurate description of what that means?",
    options: [
      { text: "Almost all of the dataset's spread lies along one direction - reducing to 1D along PC1 would lose very little information", correct: true, feedback: "Correct - this is exactly the justification for dimensionality reduction." },
      { text: "95% of the individual data points sit exactly on the PC1 line", correct: false, feedback: "Variance explained is an aggregate statistic about total spread, not a count of points sitting exactly on a line." },
      { text: "The model is 95% accurate", correct: false, feedback: "PCA has no 'accuracy' - it isn't a prediction method, it's a description of how spread out the data is in different directions." },
    ],
  },
  {
    id: "m3-calc-eigenvalue",
    moduleId: 3,
    type: "calculation",
    given: "A covariance matrix is diagonal: [[4, 0], [0, 1]]",
    prompt: "What is the larger eigenvalue, λ1?",
    answer: 4,
    tolerance: 0.01,
    hint: "For a diagonal matrix, the eigenvalues are just the diagonal entries themselves.",
    explanation: "For a diagonal matrix, Mv=λv is satisfied by the standard basis vectors with λ equal to each diagonal entry - so λ1=4, λ2=1.",
  },
  {
    id: "m3-decision-lowvariance",
    moduleId: 3,
    type: "decision",
    given: "A fraud-detection dataset has 99.9% of its variance in 'normal transaction size' and 0.1% in a direction that happens to carry the fraud signal.",
    prompt: "Should you drop the low-variance direction to reduce dimensions?",
    options: [
      { text: "No - check what a low-variance direction represents before dropping it; PCA doesn't know which direction matters for your task", correct: true, feedback: "Correct. This is the exact failure mode from the lesson - variance explained isn't the same as task-relevance." },
      { text: "Yes - PCA always drops the least useful information first", correct: false, feedback: "PCA ranks directions by variance, not by relevance to any particular downstream task - a rare but critical signal can live in a low-variance direction." },
      { text: "It doesn't matter which directions you keep, as long as you keep 95% of total variance", correct: false, feedback: "A fixed variance threshold doesn't guarantee you keep task-relevant information - exactly the scenario described here." },
    ],
  },

  {
    id: "m3-calc-varexplained",
    moduleId: 3,
    type: "calculation",
    given: "A covariance matrix has eigenvalues λ1 = 9 and λ2 = 1",
    prompt: "What percentage of variance does PC1 explain? (Enter as a number, e.g. 50 for 50%.)",
    answer: 90,
    tolerance: 0.5,
    hint: "Variance explained by PC1 = λ1 / (λ1 + λ2), then convert to a percentage.",
    explanation: "9 / (9+1) = 0.9 = 90%.",
  },
  {
    id: "m3-debug-eigenvector",
    moduleId: 3,
    type: "debugging",
    given: "A student claims: \"Rotating the data cloud by 45° will change the eigenvalues, since the data now looks different.\"",
    prompt: "What's wrong with this claim?",
    options: [
      { text: "Eigenvalues measure the data's own spread, which doesn't change under rotation - only the eigenvectors' directions rotate along with the data", correct: true, feedback: "Correct. Rotation is a rigid transformation - it preserves all distances and variances, changing only orientation." },
      { text: "Nothing - rotating data always changes its eigenvalues", correct: false, feedback: "Rotation is exactly the one transformation that leaves eigenvalues unchanged - it only relabels which raw axis the spread lines up with." },
      { text: "Eigenvalues would change, but eigenvectors would stay fixed", correct: false, feedback: "It's the opposite: the eigenVECTORS rotate along with the data (since they track the data's own directions), while the eigenVALUES (the amount of spread) stay the same." },
    ],
  },

  // ---------------- Module 4: Calculus ----------------
  {
    id: "m4-calc-partial",
    moduleId: 4,
    type: "calculation",
    given: "f(x, y) = x² + 3y², at the point x = 2",
    prompt: "Compute ∂f/∂x at that point.",
    answer: 4,
    tolerance: 0.01,
    hint: "∂f/∂x = 2x, holding y fixed.",
    explanation: "∂f/∂x = 2x = 2(2) = 4.",
  },
  {
    id: "m4-calc-gradmag",
    moduleId: 4,
    type: "calculation",
    given: "f(x, y) = x² + y², at the point (3, 4)",
    prompt: "Compute ‖∇f‖ at that point.",
    answer: 10,
    tolerance: 0.01,
    hint: "∇f = (2x, 2y). Then take the magnitude of that vector.",
    explanation: "∇f = (6, 8), and ‖(6,8)‖ = √(36+64) = √100 = 10.",
  },
  {
    id: "m4-interp-zerograd",
    moduleId: 4,
    type: "interpretation",
    prompt: "You compute ∇f = (0, 0) at a point. What does that tell you?",
    options: [
      { text: "You're at a flat point - a local minimum, maximum, or saddle point of f", correct: true, feedback: "Correct. A zero gradient means no direction increases f - that's the defining condition of a critical point." },
      { text: "The function is undefined there", correct: false, feedback: "A zero gradient is a perfectly well-defined value - it marks a flat point, not an undefined one." },
      { text: "You made a calculation error, since gradients are never exactly zero", correct: false, feedback: "Gradients are exactly zero at genuine critical points - for example, the origin for f(x,y)=x²+y²." },
    ],
  },

  {
    id: "m4-calc-partialy",
    moduleId: 4,
    type: "calculation",
    given: "f(x, y) = x² + 3y², at the point y = 2",
    prompt: "Compute ∂f/∂y at that point.",
    answer: 12,
    tolerance: 0.01,
    hint: "∂f/∂y = 6y, holding x fixed.",
    explanation: "∂f/∂y = 6y = 6(2) = 12.",
  },
  {
    id: "m4-decision-onepartial",
    moduleId: 4,
    type: "decision",
    given: "You compute ∂f/∂x = 0 at a point, but haven't checked ∂f/∂y yet.",
    prompt: "Can you already conclude this point is a flat point (local min/max) of f?",
    options: [
      { text: "No - a true flat point requires the FULL gradient (0,0), so ∂f/∂y must also be checked before concluding anything", correct: true, feedback: "Correct. One zero partial derivative alone doesn't guarantee flatness in every direction." },
      { text: "Yes - one zero partial derivative is enough to guarantee a flat point", correct: false, feedback: "This is a common shortcut error - the surface could still be sloped in the y-direction even with ∂f/∂x = 0." },
      { text: "It depends on whether f is a polynomial", correct: false, feedback: "The requirement (both partials must be zero) applies to any differentiable multivariable function, not just polynomials." },
    ],
  },

  // ---------------- Module 5: Optimization ----------------
  {
    id: "m5-calc-step",
    moduleId: 5,
    type: "calculation",
    given: "x = 4, ∂L/∂x = 6, learning rate η = 0.1",
    prompt: "Compute x_new after one gradient descent step.",
    answer: 3.4,
    tolerance: 0.01,
    hint: "x_new = x − η · (∂L/∂x).",
    explanation: "x_new = 4 − (0.1)(6) = 4 − 0.6 = 3.4.",
  },
  {
    id: "m5-debug-divergence",
    moduleId: 5,
    type: "debugging",
    given: "A training loss curve decreases smoothly for 50 steps, then suddenly spikes upward and keeps growing.",
    prompt: "What's the most likely explanation?",
    options: [
      { text: "The learning rate is too large for the current curvature of the loss surface, causing overshoot that compounds each step", correct: true, feedback: "Correct - this is the exact divergence signature from the lesson: smooth progress, then growing overshoot." },
      { text: "The dataset was shuffled incorrectly", correct: false, feedback: "Shuffling issues don't typically produce this specific smooth-then-diverging pattern - a learning-rate/curvature mismatch does." },
      { text: "The model doesn't have enough parameters", correct: false, feedback: "Insufficient capacity usually shows up as loss plateauing too high, not as smooth progress followed by a sudden, growing spike." },
    ],
  },
  {
    id: "m5-decision-lr",
    moduleId: 5,
    type: "decision",
    given: "One direction of your loss surface is very steep, another is very shallow.",
    prompt: "You can only set one shared learning rate. What's the safest choice?",
    options: [
      { text: "A learning rate small enough to be stable for the steep direction, accepting slower progress in the shallow direction", correct: true, feedback: "Correct - this is exactly why adaptive optimizers (Adam, RMSProp) were invented: to avoid this compromise." },
      { text: "A learning rate tuned for the shallow direction, since it needs bigger steps to make progress", correct: false, feedback: "That learning rate would likely be unstable (oscillating or diverging) in the steep direction - stability in the steepest direction has to come first." },
      { text: "It doesn't matter which one you pick - a single shared rate works equally well for both", correct: false, feedback: "This is exactly the problem: a shared rate that's stable for one direction is very often wrong for the other." },
    ],
  },

  {
    id: "m5-calc-step2",
    moduleId: 5,
    type: "calculation",
    given: "x = 10, ∂L/∂x = 4, learning rate η = 0.25",
    prompt: "Compute x_new after one gradient descent step.",
    answer: 9,
    tolerance: 0.01,
    hint: "x_new = x − η · (∂L/∂x).",
    explanation: "x_new = 10 − (0.25)(4) = 10 − 1 = 9.",
  },
  {
    id: "m5-interp-toosmall",
    moduleId: 5,
    type: "interpretation",
    prompt: "You lower the learning rate a lot, and training becomes extremely slow but never oscillates or diverges. What does this indicate?",
    options: [
      { text: "The learning rate is now safely stable, but small enough that convergence just takes a very long time - a speed issue, not a stability one", correct: true, feedback: "Correct. Stable-but-slow and unstable-but-fast are the two opposite failure directions of this same dial." },
      { text: "Training has completely stopped and something is broken", correct: false, feedback: "Slow, steady progress is a real working state of gradient descent - just an inefficient choice of learning rate, not a malfunction." },
      { text: "The learning rate must actually be too large, not too small", correct: false, feedback: "Oscillation and divergence are the signatures of too LARGE a rate - painfully slow, stable progress points the opposite way, toward too small a rate." },
    ],
  },

  // ---------------- Module 6: Probability ----------------
  {
    id: "m6-calc-expectation",
    moduleId: 6,
    type: "calculation",
    given: "A biased coin has true probability p = 0.3 of heads.",
    prompt: "What is the expected value E[X] of a single flip (1 = heads, 0 = tails)?",
    answer: 0.3,
    tolerance: 0.01,
    hint: "For a Bernoulli trial, E[X] = p.",
    explanation: "E[X] = p = 0.3.",
  },
  {
    id: "m6-calc-variance",
    moduleId: 6,
    type: "calculation",
    given: "The same coin, p = 0.3",
    prompt: "What is Var(X) for a single flip?",
    answer: 0.21,
    tolerance: 0.01,
    hint: "Var(X) = p(1-p).",
    explanation: "Var(X) = (0.3)(0.7) = 0.21.",
  },
  {
    id: "m6-debug-gambler",
    moduleId: 6,
    type: "debugging",
    given: "A fair coin has landed heads 5 times in a row. A student says: \"Tails is now more likely on the next flip, to balance things out.\"",
    prompt: "What's wrong with this reasoning?",
    options: [
      { text: "Each flip is independent - the coin has no memory, so the next flip is still exactly 50/50 regardless of the streak", correct: true, feedback: "Correct - this is the gambler's fallacy, a very common and specifically named reasoning error." },
      { text: "Nothing is wrong - the student is applying the law of large numbers correctly", correct: false, feedback: "The law of large numbers describes long-run averages over MANY flips, not a correction on the very next flip - it doesn't imply any single flip 'owes' a different outcome." },
      { text: "Tails is actually less likely now, not more", correct: false, feedback: "Independence means the next flip's probability doesn't change in either direction based on the streak - it stays exactly 50/50." },
    ],
  },

  {
    id: "m6-calc-se",
    moduleId: 6,
    type: "calculation",
    given: "A fair coin, p = 0.5, flipped n = 64 times",
    prompt: "Compute the standard error of the running average, √(p(1-p)/n).",
    answer: 0.0625,
    tolerance: 0.001,
    hint: "First compute p(1-p), then divide by n, then take the square root.",
    explanation: "√(0.25/64) = √0.00390625 = 0.0625.",
  },
  {
    id: "m6-decision-confidence",
    moduleId: 6,
    type: "decision",
    given: "A single model prediction is reported as \"87% confident.\"",
    prompt: "What's the most honest way to interpret this number for THIS one prediction?",
    options: [
      { text: "It describes long-run behavior across many similar predictions - it isn't a guarantee that this specific case is 87% likely to be correct in some checkable sense", correct: true, feedback: "Correct. Confidence scores are calibrated in aggregate, not as a per-instance certainty guarantee." },
      { text: "It means the model will be correct exactly 87% of the time on every future input, forever", correct: false, feedback: "A single confidence score says nothing about overall future accuracy across a different distribution of future inputs." },
      { text: "It's meaningless since it's just one prediction", correct: false, feedback: "It's not meaningless - it's a real probability statement, just one that only fully cashes out in aggregate across many predictions, not as a single-case guarantee." },
    ],
  },

  // ---------------- Module 7: Statistics ----------------
  {
    id: "m7-calc-se",
    moduleId: 7,
    type: "calculation",
    given: "Population standard deviation σ = 8, sample size n = 16",
    prompt: "Compute the standard error of the sample mean.",
    answer: 2,
    tolerance: 0.01,
    hint: "SE = σ / √n.",
    explanation: "SE = 8 / √16 = 8 / 4 = 2.",
  },
  {
    id: "m7-interp-clt",
    moduleId: 7,
    type: "interpretation",
    prompt: "A population's values are heavily right-skewed. What does the Central Limit Theorem predict about the distribution of sample means as n grows?",
    options: [
      { text: "It becomes approximately bell-shaped (normal), regardless of the population's own skewed shape", correct: true, feedback: "Correct - this is the CLT's defining, surprising claim." },
      { text: "It stays exactly as right-skewed as the population, just narrower", correct: false, feedback: "The shape itself changes toward symmetric/normal as n grows - it isn't merely a narrower copy of the original skew." },
      { text: "It becomes uniform (flat)", correct: false, feedback: "Averaging concentrates values near the mean in a bell shape - the opposite of spreading them out uniformly." },
    ],
  },
  {
    id: "m7-decision-samplesize",
    moduleId: 7,
    type: "decision",
    given: "A colleague reports \"our new model is better\" based on a comparison using only 20 test examples.",
    prompt: "What's the most appropriate response?",
    options: [
      { text: "Ask how much the result could plausibly vary from sampling noise alone at that sample size, before trusting the conclusion", correct: true, feedback: "Correct - small samples carry large standard error, exactly this module's core lesson." },
      { text: "Accept the conclusion - a real difference is a real difference regardless of sample size", correct: false, feedback: "A measured difference at a small sample size can easily be explained by ordinary sampling variability, not a genuine effect." },
      { text: "Reject the conclusion outright - small samples are always meaningless", correct: false, feedback: "Small samples aren't meaningless, they're just noisier - the right move is to account for that uncertainty, not dismiss the result entirely." },
    ],
  },

  {
    id: "m7-calc-se2",
    moduleId: 7,
    type: "calculation",
    given: "Population standard deviation σ = 15, sample size n = 9",
    prompt: "Compute the standard error of the sample mean.",
    answer: 5,
    tolerance: 0.01,
    hint: "SE = σ / √n.",
    explanation: "SE = 15 / √9 = 15 / 3 = 5.",
  },
  {
    id: "m7-debug-causation",
    moduleId: 7,
    type: "debugging",
    given: "A report states: \"Cities with more fire trucks have more fire damage, so fire trucks must be causing the damage.\"",
    prompt: "What's the flaw in this conclusion?",
    options: [
      { text: "A confounding variable (fire severity/city size) likely drives both the number of fire trucks dispatched AND the damage - correlation alone doesn't establish that trucks cause damage", correct: true, feedback: "Correct - the classic confounding-variable pattern: bigger fires need more trucks AND cause more damage." },
      { text: "The conclusion is correct - fire trucks clearly cause the damage they respond to", correct: false, feedback: "This reverses the more plausible causal direction - the fire's severity is a shared cause of both more trucks being sent and more damage occurring." },
      { text: "There's no way to explain this correlation at all", correct: false, feedback: "There's a very plausible confounding explanation (fire severity) - it isn't an unexplainable coincidence." },
    ],
  },

  // ---------------- Module 8: Likelihood ----------------
  {
    id: "m8-calc-mle-mean",
    moduleId: 8,
    type: "calculation",
    given: "Data: 2, 4, 6, 8 (assumed drawn from a Gaussian)",
    prompt: "What is the maximum likelihood estimate for μ?",
    answer: 5,
    tolerance: 0.01,
    hint: "For a Gaussian, the MLE for μ is just the sample mean.",
    explanation: "Sample mean = (2+4+6+8)/4 = 20/4 = 5.",
  },
  {
    id: "m8-interp-mle",
    moduleId: 8,
    type: "interpretation",
    prompt: "What does maximum likelihood estimation actually search for?",
    options: [
      { text: "The parameter values that make the observed data as probable as possible under the assumed model", correct: true, feedback: "Correct - that's the literal definition of MLE." },
      { text: "The parameter values that are most commonly used in similar models", correct: false, feedback: "MLE doesn't reference other models or conventions - it's a direct optimization over probability given THIS specific data." },
      { text: "The simplest possible model that fits the data reasonably well", correct: false, feedback: "That describes a different idea (a simplicity/regularization preference) - MLE only cares about maximizing likelihood, not simplicity." },
    ],
  },
  {
    id: "m8-decision-modelfit",
    moduleId: 8,
    type: "decision",
    given: "Model A gives a log-likelihood of -12.3 on some data. Model B gives -18.7 on the same data.",
    prompt: "Which model fits the data better, by the likelihood criterion?",
    options: [
      { text: "Model A - its log-likelihood is higher (less negative)", correct: true, feedback: "Correct. -12.3 > -18.7, so Model A assigns higher probability to the observed data." },
      { text: "Model B - its log-likelihood is a bigger number in magnitude", correct: false, feedback: "Bigger in magnitude but MORE negative means lower likelihood, not higher - the comparison should be by value, not absolute size." },
      { text: "They fit equally well since both are negative", correct: false, feedback: "Both being negative doesn't make them equal - compare the actual values: -12.3 is greater than -18.7." },
    ],
  },

  {
    id: "m8-calc-mle-mean2",
    moduleId: 8,
    type: "calculation",
    given: "Data: 10, 12, 14 (assumed drawn from a Gaussian)",
    prompt: "What is the maximum likelihood estimate for μ?",
    answer: 12,
    tolerance: 0.01,
    hint: "For a Gaussian, the MLE for μ is just the sample mean.",
    explanation: "Sample mean = (10+12+14)/3 = 36/3 = 12.",
  },
  {
    id: "m8-debug-truth",
    moduleId: 8,
    type: "debugging",
    given: "A student says: \"Model A has higher likelihood than Model B, so Model A must be the actual true model that generated this data.\"",
    prompt: "What's wrong with this claim?",
    options: [
      { text: "Higher likelihood only means Model A's parameters make the observed data more probable than Model B's do - it doesn't certify that Model A is the true underlying process", correct: true, feedback: "Correct. Likelihood is a relative, data-dependent comparison between the specific models tested, not an absolute proof of truth." },
      { text: "Nothing is wrong - the highest-likelihood model is always the true one", correct: false, feedback: "This overstates what likelihood proves - it ranks candidate models against each other on this data, without guaranteeing either one is the actual generating process." },
      { text: "Likelihood can't be used to compare models at all", correct: false, feedback: "Comparing likelihoods between models is a valid and common practice - the error is specifically claiming this proves 'truth,' not that comparison itself is invalid." },
    ],
  },

  // ---------------- Module 9: Information ----------------
  {
    id: "m9-calc-entropy-fair",
    moduleId: 9,
    type: "calculation",
    given: "A fair coin: p = 0.5, 0.5",
    prompt: "Compute H(p) in bits.",
    answer: 1,
    tolerance: 0.02,
    hint: "H(p) = -Σ pᵢ log₂ pᵢ.",
    explanation: "H(p) = -(0.5·log₂0.5 + 0.5·log₂0.5) = -(0.5·(-1) + 0.5·(-1)) = 1 bit.",
  },
  {
    id: "m9-calc-entropy-certain",
    moduleId: 9,
    type: "calculation",
    given: "A distribution: p = 1, 0",
    prompt: "Compute H(p) in bits.",
    answer: 0,
    tolerance: 0.01,
    hint: "A fully predictable outcome has zero average surprise.",
    explanation: "H(p) = -(1·log₂1 + 0·log₂0) = -(1·0 + 0) = 0 bits (using the convention 0·log₂0 = 0).",
  },
  {
    id: "m9-interp-crossentropy",
    moduleId: 9,
    type: "interpretation",
    prompt: "Why is H(p, q) always ≥ H(p), for any predicted distribution q?",
    options: [
      { text: "You can never predict better than the truth's own inherent unpredictability - only match it exactly (when q=p) or do worse", correct: true, feedback: "Correct - this follows from Jensen's inequality, and is exactly why cross-entropy loss has a natural floor at the true entropy." },
      { text: "It isn't always true - H(p,q) can be smaller than H(p) if q is a good enough predictor", correct: false, feedback: "H(p,q) ≥ H(p) is a mathematical guarantee for any q, not something a sufficiently good prediction can break." },
      { text: "H(p,q) and H(p) are unrelated quantities that just happen to look similar", correct: false, feedback: "They're directly related - H(p,q) - H(p) is exactly the KL divergence, a non-negative quantity by construction." },
    ],
  },

  {
    id: "m9-calc-entropy-loaded",
    moduleId: 9,
    type: "calculation",
    given: "A loaded coin: p = 0.9, 0.1",
    prompt: "Compute H(p) in bits (round to 2 decimal places).",
    answer: 0.47,
    tolerance: 0.02,
    hint: "H(p) = -Σ pᵢ log₂ pᵢ. Compute each term separately, then add.",
    explanation: "H(p) = -(0.9·log₂0.9 + 0.1·log₂0.1) ≈ -(0.9·(-0.152) + 0.1·(-3.32)) ≈ 0.137 + 0.332 ≈ 0.47 bits - much less than the fair coin's 1 bit, since this coin is far more predictable.",
  },
  {
    id: "m9-decision-asymmetric",
    moduleId: 9,
    type: "decision",
    given: "You need to score how far a model's predicted distribution q is from the true label distribution p.",
    prompt: "Should D_KL(p‖q) and D_KL(q‖p) be expected to give the same number?",
    options: [
      { text: "No - KL divergence is asymmetric; the two versions penalize different kinds of mismatch and generally give different values", correct: true, feedback: "Correct. D_KL(p‖q) heavily penalizes q assigning low probability where p is large; D_KL(q‖p) penalizes the reverse case." },
      { text: "Yes - KL divergence is always symmetric, like a true distance", correct: false, feedback: "KL divergence is specifically NOT symmetric - that's exactly why it's called a 'divergence' rather than a 'distance.'" },
      { text: "They're always exactly opposite in sign", correct: false, feedback: "Both D_KL(p‖q) and D_KL(q‖p) are always non-negative - they're just generally different positive numbers, not opposite-signed." },
    ],
  },

  // ---------------- Module 10: Neural networks ----------------
  {
    id: "m10-calc-forward",
    moduleId: 10,
    type: "calculation",
    given: "x1 = 2, x2 = 1, w1 = 0.5, w2 = -0.5, b = 0",
    prompt: "Compute z = w1·x1 + w2·x2 + b.",
    answer: 0.5,
    tolerance: 0.01,
    hint: "Just plug the numbers into the weighted-sum formula.",
    explanation: "z = (0.5)(2) + (-0.5)(1) + 0 = 1 - 0.5 = 0.5.",
  },
  {
    id: "m10-calc-sigmoid-deriv",
    moduleId: 10,
    type: "calculation",
    given: "A neuron's output is a = 0.5",
    prompt: "Compute the sigmoid derivative a(1-a) at that output.",
    answer: 0.25,
    tolerance: 0.01,
    hint: "da/dz = a(1-a).",
    explanation: "a(1-a) = (0.5)(0.5) = 0.25 - this is the sigmoid's derivative's maximum value, reached exactly at a=0.5.",
  },
  {
    id: "m10-debug-signerror",
    moduleId: 10,
    type: "debugging",
    given: "A student implements a weight update as: w_new = w + η · (∂L/∂w).",
    prompt: "What's wrong with this update rule?",
    options: [
      { text: "It should subtract the gradient term, not add it - w_new = w − η·(∂L/∂w) - otherwise it's gradient ASCENT, increasing the loss", correct: true, feedback: "Correct. This exact sign error turns a loss-minimizing update into a loss-maximizing one." },
      { text: "The learning rate η shouldn't be multiplied by the gradient", correct: false, feedback: "Multiplying the gradient by the learning rate is correct - the actual bug is the addition instead of subtraction." },
      { text: "Nothing is wrong - this is the standard gradient descent update", correct: false, feedback: "Standard gradient descent subtracts the scaled gradient (w − η·∂L/∂w); adding it moves the weight in the wrong direction." },
    ],
  },

  {
    id: "m10-calc-forward2",
    moduleId: 10,
    type: "calculation",
    given: "x1 = 1, x2 = 3, w1 = 1, w2 = -1, b = 0.5",
    prompt: "Compute z = w1·x1 + w2·x2 + b.",
    answer: -1.5,
    tolerance: 0.01,
    hint: "Plug directly into the weighted-sum formula.",
    explanation: "z = (1)(1) + (-1)(3) + 0.5 = 1 - 3 + 0.5 = -1.5.",
  },
  {
    id: "m10-interp-bias",
    moduleId: 10,
    type: "interpretation",
    prompt: "What would happen to a neuron's outputs across all inputs if it had no bias term at all?",
    options: [
      { text: "Whenever every input is exactly 0, z would always be forced to exactly 0 too, regardless of the weights - the bias is what lets the neuron activate (or not) independent of the inputs", correct: true, feedback: "Correct. Without b, z = w1x1 + w2x2 always equals 0 when x1=x2=0, no matter what the weights are." },
      { text: "The neuron would compute the exact same outputs either way - bias has no real effect", correct: false, feedback: "Bias directly shifts z up or down for every input - removing it measurably changes the neuron's output, especially near an all-zero input." },
      { text: "The neuron would only be able to output negative numbers", correct: false, feedback: "Removing the bias doesn't restrict the sign of z - it just removes one specific constant shift from the weighted sum." },
    ],
  },

  // ---------------- Module 11: Attention ----------------
  {
    id: "m11-calc-score",
    moduleId: 11,
    type: "calculation",
    given: "query q = (1, 0), key k = (0.6, 0.8), dimension d = 2",
    prompt: "Compute the scaled attention score, (q · k) / √d.",
    answer: 0.4243,
    tolerance: 0.02,
    hint: "First compute the dot product, then divide by √d.",
    explanation: "q · k = (1)(0.6) + (0)(0.8) = 0.6. Scaled: 0.6 / √2 ≈ 0.4243.",
  },
  {
    id: "m11-interp-weight",
    moduleId: 11,
    type: "interpretation",
    prompt: "In attention, why does a key vector pointing in nearly the same direction as the query receive a high attention weight?",
    options: [
      { text: "Its dot product with the query is large, which softmax converts into a large share of the total probability mass", correct: true, feedback: "Correct - high dot product (alignment) leads directly to high attention weight via the scaled-score-then-softmax pipeline." },
      { text: "Attention always assigns the highest weight to whichever key comes first in the sequence", correct: false, feedback: "Attention weights come strictly from the query-key dot products, not from position in a list." },
      { text: "It's assigned randomly during training and then fixed", correct: false, feedback: "Attention weights are computed fresh for every query via the actual dot-product/softmax formula, not randomly assigned." },
    ],
  },
  {
    id: "m11-decision-scaling",
    moduleId: 11,
    type: "decision",
    given: "You're implementing attention for embeddings with d=512 dimensions instead of the lab's d=2.",
    prompt: "Should you still divide the dot product by √d before softmax?",
    options: [
      { text: "Yes - and it matters MORE at high dimensions, since unscaled dot-product variance grows with d, pushing softmax toward an unstable near-one-hot distribution", correct: true, feedback: "Correct - √d scaling is a real fix for a problem that gets worse, not better, as dimension increases." },
      { text: "No - scaling was only needed for the small 2D teaching example", correct: false, feedback: "The opposite is true: scaling matters more, not less, at realistic (high) dimensions, which is exactly why production transformers use it." },
      { text: "It doesn't matter either way", correct: false, feedback: "Skipping the scaling at high dimensions can make softmax nearly all-or-nothing and gradients vanish - a real, documented training problem." },
    ],
  },

  {
    id: "m11-calc-score2",
    moduleId: 11,
    type: "calculation",
    given: "query q = (0, 2), key k = (1, 1), dimension d = 4",
    prompt: "Compute the scaled attention score, (q · k) / √d.",
    answer: 1,
    tolerance: 0.02,
    hint: "First compute the dot product, then divide by √d.",
    explanation: "q · k = (0)(1) + (2)(1) = 2. Scaled: 2 / √4 = 2 / 2 = 1.",
  },
  {
    id: "m11-debug-equalscores",
    moduleId: 11,
    type: "debugging",
    given: "A student says: \"Two keys with identical dot-product scores against the same query will end up with different attention weights after softmax, since softmax always favors whichever score it sees first.\"",
    prompt: "What's wrong with this claim?",
    options: [
      { text: "Softmax has no concept of input order - equal scores always produce exactly equal output weights, with no first-seen advantage", correct: true, feedback: "Correct. softmax(x_i) depends only on the numeric value of x_i relative to the others, never on list position." },
      { text: "Nothing is wrong - softmax does favor earlier-listed scores", correct: false, feedback: "There is no such tie-breaking rule in the softmax formula - it's a pure function of the numeric scores." },
      { text: "Equal scores actually produce weights of exactly 0 for both", correct: false, feedback: "Equal nonzero scores produce equal, generally nonzero shares of the total probability - they don't cancel to zero." },
    ],
  },
];

export function practiceTasksForModule(moduleId: number): PracticeTask[] {
  return PRACTICE_TASKS.filter((t) => t.moduleId === moduleId);
}
