/* One-line, accurate descriptions for the real pages listed in each
   course's "Inside the course" nav groups (course-rail-data.ts), keyed by
   filename since the same filenames repeat across courses (dashboard.html,
   syllabus.html, etc. exist in all 4). Grounded in what these pages
   actually do — read/verified against the real course content this
   engagement, not generic marketing copy. Kept separate from
   course-rail-data.ts on purpose: that file feeds the real in-app sidebar
   render and shouldn't carry marketing-page-only content. */
export const COURSE_PAGE_DESCRIPTIONS: Record<string, string> = {
  "dashboard.html": "Your home base: progress, streaks, and what's next",
  "syllabus.html": "The full course outline, module by module",
  "learning-roadmap.html": "The whole journey mapped on one page",
  "cheatsheets.html": "Printable quick-reference for every tool",
  "python-survival-guide.html": "A crash-course reference for Python syntax",
  "python-foundations.html": "Python fundamentals, taught for this course specifically",
  "tickets.html": "The Northline Digital ticket board driving every module",
  "quiz-center.html": "Every module's quiz, plus a cumulative final",
  "practice-sql.html": "Graded SQL exercises against a real database",
  "practice-excel.html": "Graded Excel formula exercises",
  "practice-python.html": "Graded Python exercises in a real interpreter",
  "practice-statistics.html": "Graded statistics exercises on real datasets",
  "practice-automation.html": "Graded scripting and automation exercises",
  "practice-integrated.html": "Cross-tool challenges combining everything you've learned",
  "practice-tableau.html": "Labeled Tableau decision simulations",
  "practice-powerbi.html": "Labeled Power BI decision simulations",
  "practice-workflows.html": "Graded workflow-design scenarios",
  "practice-apis.html": "Graded API, webhook, and auth scenarios",
  "practice-reliability.html": "Graded retry and idempotency scenarios",
  "practice-ai.html": "Graded AI-step and guardrail scenarios",
  "practice-html.html": "Graded HTML exercises, written by hand",
  "practice-css.html": "Graded CSS layout exercises",
  "practice-js.html": "Graded JavaScript logic exercises",
  "practice-testing.html": "Graded test-writing exercises",
  "practice-detective.html": "Find and prove real defects in AI-generated code",
  "practice-specs.html": "Labeled simulation: scope a messy ticket into a spec",
  "practice-git.html": "Labeled simulation: branches, diffs, and conflicts",
  "practice-review.html": "Labeled simulation: review an AI-shaped pull request",
  "ai-review.html": "Catch bad output from an AI coding agent",
  "interview.html": "Practice explaining your own decisions",
  "incident.html": "Labeled simulation: your service just went down",
  "release-review.html": "Ten real ship-or-don't-ship decisions",
  "diagnostic.html": "A placement check for where to start",
  "mastery-profile.html": "Your real skill level, tracked per tool",
  "desktop-labs.html": "The required lab done in the real desktop tool, not a simulation",
  "work-session.html": "A self-reported record of a real AI-assisted session",
  "projects.html": "The real portfolio projects you'll build",
  "deploy-guide.html": "Step-by-step: deploy your work live",
  "portfolio.html": "Every completed project, auto-summarized",
  "career.html": "Career Path Edition: readiness and job-landing playbook",
  "final-assessment.html": "A cumulative assessment across every module",
  "passport.html": "Your evidence passport: score, timeline, competencies",
  "graduation.html": "What you actually have to show, laid out honestly",
  "challenges.html": "Cross-module challenges that gate the capstone",
};
