/* Zenith Lab — AI Engineering Quiz Center question pools.
   Each core module (1-7) has an 8-question pool; a quiz attempt draws a random
   subset, in random order, with randomized option order, so repeat attempts differ.
   Module 8 is the capstone (build-graded, not a multiple-choice pool) and has no
   entry here, matching how it's graded elsewhere in the course. */
(function (global) {

function opt(t, correct, why) { return { t, correct, why: why || "" }; }

const POOLS = {
  1: { title: "Prompting & Structured Outputs", questions: [
    { id: "m1q1", type: "scenario", difficulty: "medium",
      objective: "Apply the repair-then-validate order",
      text: "A model returns ```json\\n{\"status\": \"ok\",}\\n``` (markdown fence, trailing comma). What is the correct order of operations before this data can be trusted?",
      opts: [ opt("Strip the markdown fence, remove the trailing comma, parse as JSON, then validate against the schema, in that order", true),
        opt("Validate against the schema first, then repair whatever the validator flags", false, "Schema validation needs a parsed object to inspect, you can't validate JSON you haven't successfully parsed yet, the fence and comma have to be fixed and the text parsed first."),
        opt("Reject it immediately, a markdown fence means the model isn't following instructions", false, "A markdown fence is one of the most common, easily-repaired deviations, rejecting outright throws away perfectly recoverable output instead of fixing it deterministically.") ] },
    { id: "m1q2", type: "recall", difficulty: "easy",
      objective: "Explain why every model output needs validation",
      text: "Why must structured model output be validated even when the prompt explicitly asked for a specific JSON schema?",
      opts: [ opt("The model can still produce output that doesn't match the schema, asking for a shape doesn't guarantee the shape was produced", true),
        opt("Validation is only needed if the prompt didn't specify a schema", false, "A specified schema in the prompt is a strong hint to the model, not an enforced guarantee, the model can still deviate."),
        opt("Validation is only needed for free-text responses, not JSON-shaped ones", false, "JSON-shaped output is exactly what needs validation, malformed or incorrectly-typed JSON is a common failure mode this course covers directly.") ] },
    { id: "m1q3", type: "debugging", difficulty: "hard",
      objective: "Diagnose a repair-order bug",
      text: "A repair function strips trailing commas AFTER attempting json.loads(). On input {\"a\": 1,} it raises instead of repairing. What's the bug?",
      opts: [ opt("The repair step runs after the parse attempt already failed, trailing-comma stripping has to happen BEFORE calling json.loads(), not after", true),
        opt("json.loads() doesn't support trailing commas ever, so no repair order would fix this", false, "json.loads() indeed rejects trailing commas, that's exactly why the repair step exists, to strip them before parsing, the bug is purely about step ORDER."),
        opt("The regex used to strip commas is wrong", false, "The described bug is about WHEN the repair runs relative to parsing, not the correctness of the stripping logic itself.") ] },
    { id: "m1q4", type: "application", difficulty: "medium",
      objective: "Distinguish a repairable defect from a non-repairable one",
      text: "Which of these is NOT something a deterministic repair pass can fix?",
      opts: [ opt("The model returning conversational prose instead of ever attempting JSON at all", true),
        opt("A markdown code fence wrapped around otherwise-valid JSON", false, "Stripping a fence is a simple, deterministic, always-safe repair, this is exactly the kind of thing a repair pass handles well."),
        opt("A single trailing comma before a closing brace", false, "Trailing commas are mechanically detectable and removable with a simple regex, a textbook repairable defect.") ] },
    { id: "m1q5", type: "scenario", difficulty: "medium",
      objective: "Know when to fall back to a model retry",
      text: "After stripping fences and trailing commas, json.loads() still raises. What's the appropriate next step?",
      opts: [ opt("Fall back to an expensive retry (re-prompting the model with the parse error included), since the cheap deterministic fixes didn't work", true),
        opt("Give up and return the raw unparsed text to the caller as-is", false, "Silently returning unusable text to a caller expecting structured data just moves the failure downstream instead of handling it."),
        opt("Try stripping the trailing comma again, a second time", false, "Repeating an already-attempted deterministic fix that didn't work won't produce a different result, the next step is escalating, not repeating.") ] },
    { id: "m1q6", type: "recall", difficulty: "easy",
      objective: "State this course's token estimate",
      text: "What planning-level relationship between characters and tokens does this course use?",
      opts: [ opt("tokens ≈ characters / 4", true),
        opt("tokens ≈ characters × 4", false, "This inverts the relationship, a token is roughly 4 characters, not 4 tokens per character."),
        opt("tokens = words exactly, one token per word", false, "Tokens are sub-word units, not whole words, punctuation and rare words often cost MORE than one token each.") ] },
    { id: "m1q7", type: "engineering-decision", difficulty: "hard",
      objective: "Decide how to surface a validation failure",
      text: "A required field is missing from an otherwise well-formed model response. What should the system do?",
      opts: [ opt("Reject the response and surface a clear, structured error naming the missing field, rather than proceeding with incomplete data", true),
        opt("Fill the missing field with a reasonable-looking default and continue silently", false, "Silently fabricating a value for a required field hides a real problem and can produce confidently wrong downstream behavior."),
        opt("Ignore the missing field if the rest of the response looks fine", false, "A required field being missing is exactly the kind of defect validation exists to catch, ignoring it defeats the purpose of validating at all.") ] },
    { id: "m1q8", type: "scenario", difficulty: "medium",
      objective: "Recognize why prose isn't a parse failure to repair",
      text: "A model asked for JSON responds: \"Sure! Here's what I found: the user is 29.\" Why doesn't a repair pass fix this the way it fixes a trailing comma?",
      opts: [ opt("There's no JSON structure present at all to repair, the model never attempted the format, repair only fixes small deviations from an otherwise-present structure", true),
        opt("Because the response is too long for a repair pass to process", false, "Length isn't the issue, structure is, a repair pass targets small syntactic deviations, not a complete absence of the requested format."),
        opt("Because repair passes only work on responses under 100 characters", false, "There's no length threshold involved, the issue is that prose has no JSON structure to repair in the first place.") ] },
    { id: "m1q9", type: "scenario", difficulty: "medium",
      objective: "Apply repair-then-validate to a real intake form",
      text: "An insurance-claim intake bot asks a model to extract {\"claimant_name\": str, \"incident_date\": str, \"amount\": number} from a submitted description. It returns valid JSON, but amount is the string \"about $2,400\" instead of a number. Is this a repair-pass fix or a validation failure?",
      opts: [ opt("A validation failure, the JSON parsed fine, the defect is a type mismatch (string where a number was required), that's schema validation's job to catch, not the repair pass's", true),
        opt("A repair-pass fix, since \"about $2,400\" can be turned into 2400 with a bit of string cleanup", false, "Even though a human could guess the intended number, this isn't a small syntactic defect like a trailing comma, silently coercing a fuzzy string into a number risks fabricating precision the source text didn't actually contain, that's a rejection-and-clarify case, not a mechanical repair."),
        opt("Neither, since the JSON is syntactically valid the whole response should be accepted as-is", false, "Syntactic validity (it parsed) and semantic correctness (the fields have the right types and meaning) are different checks, this response passes the first and fails the second.") ] },
    { id: "m1q10", type: "engineering-decision", difficulty: "medium",
      objective: "Decide when repeated malformed output stops being a repair problem",
      text: "A structured-output validator's repair pass is triggered on 40% of calls to a particular prompt, and about half of those still fail validation even after repair. What does this pattern suggest about the fix?",
      opts: [ opt("The prompt itself likely needs to change, a repair pass masking a persistently bad hit rate is treating a systemic prompt problem as if it were an occasional parsing inconvenience", true),
        opt("Nothing, a 40% repair rate is normal and expected for any structured-output prompt", false, "A recurring, high repair-then-still-fails rate is a signal worth investigating, not a baseline to accept silently, it points at the prompt (or schema clarity) as the actual problem."),
        opt("The repair pass needs more regex rules added until the failure rate reaches zero", false, "Continuously patching repair logic to paper over a persistently bad hit rate treats a symptom, the more durable fix is improving the prompt or schema that's producing malformed output this often in the first place.") ] },
    { id: "m1q11", type: "recall", difficulty: "easy",
      objective: "Distinguish parsing from validation as two separate stages",
      text: "A response fails to parse as JSON at all. Does it make sense to run schema validation against it anyway, \"just in case\"?",
      opts: [ opt("No, schema validation checks fields on a parsed object, if there's no parsed object yet there's nothing for the validator to inspect", true),
        opt("Yes, validation can check the raw text directly without a successful parse first", false, "Schema validation operates on structured data (an object with fields), not on raw unparsed text, a parse has to succeed first."),
        opt("Yes, but only for schemas with fewer than five fields", false, "Field count has no bearing on whether validation needs a successfully parsed object first, that requirement is unconditional.") ] },
  ]},

  2: { title: "Context Windows & Token Economics", questions: [
    { id: "m2q1", type: "calculation", difficulty: "medium",
      objective: "Compute available input budget",
      text: "Context window is 16000 tokens, 2000 are reserved for output. How many tokens are available for input?",
      opts: [ opt("14000", true),
        opt("16000, the reservation doesn't reduce what's available for input", false, "Reserved output tokens come out of the same total window, they're not additional headroom, available input = window minus reservation."),
        opt("18000, input and output budgets are separate pools that add together", false, "They're not separate pools, both input and output share one total context window, that's the entire premise of the budget calculation.") ] },
    { id: "m2q2", type: "recall", difficulty: "easy",
      objective: "Define naive truncation's core failure",
      text: "What makes naive truncation specifically dangerous, compared to an error that raises an exception?",
      opts: [ opt("It succeeds silently while discarding content, producing plausible-looking output with no indication anything was cut", true),
        opt("It always crashes the application, which is worse than a normal error", false, "Naive truncation doesn't crash anything, that's precisely the danger, a loud crash would at least be noticed and handled."),
        opt("It only affects image inputs, not text", false, "Truncation applies to text content being cut at a token/character limit, it isn't specific to images.") ] },
    { id: "m2q3", type: "application", difficulty: "medium",
      objective: "Apply the oversized-single-word rule in chunking",
      text: "A chunker's budget check applies even when the current chunk is still empty. A single word alone exceeds the whole budget. What happens to that word?",
      opts: [ opt("It gets silently dropped, since the check blocks adding it to any chunk, ever", true),
        opt("It automatically gets its own oversized chunk, chunkers always handle this case correctly by default", false, "This is only true if the budget check specifically has a guard exempting an empty chunk, without that guard (as described here), the word is dropped, not automatically rescued."),
        opt("It gets truncated to fit the budget", false, "Nothing in a basic budget-check chunker truncates individual words, an oversized word without the empty-chunk guard is simply never added anywhere.") ] },
    { id: "m2q4", type: "recall", difficulty: "easy",
      objective: "Explain the purpose of chunk overlap",
      text: "What problem does overlapping chunk boundaries solve?",
      opts: [ opt("It keeps an idea that spans a chunk boundary readable in both the chunk before and after the cut, instead of being split with zero context on either side", true),
        opt("It reduces the total number of tokens processed across the document", false, "Overlap increases total tokens processed (the same content is repeated across boundaries), it doesn't reduce it."),
        opt("It makes chunking unnecessary for documents under the context window size", false, "Overlap is about boundary continuity between MULTIPLE chunks, it has nothing to do with whether chunking is needed at all for a given document size.") ] },
    { id: "m2q5", type: "engineering-decision", difficulty: "medium",
      objective: "Reason about overlap as a cost tradeoff",
      text: "A team doubles their chunk overlap percentage to improve answer quality at chunk boundaries. What do they need to accept in exchange?",
      opts: [ opt("More total tokens processed across the whole document (and thus more cost and more total chunks), since repeated boundary content is processed more than once", true),
        opt("Nothing, overlap is free since the repeated content was already fetched once", false, "'Already fetched' doesn't mean free to process, the model still reads those repeated tokens again in the next chunk, that's real additional cost."),
        opt("Fewer total chunks, since overlap merges adjacent chunks together", false, "Overlap doesn't merge chunks, if anything more overlap per boundary tends to require slightly MORE chunks to cover the same content, not fewer.") ] },
    { id: "m2q6", type: "calculation", difficulty: "medium",
      objective: "Compute a retry's real token cost",
      text: "A 500-token prompt fails validation, and the retry sends the original prompt plus a 100-token error explanation, generating a new 150-token response. Roughly how many total input+output tokens did this cost across both attempts?",
      opts: [ opt("Roughly 750 tokens (500 original + 100 error context + 150 new response), notably more than a single successful call of similar size", true),
        opt("500 tokens, only the original prompt counts since the retry reuses it", false, "The error-context tokens and the newly generated response are real additional tokens, they don't disappear because part of the content was reused."),
        opt("150 tokens, only the final successful response counts", false, "The first attempt's prompt tokens and the retry's added context were both real, billed tokens, ignoring them undercounts the true cost of the retry.") ] },
    { id: "m2q7", type: "debugging", difficulty: "hard",
      objective: "Diagnose a silent-truncation bug in production",
      text: "A summarizer truncates ticket text to the first 400 tokens. A customer's actual complaint is in the last paragraph. The pipeline runs with no errors and produces a summary. What's actually wrong?",
      opts: [ opt("The summary is confidently wrong, it describes only the truncated portion and never saw the actual complaint, a technically-successful run that's functionally incorrect", true),
        opt("Nothing is wrong, the pipeline completed without throwing an exception", false, "Completing without an exception is not the same as being correct, this is exactly the silent-failure trap naive truncation creates."),
        opt("The bug is in the summarization model itself, not the truncation step", false, "The model is doing its job correctly on the text it actually received, the defect is upstream, truncation never gave it the relevant paragraph to summarize.") ] },
    { id: "m2q8", type: "scenario", difficulty: "medium",
      objective: "Recognize a realistic negative-budget scenario",
      text: "A small, cheap model has a 2000-token context window. A task genuinely needs a long, detailed 1800-token response. Reserved output alone (1800) is most of the window. What's the real fix?",
      opts: [ opt("Choose a model with a larger context window, or reduce what the output needs to contain, not a UI trick on the existing budget", true),
        opt("Just set reserved output higher than the context window, the system will figure it out", false, "Reserving more tokens than the window even contains doesn't create more room, it makes the available input budget negative, there's nothing left to figure out."),
        opt("Truncate the input to zero tokens so all remaining room goes to output", false, "Zero input tokens likely means the model has nothing to work with for a task that presumably needs some context, this doesn't solve the underlying mismatch between task and model choice.") ] },
    { id: "m2q9", type: "scenario", difficulty: "medium",
      objective: "Apply budget arithmetic to a real ingestion pipeline",
      text: "A codebase-documentation generator ingests a 40,000-token source file. The model's context window is 32,000 tokens, with 2,000 reserved for output. Can the whole file fit in one call?",
      opts: [ opt("No, available input is 32,000 − 2,000 = 30,000 tokens, and the file is 40,000, it needs to be chunked, it can't be sent in a single call", true),
        opt("Yes, the file is under the 32,000-token window so it fits fine", false, "The 32,000-token window has to hold BOTH input and reserved output, only 30,000 of it is actually available for input, the 40,000-token file exceeds that."),
        opt("Yes, as long as the output is kept short the whole file will fit", false, "The reservation for output is fixed at 2,000 in this scenario regardless of how short the actual output turns out to be, available input is computed from the reservation, not the eventual output length.") ] },
    { id: "m2q10", type: "engineering-decision", difficulty: "medium",
      objective: "Decide chunk size for a multi-turn chat history",
      text: "A customer-support chat assistant needs to keep recent conversation turns in context. Turns are short (avg 40 tokens) but frequent. Should this content be truncated to the last N characters, or handled with the chunking discipline from this module?",
      opts: [ opt("Chunking discipline still applies in spirit, even if implemented as \"keep the last N whole turns\" rather than sub-turn chunks, the goal is never silently cutting a turn in half or dropping a turn's context with no signal that it happened", true),
        opt("Plain character truncation is fine here since chat turns are short", false, "Turn length doesn't remove the risk, cutting mid-turn (or silently dropping older turns with no indication) is the same silent-failure pattern this module warns about, regardless of how short each individual turn is."),
        opt("Neither applies, conversation history doesn't count as \"content\" for budgeting purposes", false, "Conversation history consumes real input tokens like any other content, it's fully subject to the same budget arithmetic as a document being chunked.") ] },
    { id: "m2q11", type: "recall", difficulty: "easy",
      objective: "State why cost and latency both scale with tokens",
      text: "Besides correctness, what are the other two practical reasons a chunking or truncation decision matters?",
      opts: [ opt("Cost (roughly tokens × price-per-token) and latency (which generally grows with how many tokens the model reads and generates)", true),
        opt("Only cost, latency is unrelated to how many tokens a call processes", false, "Latency generally scales with token count too, a call processing more input and generating more output typically takes measurably longer, not just costs more."),
        opt("Only latency, cost is a fixed flat rate per call regardless of size", false, "Cost is not flat per call in this course's model, it scales with tokens processed, larger calls cost more, not the same amount as a smaller one.") ] },
  ]},

  3: { title: "Retrieval-Augmented Generation", questions: [
    { id: "m3q1", type: "calculation", difficulty: "medium",
      objective: "Compute cosine similarity for perpendicular vectors",
      text: "Query vector [0, 1] compared against document vector [1, 0]. What's the cosine similarity?",
      opts: [ opt("0, the vectors are perpendicular", true),
        opt("1, both vectors have the same magnitude", false, "Magnitude being equal doesn't make vectors similar in direction, these two point in completely different directions (90° apart), giving a similarity of 0."),
        opt("-1, the vectors are opposite", false, "Opposite vectors would be [1,0] and [-1,0], these two are perpendicular, not opposite, perpendicular gives 0, not -1.") ] },
    { id: "m3q2", type: "recall", difficulty: "easy",
      objective: "Explain scale-invariance",
      text: "Why does cosine similarity ignore vector magnitude?",
      opts: [ opt("Magnitude reflects length, not how semantically related two pieces of text are, dividing it out leaves a pure measure of direction (meaning)", true),
        opt("Because computing magnitude is too computationally expensive", false, "Magnitude is trivial to compute (a square root of a sum of squares), the reason it's divided out is about MEANING, not computational cost."),
        opt("It doesn't, cosine similarity is affected by magnitude just like dot product is", false, "This is exactly backwards, cosine similarity is specifically defined to divide out magnitude, that's what distinguishes it from raw dot product.") ] },
    { id: "m3q3", type: "application", difficulty: "medium",
      objective: "Apply a relevance threshold correctly",
      text: "Top-k retrieval with k=5 and no minimum-relevance threshold is asked about a topic completely absent from the document collection. What does it return?",
      opts: [ opt("Its 5 best-scoring documents anyway, whatever scored highest among a set of irrelevant matches, since top-k alone has no concept of 'not good enough'", true),
        opt("An empty result automatically, since nothing is actually relevant", false, "Without an explicit threshold, top-k has no built-in relevance floor, it always returns exactly k results (or fewer only if the collection itself has fewer than k documents)."),
        opt("An error, since no document scores above a reasonable bar", false, "There's no error here, similarity scoring doesn't know what 'reasonable' means without an explicit threshold, it just returns the mathematically highest-scoring k.") ] },
    { id: "m3q4", type: "debugging", difficulty: "hard",
      objective: "Diagnose a zero-vector bug",
      text: "A retrieval function divides dot product by (magnitude_a × magnitude_b) with no zero check. A document has an all-zero embedding vector. What happens?",
      opts: [ opt("Python raises a ZeroDivisionError right at that division, crashing the whole retrieval call instead of just scoring that one document as irrelevant", true),
        opt("The function returns a clear, descriptive 'zero vector' error value automatically, with no explicit guard needed", false, "Python doesn't do this automatically, dividing by zero is a real, unhandled exception unless you explicitly check for a zero magnitude first and return a defined score instead."),
        opt("The document is automatically excluded from results with no other effect", false, "Without an explicit guard, there's no automatic exclusion, the exception propagates and can crash the entire retrieval call for every document, not just the zero-vector one.") ] },
    { id: "m3q5", type: "recall", difficulty: "easy",
      objective: "Define hybrid search",
      text: "What does hybrid search combine, and why?",
      opts: [ opt("Vector similarity search with traditional keyword search, since exact terms (product codes, names) can matter even when their embedding similarity to a paraphrase is unremarkable", true),
        opt("Two different embedding models run in parallel for redundancy", false, "Hybrid search specifically refers to combining vector similarity with KEYWORD search, not running multiple embedding models."),
        opt("Retrieval results from two different document collections merged together", false, "This describes combining data sources, not the vector+keyword scoring combination that defines hybrid search.") ] },
    { id: "m3q6", type: "engineering-decision", difficulty: "medium",
      objective: "Decide what completeness means for retrieval vs. chunking",
      text: "Chunking guarantees every word ends up in some chunk. Should retrieval guarantee every chunk ends up in some answer?",
      opts: [ opt("No, and it shouldn't, chunking's job is completeness (don't lose content), retrieval's job is selectivity (don't include irrelevant content), most chunks correctly never get retrieved for any given query", true),
        opt("Yes, otherwise the chunking step was wasted effort", false, "Chunking effort isn't wasted just because most chunks go unretrieved for any single query, different queries retrieve different chunks over time, that's the system working correctly, not a failure of completeness."),
        opt("Yes, retrieval should eventually surface every chunk to some user", false, "There's no such guarantee or requirement, some content may legitimately never be the best answer to any query asked, that's expected, not a bug.") ] },
    { id: "m3q7", type: "scenario", difficulty: "medium",
      objective: "Recognize a false-positive keyword-overlap match",
      text: "A query about 'resetting a customer password' retrieves a chunk about 'resetting a router to factory settings' with a non-trivial similarity score. Why doesn't this score exactly zero?",
      opts: [ opt("Embeddings capture broad lexical/semantic overlap (like the shared word 'reset'), not topic identity, a modest positive score across unrelated domains is common, not rare", true),
        opt("This indicates a bug in the embedding model that needs to be fixed", false, "This is expected embedding behavior, not a bug, shared vocabulary and phrasing naturally produce some similarity even across different topics."),
        opt("It means the two documents are actually about the same topic", false, "A moderate score from shared terminology doesn't mean the topics are the same, that's exactly the false-positive risk a relevance threshold exists to catch.") ] },
    { id: "m3q8", type: "application", difficulty: "medium",
      objective: "Apply top-k correctly with a partial input order",
      text: "Four documents score 0.9, 0.3, 0.7, 0.5 in that input order. With k=2 and minScore=0, which are returned, and in what order?",
      opts: [ opt("The 0.9 and 0.7 documents, sorted with 0.9 first, the two highest scores regardless of original input position", true),
        opt("The first two documents in input order (0.9 and 0.3), since top-k just takes the first k results", false, "Top-k means highest-SCORING k, not first-k-in-input-order, the 0.3 document should not make the cut when 0.7 scored higher."),
        opt("All four documents, since minScore=0 means no filtering happens", false, "minScore=0 does allow all non-negative scores through the FILTER, but k=2 still limits the final OUTPUT to just the top 2 by score.") ] },
    { id: "m3q9", type: "scenario", difficulty: "medium",
      objective: "Apply threshold reasoning to a real knowledge-base search",
      text: "An internal HR-policy chatbot retrieves its best match at similarity 0.31 for a question about parental leave, when the actual policy document exists but uses different wording than the query. The threshold is set at 0.5. What should happen, and is the threshold necessarily wrong?",
      opts: [ opt("The bot should return \"no relevant information found\" since nothing cleared the threshold, and the threshold isn't necessarily wrong, it may indicate the underlying document needs better wording, phrasing, or a rewritten summary that embeds closer to how people actually ask", true),
        opt("The threshold should always be lowered until this specific query's best match clears it", false, "Tuning the threshold down to force one query's best-but-still-weak match through undermines the threshold for every OTHER query too, a targeted fix (better document phrasing, or a hybrid keyword layer) addresses the specific gap without weakening the general filter."),
        opt("The bot should always answer using the best-scoring match regardless of the threshold, since some answer is better than none", false, "This is exactly the \"confidently wrong\" failure mode a threshold exists to prevent, a 0.31 similarity score, well below 0.5, isn't a reliable basis for a confident answer.") ] },
    { id: "m3q10", type: "debugging", difficulty: "hard",
      objective: "Diagnose a filter-after-slice bug",
      text: "A retrieval function sorts candidates by score, slices to the top 3, THEN filters out anything below the threshold. Five candidates score 0.9, 0.2, 0.15, 0.1, 0.05, with threshold 0.4. What does this buggy order return, and how does it differ from filtering first?",
      opts: [ opt("It returns just [0.9] after filtering the sliced top-3 ([0.9, 0.2, 0.15]) down to only what clears 0.4, which happens to match filter-then-slice here, but the bug is real: with a different score distribution, slicing first can permanently discard a candidate that would have cleared the threshold, before filtering ever gets a chance to see it", true),
        opt("The two orderings always produce identical results regardless of the score distribution, so the order doesn't actually matter", false, "The orders coincide on THIS particular input, but they're not equivalent in general, slice-then-filter can only ever return candidates from the pre-filter top-k, permanently losing any lower-ranked-but-still-relevant candidate that a filter-first approach would have kept in consideration."),
        opt("Slicing before filtering just returns fewer results faster, with no correctness difference from filtering first", false, "There is a real correctness difference in general, filtering before slicing guarantees every threshold-clearing candidate is considered before the top-k cut, slicing first can wrongly exclude one earlier.") ] },
    { id: "m3q11", type: "recall", difficulty: "medium",
      objective: "Explain why 'relevant' and 'exists in the collection' aren't the same",
      text: "A retrieval system always returns its top-k results even for a query about something the document collection has zero coverage of. What concept in this module is specifically meant to catch that case?",
      opts: [ opt("A minimum-relevance threshold, without one the system has no way to say 'nothing here is actually good enough', it just returns whatever scored highest among a set of irrelevant candidates", true),
        opt("Chunk overlap, from Module 2, since it's about preserving content at boundaries", false, "Chunk overlap addresses boundary continuity during ingestion, it has no bearing on whether a QUERY has any relevant match in the collection at all."),
        opt("Increasing k so more results are returned, giving a better chance something relevant is included", false, "Increasing k only returns MORE of the same irrelevant candidates when nothing in the collection is actually relevant, it doesn't introduce any relevance floor, only a threshold does that.") ] },
  ]},

  4: { title: "Tool Use & Function Calling", questions: [
    { id: "m4q1", type: "recall", difficulty: "easy",
      objective: "Define what a tool call actually is",
      text: "What is a model 'calling a tool,' precisely?",
      opts: [ opt("The model produces a structured request (a proposal) naming a tool and arguments, your code decides whether to trust it and only then actually executes anything", true),
        opt("The model directly executes code on your server", false, "The model never directly executes anything, it only produces text describing what it wants to happen, your code is what actually runs it."),
        opt("The model sends a network request to the tool's API directly", false, "The model has no independent ability to send network requests, it produces a description of a call, your infrastructure performs the actual execution.") ] },
    { id: "m4q2", type: "application", difficulty: "medium",
      objective: "Apply schema validation before business-rule checks",
      text: "A refund tool call has correct types and all required fields, but requests $50,000 on an order that never exceeds $500. Is schema validation alone sufficient to catch this?",
      opts: [ opt("No, this passes structural validation but fails a business-rule check (amount bounds), the two are separate validation layers that catch different problems", true),
        opt("Yes, if the types and required fields are correct, the call is safe to execute", false, "Structural correctness says nothing about whether the specific VALUES make sense for this business, an amount can be a perfectly valid number and still be wrong for this order."),
        opt("No additional check is possible once the call has been generated", false, "Additional checks are standard practice, bounds checks, permission checks, and rate limits are all commonly layered on top of schema validation.") ] },
    { id: "m4q3", type: "scenario", difficulty: "hard",
      objective: "Apply idempotent execution to a lost-response scenario",
      text: "A payment tool call succeeds server-side, but the response is lost to a network blip. The model retries with the same call ID. What should the executor do?",
      opts: [ opt("Recognize the call ID as already-executed and return the cached original result, without running the handler (and its side effect) again", true),
        opt("Run the handler again since the client never received confirmation of success", false, "The client's uncertainty about the outcome doesn't change what actually happened server-side, re-running would duplicate a side effect (like a charge) that already completed."),
        opt("Reject the retry outright as a suspicious duplicate", false, "Rejecting isn't useful either, the caller still needs the actual result, returning the cached success is more useful and still safe.") ] },
    { id: "m4q4", type: "debugging", difficulty: "hard",
      objective: "Diagnose a cache-before-catch bug",
      text: "An executor caches a call's result BEFORE invoking the handler, planning to overwrite it after. On the error path, the overwrite is accidentally skipped. What's the consequence?",
      opts: [ opt("A failed attempt gets permanently marked as 'done,' incorrectly blocking any future legitimate retry with that call ID from ever getting a real attempt", true),
        opt("Nothing, the cache will just be correct once the handler eventually succeeds", false, "If the overwrite-on-success path is what actually corrects the cache, and the error path skips cleanup, a failure gets permanently stuck as cached, blocking legitimate future retries."),
        opt("The handler will simply be called twice for every request", false, "The bug described causes UNDER-calling on retry (a failed attempt is wrongly treated as complete), not over-calling.") ] },
    { id: "m4q5", type: "recall", difficulty: "medium",
      objective: "Explain why failures shouldn't be cached",
      text: "Why should only successful outcomes be cached against a call ID, not failures?",
      opts: [ opt("If nothing succeeded, there's no side effect to protect against repeating, caching a failure would block a legitimate future retry that might actually succeed", true),
        opt("Caching failures wastes more memory than caching successes", false, "Memory usage isn't the reason, the reason is correctness: caching a failure permanently blocks a legitimate retry from ever getting a real attempt."),
        opt("Failures should be cached too, for consistency with how successes are handled", false, "Treating them the same defeats the purpose of idempotency for retries, a transient failure should remain retryable, not get permanently locked in as 'done.'") ] },
    { id: "m4q6", type: "engineering-decision", difficulty: "medium",
      objective: "Decide how to respond to an unknown tool name",
      text: "A model calls a tool name that isn't in your registry. What's the correct response?",
      opts: [ opt("Reject it with a structured error naming the unknown tool, and never call any handler", true),
        opt("Execute the closest-matching known tool instead, in case the model meant that one", false, "Silently substituting a different tool (with different effects) for what was actually requested is more dangerous than rejecting the call outright."),
        opt("Log it and move on without informing the model", false, "Silence gives the model nothing to self-correct with, a structured error lets it retry with a valid tool name.") ] },
    { id: "m4q7", type: "scenario", difficulty: "medium",
      objective: "Apply repair-then-validate to tool arguments",
      text: "A tool call's arguments arrive as raw text {\"location\": \"Paris\",} (trailing comma). What's the correct order of operations before schema validation runs?",
      opts: [ opt("Repair the malformed JSON text first (strip the trailing comma, parse it), then validate the resulting object against the tool's schema", true),
        opt("Validate the raw text directly against the schema, schemas tolerate minor syntax issues", false, "Schema validation operates on a parsed object, not text with a syntax error, the trailing comma must be fixed and the text parsed before schema validation can run at all."),
        opt("Reject the call immediately, a trailing comma means the model can't be trusted with tools at all", false, "A trailing comma is a minor, mechanically-fixable formatting defect, not evidence of unreliability, the whole discipline from Module 1 is repairing these small defects rather than treating them as fatal.") ] },
    { id: "m4q8", type: "application", difficulty: "medium",
      objective: "Distinguish two different call IDs from a true duplicate",
      text: "Two DIFFERENT call IDs both invoke the same tool with similar arguments. Should the second one be treated as a duplicate and blocked?",
      opts: [ opt("No, idempotency is keyed by call ID specifically, not by tool name or argument similarity, two different IDs are two legitimately independent requests", true),
        opt("Yes, any repeated call to the same tool should be deduplicated regardless of ID", false, "That would incorrectly block legitimate independent uses of the same tool, idempotency protects against a SPECIFIC request being duplicated, not against a tool being used more than once."),
        opt("It depends on whether the arguments are byte-for-byte identical, not on the call ID at all", false, "The call ID, not argument content, is the idempotency key in this course's model, using argument matching instead would incorrectly block distinct legitimate requests that happen to look similar.") ] },
    { id: "m4q9", type: "scenario", difficulty: "medium",
      objective: "Apply the two validation layers to a real booking tool",
      text: "A calendar-booking tool's schema requires {\"date\": str, \"time\": str, \"attendee_email\": str}, all correctly typed. The requested date is in the past. Does schema validation catch this?",
      opts: [ opt("No, a past date is still a syntactically valid string in the right shape, this is a business-rule failure (the value doesn't make sense for this use case), not a structural one", true),
        opt("Yes, schema validation checks that dates are chronologically valid relative to today", false, "Schema validation checks shape and type (is this a string, is this field present), it has no built-in concept of \"today\" or chronological sense, that requires a separate business-rule check."),
        opt("No additional check is needed, the booking tool will simply reject a past date on its own when executed", false, "Assuming the underlying tool handles this gracefully isn't a safe default, the whole point of layered validation is catching a nonsensical value BEFORE the handler runs, not hoping the handler happens to guard against it.") ] },
    { id: "m4q10", type: "engineering-decision", difficulty: "medium",
      objective: "Decide the idempotency key for a multi-step checkout tool",
      text: "An e-commerce checkout tool is called once per cart. A user's flaky connection causes the client to submit the same checkout request three times within two seconds. What should the idempotency key be built from?",
      opts: [ opt("A stable identifier for THIS specific checkout attempt (e.g. a client-generated request ID tied to that cart session), not the cart contents alone, since a different legitimate checkout later with the same cart contents shouldn't be blocked as a false duplicate", true),
        opt("The cart's contents (item IDs and quantities), since identical carts should always be treated as the same request", false, "Keying off cart contents would incorrectly block a genuinely new, later purchase of the exact same items, idempotency needs to identify a specific REQUEST attempt, not a recurring pattern of contents."),
        opt("The user's account ID alone, since all of a user's requests should be deduplicated together", false, "Deduplicating by account ID alone would incorrectly merge a user's separate, legitimate purchases into one, the key needs to be specific to a single request attempt, not scoped to the whole account.") ] },
    { id: "m4q11", type: "recall", difficulty: "easy",
      objective: "State the validation order before any handler runs",
      text: "Before a tool's handler is ever invoked, what three checks does this module's pattern require, in order?",
      opts: [ opt("Does the tool exist in the registry, are the required arguments present and correctly typed, and has this call ID already succeeded (idempotency check)", true),
        opt("Only whether the arguments are correctly typed, existence and idempotency checks are optional extras", false, "All three checks are treated as required in this module's pattern, skipping the registry check or the idempotency check leaves real gaps (executing an unknown tool, or duplicating a side effect)."),
        opt("Whether the call ID has succeeded before, then tool existence, then argument types, in that order", false, "Checking idempotency before confirming the tool even exists is backwards, you'd be looking up a call record for a request that might not even name a valid tool.") ] },
  ]},

  5: { title: "Agent Architectures & Control Flow", questions: [
    { id: "m5q1", type: "recall", difficulty: "easy",
      objective: "Explain why a step limit is required",
      text: "Why does every agent loop need a hard, code-enforced step limit?",
      opts: [ opt("'The model will know when to stop' isn't a control mechanism, models can reason in circles or fail to emit a clean final answer, so the loop needs an external, non-negotiable cap", true),
        opt("Because models are only capable of a fixed number of reasoning steps before crashing", false, "Models don't have a hard-coded step ceiling that crashes them, the risk is a loop that keeps running (and costing) indefinitely without external bounds, not a technical crash."),
        opt("Step limits are only needed for loops with more than 3 available tools", false, "The number of available tools is unrelated to why a step limit is needed, the risk (unbounded cost/time) exists regardless of tool count.") ] },
    { id: "m5q2", type: "application", difficulty: "medium",
      objective: "Apply stuck-loop detection correctly",
      text: "An agent issues the exact same tool call (same tool, same arguments) three times in a row. What should the loop do?",
      opts: [ opt("Stop early and report a 'stuck' outcome, rather than continuing to burn steps up to the limit repeating an unproductive pattern", true),
        opt("Keep going, the model will eventually try something different", false, "That's the exact trap this concept exists to prevent, an unguarded loop has no reason to assume the model will spontaneously change approach."),
        opt("Immediately raise the step limit to give it more room", false, "Raising the limit doesn't fix repeating the SAME action, more steps just means more identical unproductive attempts.") ] },
    { id: "m5q3", type: "debugging", difficulty: "hard",
      objective: "Diagnose a repeat-counter reset bug",
      text: "A loop's stuck-detector increments a repeat counter every step but never resets it when the action CHANGES. Actions alternate: fetch, parse, fetch, parse, then a final answer. What false result could this cause?",
      opts: [ opt("The counter could accumulate across DIFFERENT actions and falsely trigger 'stuck' even though nothing actually repeated 3 times in a row, incorrectly cutting off real progress", true),
        opt("Nothing, alternating actions never trigger stuck-detection regardless of reset logic", false, "Without a reset-on-change, the counter keeps climbing across ANY action (same or different), which can falsely trigger stuck detection on a genuinely alternating, productive sequence."),
        opt("The loop would run forever since the counter never reaches the threshold", false, "The opposite is true, a counter that never resets climbs continuously regardless of which action occurs, reaching the threshold too EARLY and falsely, not never.") ] },
    { id: "m5q4", type: "recall", difficulty: "medium",
      objective: "Enumerate the three loop termination conditions",
      text: "What are the three distinct, valid ways a well-bounded agent loop can end?",
      opts: [ opt("Success (a distinct final-answer signal), step limit reached, or stuck (repeated identical action detected)", true),
        opt("Only success, a properly designed loop should never hit a step limit or get stuck", false, "Relying on only one termination path is the exact failure mode this module warns against, a model that never emits a clean final answer needs a real backstop."),
        opt("Only the step limit, since that's the one guaranteed to always trigger eventually", false, "Relying only on the step limit means every task, even a clearly stuck one, runs to the full maximum budget, wasting cost that early stuck-detection would save.") ] },
    { id: "m5q5", type: "engineering-decision", difficulty: "medium",
      objective: "Decide whether idempotency alone prevents loop spinning",
      text: "Module 4's idempotent executor returns a cached result for a repeated call ID. Does this alone prevent an agent loop from spinning on the same failing action forever?",
      opts: [ opt("No, idempotency prevents a repeat from causing a NEW side effect, it doesn't limit how many times the loop itself keeps trying, that's the loop's own step-limit/stuck-detection job", true),
        opt("Yes, an idempotent executor automatically caps how many times a loop can call the same tool", false, "Idempotency has no concept of a loop-wide call count, it only tracks whether a SPECIFIC call ID has already succeeded, a narrower guarantee than a loop-wide bound."),
        opt("Yes, because a cached result means the loop stops calling tools after the first attempt", false, "The loop can still keep calling step() and issuing new tool-call attempts (often with fresh call IDs) indefinitely, a cached result for one ID doesn't stop the surrounding loop.") ] },
    { id: "m5q6", type: "scenario", difficulty: "medium",
      objective: "Distinguish step-limit from stuck as different signals",
      text: "Why distinguish 'hit the step limit' from 'detected stuck' instead of logging both the same way as 'didn't finish'?",
      opts: [ opt("They point to different problems: hitting the limit on a hard task suggests the budget may be too small, while getting stuck after 3 identical actions suggests something is actually broken regardless of budget size", true),
        opt("There's no meaningful difference, both always indicate the same underlying bug", false, "They indicate genuinely different situations, a hard task needing more budget is not the same problem as a tool returning an error the model can't act on."),
        opt("Stuck detection is just a special case of the step limit being set too low", false, "Stuck detection triggers regardless of how high the step limit is set, even a very generous limit doesn't prevent 3 identical actions in a row from being flagged as stuck.") ] },
    { id: "m5q7", type: "calculation", difficulty: "medium",
      objective: "Trace a loop's step count",
      text: "A loop's step() returns: action, action, action (all different), then final on the 4th call. What's stepsUsed when it returns?",
      opts: [ opt("4, the final call that returns the answer counts as a step too", true),
        opt("3, only the action steps count, not the one returning the final answer", false, "The call to step() that returns 'final' is still an iteration of the loop, it counts toward the total steps used."),
        opt("5, one extra step is needed to confirm the final answer", false, "There's no extra confirmation step in this model, the loop ends the moment step() returns type:'final', which is the 4th call here.") ] },
    { id: "m5q8", type: "recall", difficulty: "easy",
      objective: "Define a trace",
      text: "What is a trace, in the context of an agent loop?",
      opts: [ opt("The ordered record of actions (and often reasoning) an agent loop produced, used for debugging and for detecting repetition", true),
        opt("A separate log file only written after the loop crashes", false, "A trace is built up continuously as the loop runs, not only produced on crash, it's the ongoing record of what the loop did."),
        opt("The final answer text returned by the loop", false, "The final answer is the loop's OUTPUT, the trace is the record of the STEPS taken to get there, a different thing entirely.") ] },
    { id: "m5q9", type: "scenario", difficulty: "medium",
      objective: "Apply stuck-detection to near-identical but distinct actions",
      text: "A data-pipeline-repair agent calls fix_column(name=\"email\") three times in a row, but each call includes a DIFFERENT proposed fix in its arguments (e.g. a different regex each time). Should this trip stuck-detection the same way three byte-for-byte identical calls would?",
      opts: [ opt("Only if stuck-detection is defined to match on tool name AND arguments together, if it matches on tool name alone, this would be a false trigger, since the agent is actually trying different approaches, not repeating the same one", true),
        opt("Yes, always, calling the same tool three times in a row is inherently a sign of being stuck regardless of arguments", false, "Matching on tool name alone conflates \"trying variations of the same fix\" with \"repeating the exact same failed action\", these are different situations and a well-designed detector distinguishes them."),
        opt("No, stuck-detection should never consider tool name at all, only exact argument matches count", false, "Ignoring tool name entirely would miss the actual repeating-identical-call case this module is built around, the detector needs BOTH pieces of information to correctly distinguish repetition from genuine variation.") ] },
    { id: "m5q10", type: "debugging", difficulty: "hard",
      objective: "Diagnose a step-limit check placed after side-effecting work",
      text: "A loop checks stepsUsed >= maxSteps only at the very TOP of each iteration, but the tool call for that iteration still executes even when the check would have failed, because the check runs before incrementing but after the previous iteration's call already ran. Concretely: what's the actual risk if the step-limit check is accidentally placed AFTER a tool call executes, rather than before?",
      opts: [ opt("The loop can execute one more tool call (with real side effects) past its intended limit before finally stopping, since the check that should have prevented it runs too late", true),
        opt("There's no risk, checking before or after a tool call produces identical behavior either way", false, "Order matters specifically because a tool call can have a real side effect, checking the limit AFTER a call has already run means that call's side effect already happened, even though the limit says it shouldn't have."),
        opt("The loop would stop one step too early instead of one step too late", false, "A check placed after the call executes allows one EXTRA call through, not one fewer, the direction of the bug is over-running the limit, not under-running it.") ] },
    { id: "m5q11", type: "recall", difficulty: "medium",
      objective: "Explain why a step limit alone doesn't prevent bad outcomes",
      text: "A loop has a strict step limit of 8 and never exceeds it. Does this guarantee the loop's behavior is otherwise safe?",
      opts: [ opt("No, a step limit only bounds HOW LONG the loop can run, it says nothing about whether individual steps are safe (idempotent tool execution), whether the loop is stuck repeating itself, or whether the final answer is even correct", true),
        opt("Yes, a strict step limit is sufficient on its own to guarantee safe agent behavior", false, "A step limit is one of several independent safeguards this course covers (alongside idempotent execution and stuck-detection), it bounds duration/cost, not correctness or safety of what happens within each step."),
        opt("Yes, because a bounded loop can never repeat the same action more than the step limit allows", false, "A step limit bounds TOTAL steps, but doesn't by itself detect or prevent REPEATING the same unproductive action across those steps, that's specifically what stuck-detection is for.") ] },
  ]},

  6: { title: "Reliability for LLM Systems", questions: [
    { id: "m6q1", type: "recall", difficulty: "easy",
      objective: "Classify a 429 as retryable",
      text: "A model API call fails with a 429 (rate limited). Should this be retried?",
      opts: [ opt("Yes, a 429 is transient, the request itself is fine, retrying with backoff has a real chance of succeeding", true),
        opt("No, a 429 means the request was rejected and must be changed first", false, "A 429 doesn't mean the request was invalid, it means too many requests arrived too quickly, the identical request sent again after a delay is very likely to succeed."),
        opt("It depends only on which provider returned the error", false, "429 has a consistent meaning (rate limiting) across virtually all HTTP APIs, provider identity doesn't change whether this specific error is transient.") ] },
    { id: "m6q2", type: "application", difficulty: "medium",
      objective: "Classify a 400 as non-retryable",
      text: "A call fails with a 400 because your own request body was malformed. Should this be retried as-is?",
      opts: [ opt("No, the request is malformed, retrying the exact same request will fail identically every time, it needs to be FIXED, not retried", true),
        opt("Yes, with enough retries and backoff it will eventually succeed", false, "No amount of waiting fixes a structurally invalid request, it will fail on attempt 10 exactly as it failed on attempt 1."),
        opt("Yes, but only if a fallback model is also configured", false, "Fallback doesn't fix a malformed request either, sending the SAME malformed request to a different model has no reason to succeed there.") ] },
    { id: "m6q3", type: "calculation", difficulty: "medium",
      objective: "Compute a capped backoff delay",
      text: "Base delay 250ms, cap 4000ms. Using min(cap, base × 2^attempt), what's the maximum possible delay before retry attempt 5 (exponent 4, since 250 × 2^4 = 4000)?",
      opts: [ opt("4000ms, exactly at the cap", true),
        opt("4250ms, the base gets added on top of the capped value", false, "The formula is min(cap, ...), not cap-plus-base, once the exponential value reaches or exceeds the cap, the cap itself is the answer, nothing is added on top."),
        opt("2000ms, half the cap", false, "250 × 2^4 = 4000 exactly, which equals the cap, not half of it.") ] },
    { id: "m6q4", type: "recall", difficulty: "medium",
      objective: "Explain why full jitter matters",
      text: "Why does full jitter (random delay between 0 and the cap) outperform a fixed exponential delay under concurrent load?",
      opts: [ opt("Fixed delays cause many simultaneously-failed callers to retry at the exact same instant (a retry storm), jitter spreads retries across a window instead of concentrating them", true),
        opt("Jitter makes each individual retry succeed with higher probability than a fixed delay would", false, "Jitter doesn't change any single retry's odds of success, its benefit is about the AGGREGATE pattern across many concurrent callers, not any one caller's odds."),
        opt("Jitter is only relevant when there's exactly one caller retrying", false, "The retry-storm problem jitter solves specifically requires MULTIPLE concurrent callers, a single caller retrying alone has no synchronization problem to begin with.") ] },
    { id: "m6q5", type: "engineering-decision", difficulty: "medium",
      objective: "Decide fallback's retry budget",
      text: "Should a fallback model call be retried with the same generous budget as the primary?",
      opts: [ opt("No, fallback should get a single bounded attempt (or a much smaller budget), if both primary and fallback need extensive retries the issue is likely broader than one provider's outage", true),
        opt("Yes, fallback deserves the exact same retry budget as the primary for fairness", false, "Giving fallback the same generous budget as the primary risks doubling total latency and cost when both paths are struggling, undermining the entire point of having a bounded backstop."),
        opt("No, fallback should never be retried at all, even once", false, "A single retry attempt on fallback is still reasonable, the point is bounding it tightly, not eliminating any chance of a second try entirely.") ] },
    { id: "m6q6", type: "debugging", difficulty: "hard",
      objective: "Diagnose a retryable-check-order bug",
      text: "A wrapper checks 'attempt >= max_retries' but never checks whether the error is retryable at all. A non-retryable error occurs with max_retries=5. What happens?",
      opts: [ opt("The non-retryable error gets retried 5 extra times anyway (6 total calls) before finally giving up, wasting calls on a request guaranteed to fail every time", true),
        opt("Nothing wrong happens, the retry count check alone is sufficient for correct behavior", false, "Without checking retryable status independently, a permanent failure gets treated the same as a transient one, wasting the entire retry budget on guaranteed failures."),
        opt("The function raises immediately on the first attempt regardless of max_retries", false, "With only an attempt-count check and no retryable check, the code KEEPS retrying up to the count, it doesn't stop early, that's precisely the bug.") ] },
    { id: "m6q7", type: "scenario", difficulty: "medium",
      objective: "Reason about ambiguous error classification",
      text: "A provider returns the same generic 500 for both truly transient faults and permanent failures. How should 'unknown' errors be classified by default?",
      opts: [ opt("Treat them as retryable, but always with a bounded retry count, a spurious retry on a permanent failure costs one bounded extra attempt, while wrongly treating a transient failure as non-retryable throws away a request a retry would have saved", true),
        opt("Treat them as non-retryable by default to be safe", false, "This is the more expensive default, it discards potentially-transient failures that a bounded retry would likely have resolved."),
        opt("Alternate between retryable and non-retryable each time this ambiguous error occurs", false, "Randomly alternating classification adds unpredictability with no actual benefit, a consistent, bounded default handles the ambiguity correctly.") ] },
    { id: "m6q8", type: "application", difficulty: "medium",
      objective: "Apply the bounded-everything principle",
      text: "An agent loop has a step limit of 10, but each step's internal retry-and-fallback wrapper has an unbounded retry count. What actually breaks?",
      opts: [ opt("The step COUNT stays capped at 10, but each individual step can now take unpredictably long or cost far more, since an unbounded retry inside one step defeats the point of bounding the number of steps", true),
        opt("Nothing breaks, the step limit of 10 automatically caps total retries across the whole loop", false, "The step limit counts loop ITERATIONS, it has no awareness of how many times a retry wrapper retries WITHIN a single step, those are separate, independent bounds."),
        opt("The agent loop raises an error once retries exceed the step limit", false, "There's no automatic interaction between an internal retry count and the outer loop's step counter unless they're explicitly wired together, which an unbounded retry count specifically fails to do.") ] },
    { id: "m6q9", type: "scenario", difficulty: "medium",
      objective: "Apply retryable classification to a real payment-processor integration",
      text: "A payment-processor API returns a 503 during a flash sale's traffic spike, and separately returns a 402 for a specific card being declined. Should both be handled the same way?",
      opts: [ opt("No, the 503 is a transient overload signal, retryable with backoff, the 402 (card declined) is a permanent outcome for that specific card, retrying the identical charge won't change the decline", true),
        opt("Yes, both should be retried the same number of times since they're both payment failures", false, "Treating a card decline as retryable wastes attempts on a request guaranteed to fail again, and can look like repeated unauthorized charge attempts to the customer, they need different handling."),
        opt("Yes, both should be treated as non-retryable to avoid ever double-charging a customer", false, "Treating a genuinely transient 503 as non-retryable throws away a request a bounded, backed-off retry would likely have completed successfully, that's the opposite failure mode from double-charging.") ] },
    { id: "m6q10", type: "engineering-decision", difficulty: "medium",
      objective: "Decide the fallback strategy for a logistics-routing API",
      text: "A shipping-rate API used by a logistics router has occasional multi-second timeouts under load, with a slower but reliable backup provider available. How should the fallback be structured relative to retries on the primary?",
      opts: [ opt("Retry the primary a bounded number of times with backoff, then, only if that budget is exhausted, try the backup provider once, rather than immediately failing over on the first timeout or retrying the primary indefinitely", true),
        opt("Skip retries entirely and fail over to the backup provider on the very first timeout", false, "Failing over immediately on a single timeout throws away the common case where a quick backed-off retry on the primary would have succeeded, wasting the backup path's slower response time unnecessarily."),
        opt("Retry the primary with an unbounded retry count before ever considering the backup", false, "An unbounded retry count on the primary defeats the purpose of having a backup at all, and risks the caller waiting indefinitely for a provider that may be down for an extended period.") ] },
    { id: "m6q11", type: "recall", difficulty: "easy",
      objective: "State the bounded call shape in one sentence",
      text: "In one sentence, what does a correctly bounded reliability wrapper around a model or API call guarantee?",
      opts: [ opt("A retryable failure gets a bounded number of backed-off retries on the primary, a non-retryable failure fails fast, and if the primary's budget is exhausted, exactly one bounded fallback attempt is made before giving up with a clear failure", true),
        opt("Every failure, retryable or not, gets retried until either it succeeds or a global timeout is hit", false, "This ignores the retryable-vs-not distinction entirely, retrying a non-retryable failure until timeout wastes the whole budget on a request that was guaranteed to fail from the first attempt."),
        opt("The primary is retried without limit, and no fallback is used, since a well-built primary should never need one", false, "This course's model explicitly bounds primary retries AND includes a fallback path, an unbounded primary with no fallback is exactly the unbounded-risk pattern the module warns against.") ] },
  ]},

  7: { title: "Evaluation, Testing & Observability", questions: [
    { id: "m7q1", type: "recall", difficulty: "easy",
      objective: "Explain why spot-checking isn't evaluation",
      text: "Why doesn't 'I read a few outputs and they looked fine' substitute for a systematic eval?",
      opts: [ opt("It's an unrepresentative sample judged by inconsistent, undocumented criteria, with no repeatable number to compare against a baseline later", true),
        opt("It's fine for small projects, systematic eval is only needed at production scale", false, "The problem isn't project scale, it's rigor, even a small project can't reliably tell whether a change helped or hurt without a systematic, repeatable score."),
        opt("It doesn't substitute for eval only when outputs are structured (JSON)", false, "The reasoning applies regardless of output format, an unrepresentative, inconsistently-judged sample doesn't produce a trustworthy signal for structured OR free-text outputs.") ] },
    { id: "m7q2", type: "recall", difficulty: "medium",
      objective: "Explain the core LLM-as-judge risk",
      text: "What specific risk does LLM-as-judge scoring introduce that a deterministic exact-match check doesn't have?",
      opts: [ opt("The judge's own grading is itself an unverified model output, it can be inconsistent or biased, unlike fixed logic that behaves identically on identical input every time", true),
        opt("LLM-as-judge is always slower, that's its only real downside compared to deterministic checks", false, "Speed is a real cost, but not the core risk this concept highlights, the deeper issue is that the judge's scoring isn't guaranteed to be consistent or correct."),
        opt("There's no meaningful difference, both approaches carry identical reliability risk", false, "There is a meaningful difference, a deterministic check produces the exact same result every time on the same input, an LLM judge is not guaranteed to.") ] },
    { id: "m7q3", type: "engineering-decision", difficulty: "medium",
      objective: "Prefer deterministic checks where they apply",
      text: "When a task's correctness CAN be checked with fixed logic (schema validation, exact match), which approach should be preferred over LLM-as-judge?",
      opts: [ opt("The deterministic check, it's consistent, cheap, and exactly reproducible, wherever a fixed correct answer or shape exists", true),
        opt("LLM-as-judge, since it generalizes better even to cases with a known correct answer", false, "When a fixed correct answer or shape already exists, there's nothing an LLM judge adds that a deterministic check doesn't already handle exactly and consistently."),
        opt("Whichever is cheaper to run for this specific test case", false, "Cost isn't the deciding tradeoff here, deterministic checks are both cheaper AND more reliable when they apply, there's no real tradeoff to weigh.") ] },
    { id: "m7q4", type: "application", difficulty: "medium",
      objective: "Apply the regression definition",
      text: "An eval run scores 0.70 against a recorded baseline of 0.75. Using this course's definition, is this a regression?",
      opts: [ opt("Yes, the new score (0.70) is lower than the baseline (0.75), meeting the definition of a regression", true),
        opt("No, a 5-point difference is too small to count as a real regression", false, "The definition used in this course is simply 'lower than baseline', there's no minimum-magnitude exemption, any measurable drop below baseline counts."),
        opt("It can't be determined without knowing the exact test cases used", false, "The regression definition only requires comparing the score to the baseline, 0.70 < 0.75 is sufficient to classify it as a regression regardless of which specific cases were included.") ] },
    { id: "m7q5", type: "debugging", difficulty: "hard",
      objective: "Diagnose an eval harness that lets one bad checker crash everything",
      text: "An eval harness's loop calls tc['check'](actual) with no try/except around it. One test case's check() function has a bug and raises. What happens to the other test cases?",
      opts: [ opt("The exception propagates up out of the loop and crashes the entire evaluation, losing results for every other test case too, not just the broken one", true),
        opt("Nothing, Python automatically isolates each loop iteration from exceptions raised in other iterations", false, "A for-loop has no built-in per-iteration exception isolation, an unhandled raise inside the loop body stops the loop immediately and propagates out."),
        opt("Only that one test case is marked failed, the rest continue normally by default", false, "Without an explicit try/except around the check() call specifically, there's no default per-case isolation, the exception aborts the whole run.") ] },
    { id: "m7q6", type: "scenario", difficulty: "medium",
      objective: "Reason about isolating variables before evaluating",
      text: "A team changes their system prompt AND their retrieval top-k value in one deploy, then runs the eval suite once and sees a score drop. What's the practical downside of evaluating both changes together?",
      opts: [ opt("They can't tell which change caused the drop, or whether one change improved things while the other hurt worse, isolating the cause now requires re-running the eval with each change separated", true),
        opt("Nothing, the eval score reflects reality either way regardless of how many things changed", false, "The score is accurate as an aggregate outcome, but it conflates the effects of both changes, making the CAUSE ambiguous, which is the actual practical problem."),
        opt("The eval suite itself becomes invalid once more than one variable changes between runs", false, "The eval suite still produces a valid, meaningful score, the issue isn't the suite's validity, it's that attributing the cause of the change becomes ambiguous.") ] },
    { id: "m7q7", type: "recall", difficulty: "easy",
      objective: "Define a golden dataset",
      text: "What is a 'golden dataset' in the context of evaluation?",
      opts: [ opt("A curated, hand-labeled test set updated carefully and deliberately over time, since eval quality is bounded by the quality and coverage of its test cases", true),
        opt("The single highest-scoring output an eval run has ever produced", false, "This describes a best individual result, not the curated test-set concept a golden dataset actually refers to."),
        opt("An automatically-generated set of test cases requiring no human review", false, "A golden dataset is specifically hand-labeled and carefully curated, the opposite of an unreviewed automatically-generated set.") ] },
    { id: "m7q8", type: "application", difficulty: "medium",
      objective: "Design a test case with a real criterion",
      text: "A proposed eval test case has an input and an 'expected' field reading '(judge if the summary is good)'. What's missing for this to be a usable eval case?",
      opts: [ opt("An explicit, checkable criterion, not an implicit request to judge quality, without one, different reviewers (or the same reviewer on different days) will score it inconsistently", true),
        opt("Nothing is missing, this is already a complete and usable eval test case", false, "An implicit 'judge if it's good' provides no fixed criterion, that's exactly the kind of inconsistent, unrepeatable scoring a real eval case needs to avoid."),
        opt("Only the input is missing, the expected field alone is sufficient", false, "The input is actually present here, what's missing is a defined, checkable criterion, not the input.") ] },
    { id: "m7q9", type: "scenario", difficulty: "medium",
      objective: "Apply deterministic-vs-judge reasoning to a real classification eval",
      text: "A support-ticket classifier assigns one of five fixed categories to each ticket. An engineer proposes evaluating it with an LLM judge that reads the ticket and the assigned category and rates 1-5 how appropriate it seems. Is this the right approach?",
      opts: [ opt("No, each ticket in a labeled eval set has one correct category, an exact-match deterministic check against the labeled answer is cheaper, consistent, and exactly reproducible, an LLM judge adds unnecessary unreliability to a problem that already has a fixed correct answer", true),
        opt("Yes, an LLM judge is always a better choice since it can account for nuance a simple match can't", false, "There's no nuance to account for when a fixed-category classification task already has one correct labeled answer per ticket, that's precisely the situation where a deterministic check is both sufficient and preferable."),
        opt("Yes, but only if the categories have similar-sounding names that a script might confuse", false, "Even with similar-sounding category names, an exact string match against the labeled correct category is still a deterministic, reliable check, category-name similarity doesn't require introducing judge-based scoring.") ] },
    { id: "m7q10", type: "debugging", difficulty: "hard",
      objective: "Diagnose a baseline that was recorded against the wrong eval set",
      text: "A team's recorded baseline score (0.88) was computed on an earlier, smaller eval set. They've since added 20 new labeled cases to the eval set but kept using the old baseline number for regression comparisons. What's wrong with this setup?",
      opts: [ opt("The baseline and the current eval set are no longer the same measurement, comparing a new score (on the expanded set) against an old baseline (on the smaller set) can flag false regressions or hide real ones, since the score's meaning changed when the test set changed", true),
        opt("Nothing is wrong, a baseline score is valid indefinitely regardless of what's later added to the eval set", false, "A baseline is only a meaningful comparison point for the SAME eval set it was measured on, expanding the set changes what the score represents, the baseline needs to be re-recorded on the new set."),
        opt("The only problem is that the eval now takes longer to run, the comparison itself is still valid", false, "Runtime isn't the issue, the actual problem is a mismatch in what's being measured, comparing scores across two different-sized test sets isn't a like-for-like regression check.") ] },
    { id: "m7q11", type: "recall", difficulty: "medium",
      objective: "Explain why every check() call needs independent error isolation",
      text: "Why does this module recommend wrapping each individual test case's check() call in its own try/except, rather than one try/except around the entire eval loop?",
      opts: [ opt("One try/except around the whole loop still lets a single bad checker abort every remaining test case, wrapping each call individually isolates a broken checker to just its own case so the rest of the suite still runs and reports", true),
        opt("There's no real difference, a single try/except around the whole loop provides the same per-case isolation", false, "A try/except around the WHOLE loop still exits the loop entirely the first time any single check() raises, it doesn't isolate failures to individual cases the way a per-call try/except does."),
        opt("Per-case try/except is only needed when the eval set has more than 50 test cases", false, "The isolation benefit has nothing to do with eval set size, even a 3-case suite benefits from one broken checker not silently discarding the other two cases' results.") ] },
  ]},
};

const MIXED_QUIZZES = [
  { id: "mix_1_3", title: "Mixed Quiz: Modules 1–3", modules: [1, 2, 3], perModule: 3 },
  { id: "mix_4_5", title: "Mixed Quiz: Modules 4–5", modules: [4, 5], perModule: 4 },
  { id: "mix_6_7", title: "Mixed Quiz: Modules 6–7", modules: [6, 7], perModule: 4 },
];

function shuffle(arr) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function masteryBand(pct) {
  if (pct >= 90) return { label: "Mastered", cls: "mastered" };
  if (pct >= 80) return { label: "Strong", cls: "strong" };
  if (pct >= 70) return { label: "Needs review", cls: "review" };
  return { label: "Revisit module", cls: "revisit" };
}

global.QuizData = { POOLS, MIXED_QUIZZES, shuffle, masteryBand };
})(window);
