/* Zenith Lab — Data Science & Analysis Quiz Center question pools.
   Each core module (1-8) has a 6-question pool; a quiz attempt shuffles the
   pool and randomizes option order, so repeat attempts genuinely differ.
   Module 9 is the capstone (rubric-graded, not multiple-choice) and has no
   entry here, matching how it's graded elsewhere in the course. */
(function (global) {

function opt(t, correct, why) { return { t, correct, why: why || "" }; }

const POOLS = {
  1: { title: "Spreadsheet & Data Literacy Foundations", questions: [
    { id: "m1q1", type: "recall", difficulty: "easy",
      objective: "Explain what a dataset is structurally",
      text: "In a dataset, what does a single row represent?",
      opts: [ opt("One observation, one order, one employee, one survey response", true),
        opt("One variable, like 'revenue' or 'region'", false, "That's what a COLUMN represents, not a row. Rows are observations, columns are variables."),
        opt("A formula applied to the whole sheet", false, "A row is data, not a formula. Formulas live in individual cells.") ] },
    { id: "m1q2", type: "application", difficulty: "medium",
      objective: "Choose the right formula for a counting question",
      text: "You need to know how many orders came from the 'West' region. Which formula answers that directly?",
      opts: [ opt("COUNTIF(range, \"West\")", true),
        opt("SUM(range)", false, "SUM adds numeric values, it doesn't count text matches."),
        opt("AVERAGE(range)", false, "AVERAGE computes a mean, it has nothing to do with counting occurrences of a category.") ] },
    { id: "m1q3", type: "scenario", difficulty: "medium",
      objective: "Recognize a tidy-data violation",
      text: "A 'Phone' column has some rows as \"555-1234\" and others as \"(555) 123-4\". What does this violate?",
      opts: [ opt("Tidy data: one column should hold one consistent format, not mixed representations", true),
        opt("Nothing, spreadsheets treat both the same internally", false, "They're stored as different text strings, which breaks sorting, filtering, and any lookup keyed on that column."),
        opt("This is only a problem once the data reaches Python", false, "It's a problem the moment the data exists this way, it just gets worse once it reaches pandas or SQL.") ] },
    { id: "m1q4", type: "application", difficulty: "medium",
      objective: "Identify XLOOKUP's real function",
      text: "What does XLOOKUP fundamentally do?",
      opts: [ opt("Finds a value in one table using a matching key from another table", true),
        opt("Sorts a column from smallest to largest", false, "That's what clicking a column header (or using SORT) does, not XLOOKUP."),
        opt("Removes duplicate rows from a range", false, "That's a different operation entirely, XLOOKUP retrieves a matching value, it doesn't deduplicate.") ] },
    { id: "m1q5", type: "recall", difficulty: "easy",
      objective: "Justify why sorting is a safe first move",
      text: "Why is sorting a safer first step on unfamiliar data than writing a formula that overwrites a column?",
      opts: [ opt("Sorting never changes the underlying data, it's always safe to undo", true),
        opt("Sorting is faster to type", false, "Speed isn't the reason, safety is: sorting can't corrupt the source data the way an overwriting formula can."),
        opt("Formulas can never be undone, sorting always can", false, "Most formulas CAN be undone. The real distinction is that sorting/filtering never modify the source values at all.") ] },
    { id: "m1q6", type: "recall", difficulty: "easy",
      objective: "State the tidy-data cell rule",
      text: "Under the tidy-data principle, what should a single cell contain?",
      opts: [ opt("A single value", true),
        opt("Multiple related values, separated by commas", false, "That's exactly what tidy data forbids, it breaks sorting, filtering, and formulas."),
        opt("Always a formula, never a literal value", false, "Tidy data says nothing about formula vs. literal, only that a cell should hold one value either way.") ] },
  ] },

  2: { title: "Python Foundations for Data", questions: [
    { id: "m2q1", type: "recall", difficulty: "easy",
      objective: "Distinguish a list from a dictionary",
      text: "You want to represent one row of data with named fields like 'name' and 'revenue'. Which Python structure fits best?",
      opts: [ opt("A dictionary, so each value has a named key", true),
        opt("A list, since order alone is enough to represent named fields", false, "A list only has position, not names, you'd have to remember that index 0 means 'name' and index 1 means 'revenue', a dictionary makes that explicit."),
        opt("A single string containing all the values", false, "A string would need to be re-parsed to get individual fields back out, a dictionary already holds them as separate, accessible values.") ] },
    { id: "m2q2", type: "application", difficulty: "medium",
      objective: "Understand what a for-loop over rows accomplishes",
      text: "Why would you loop over a list of dictionaries (one per row) when hand-parsing a CSV?",
      opts: [ opt("To apply the same operation, like extracting a field, to every row without repeating code", true),
        opt("Because Python requires a loop to read any file at all", false, "Python can read a whole file at once, the loop is for processing each row, not for reading the file itself."),
        opt("To sort the rows automatically", false, "A loop doesn't sort anything by itself, you'd need an explicit sort operation for that.") ] },
    { id: "m2q3", type: "debugging", difficulty: "medium",
      objective: "Diagnose a type-mismatch bug",
      text: "Code reads a CSV column of prices as strings, then tries `total = total + price` and gets a TypeError. What's wrong?",
      opts: [ opt("price is still a string; it needs to be converted with float() or int() before it can be added to a running numeric total", true),
        opt("The variable name 'total' is invalid in Python", false, "'total' is a perfectly valid variable name, the error is about types, not naming."),
        opt("CSV files can't contain numbers", false, "CSV files can absolutely contain numbers, but everything read from a CSV comes in as text (a string) until you explicitly convert it.") ] },
    { id: "m2q4", type: "recall", difficulty: "easy",
      objective: "Explain why functions matter",
      text: "Why write a function instead of copy-pasting the same block of code five times?",
      opts: [ opt("A function lets you reuse and fix logic in one place instead of five", true),
        opt("Functions run faster than any other Python code", false, "Speed isn't the primary reason here, reuse and maintainability are."),
        opt("Python requires functions for any code longer than 3 lines", false, "There's no such length requirement in Python, functions are a choice for organizing reusable logic.") ] },
    { id: "m2q5", type: "scenario", difficulty: "medium",
      objective: "Connect hand-parsing to what pandas automates",
      text: "After hand-parsing a CSV with plain Python loops and dictionaries, what does pandas' `read_csv()` actually save you from doing?",
      opts: [ opt("Manually splitting each line, handling the header row, and converting types row by row", true),
        opt("Nothing, pandas and hand-written loops do fundamentally different things", false, "They do the same underlying job, read structured rows into memory, pandas just automates and optimizes what you did by hand."),
        opt("Only saves you from writing comments", false, "pandas automates real parsing and type-handling work, not just documentation.") ] },
    { id: "m2q6", type: "recall", difficulty: "easy",
      objective: "Identify a conditional's purpose",
      text: "What is an `if` statement used for?",
      opts: [ opt("Branching: running different code depending on whether a condition is true or false", true),
        opt("Repeating a block of code a fixed number of times", false, "That's what a loop does. `if` branches once, based on a condition, it doesn't repeat anything."),
        opt("Defining a reusable block of code", false, "That's what a function does, `if` doesn't define anything reusable on its own.") ] },
  ] },

  3: { title: "Pandas & NumPy Fundamentals", questions: [
    { id: "m3q1", type: "recall", difficulty: "easy",
      objective: "Identify pandas' core structure",
      text: "What is a pandas DataFrame, structurally?",
      opts: [ opt("A 2-dimensional table of rows and columns, with labeled columns and an index", true),
        opt("A single column of values with no row structure", false, "That describes a Series, a DataFrame is the full table, made of multiple Series."),
        opt("A Python dictionary with no tabular structure at all", false, "A DataFrame is genuinely tabular, rows and columns, not just a flat key-value mapping.") ] },
    { id: "m3q2", type: "application", difficulty: "medium",
      objective: "Choose groupby for an aggregation question",
      text: "You need total revenue per region from a DataFrame of orders. What's the right approach?",
      opts: [ opt("df.groupby('region')['revenue'].sum()", true),
        opt("df.sort_values('region')", false, "Sorting reorders rows, it doesn't aggregate or sum anything by group."),
        opt("df['region'].unique()", false, "unique() lists the distinct region names, it doesn't compute any totals.") ] },
    { id: "m3q3", type: "scenario", difficulty: "medium",
      objective: "Recognize when a merge/join is needed",
      text: "You have an orders table with a customer_id column, and a separate customers table with customer details. How do you combine them into one table?",
      opts: [ opt("pd.merge() on the shared customer_id key", true),
        opt("pd.concat() stacking them on top of each other", false, "concat() stacks rows or columns together as-is, it doesn't match rows by a shared key the way merge() does."),
        opt("df.groupby('customer_id')", false, "groupby aggregates rows within ONE table, it doesn't combine two separate tables.") ] },
    { id: "m3q4", type: "recall", difficulty: "easy",
      objective: "Explain vectorization",
      text: "Why is `df['total'] = df['price'] * df['qty']` preferred over looping row by row in Python?",
      opts: [ opt("It's vectorized: NumPy applies the operation to the whole column at once, much faster than a Python loop", true),
        opt("It's the only syntax pandas accepts", false, "Row-by-row loops are technically possible in pandas, they're just far slower and considered bad practice."),
        opt("It changes the underlying data type automatically", false, "Vectorization is about speed and style, not automatic type conversion.") ] },
    { id: "m3q5", type: "debugging", difficulty: "hard",
      objective: "Diagnose a merge producing duplicate rows",
      text: "After merging two tables on customer_id, the row count is much higher than expected. What's the most likely cause?",
      opts: [ opt("customer_id isn't unique in one of the tables, so each match produces multiple combined rows", true),
        opt("merge() always duplicates every row by default", false, "merge() doesn't inherently duplicate rows, duplication happens specifically when the join key isn't unique on one or both sides."),
        opt("The columns were named differently in each table", false, "Mismatched column names would usually cause a merge to fail or produce no matches, not extra rows.") ] },
    { id: "m3q6", type: "recall", difficulty: "easy",
      objective: "Distinguish filtering from sorting in pandas",
      text: "df[df['revenue'] > 1000] does what?",
      opts: [ opt("Filters to only rows where revenue exceeds 1000", true),
        opt("Sorts all rows by revenue, descending", false, "Sorting uses sort_values(), this expression is a boolean filter, not a sort."),
        opt("Deletes the revenue column entirely", false, "This doesn't touch columns at all, it selects a subset of rows based on a condition.") ] },
  ] },

  4: { title: "Data Cleaning & Validation", questions: [
    { id: "m4q1", type: "scenario", difficulty: "medium",
      objective: "Diagnose a mixed-type column",
      text: "A 'price' column has some values like \"$1,200\" and others like 1200.50. What's the right first move?",
      opts: [ opt("Strip currency symbols and commas, then coerce the whole column to a consistent numeric type", true),
        opt("Delete the rows with the \"$1,200\" format", false, "Deleting real data because of a formatting inconsistency throws away information you can actually recover with cleaning."),
        opt("Leave it as-is, pandas will figure out the type automatically", false, "pandas will treat a mixed-format column as text (object dtype), any numeric operation on it will fail or behave wrong until it's cleaned.") ] },
    { id: "m4q2", type: "recall", difficulty: "easy",
      objective: "Distinguish duplicates from legitimate repeats",
      text: "Two rows have the exact same customer name, 'John Smith'. Why might this NOT be a duplicate to remove?",
      opts: [ opt("They could be two different real customers who happen to share a common name", true),
        opt("Duplicates never actually happen in real data", false, "Duplicates happen constantly in real data, that's exactly why this module exists."),
        opt("A name match always means it's the same customer", false, "A name alone isn't a reliable unique identifier, this is precisely why you check other fields (email, ID) before deduplicating.") ] },
    { id: "m4q3", type: "application", difficulty: "medium",
      objective: "Handle inconsistent categorical labels",
      text: "A 'status' column has values \"Returned\", \"returned\", and \"RETURNED\" all meaning the same thing. What should you do before analyzing it?",
      opts: [ opt("Normalize casing (e.g. lowercase everything) so they're treated as one category", true),
        opt("Leave them as three separate categories, since the data has three spellings", false, "Treating them as three separate categories will silently split what should be one count into three, undercounting the real total every time."),
        opt("Delete all rows with lowercase 'returned'", false, "Deleting valid data because of a casing difference destroys real information, normalizing the text is the right fix.") ] },
    { id: "m4q4", type: "scenario", difficulty: "hard",
      objective: "Triage a real outlier",
      text: "One row shows a single order of 50,000 units when every other order is under 200. What's the right next step?",
      opts: [ opt("Investigate it before deciding: check if it's a real bulk order, a data-entry error, or a unit mismatch, don't just delete it", true),
        opt("Delete it immediately, it's clearly wrong", false, "It might be a real bulk order, deleting real data without checking throws away potentially important signal."),
        opt("Leave it exactly as-is without checking", false, "An unchecked outlier this extreme can badly skew averages and totals, it needs at least a quick investigation before you trust any summary statistic built on it.") ] },
    { id: "m4q5", type: "recall", difficulty: "easy",
      objective: "Explain the value of a cleaning checklist",
      text: "Why build a reusable cleaning checklist instead of writing a one-off script for each new messy file?",
      opts: [ opt("The same handful of problems, missing values, duplicates, inconsistent types, recur across almost every real dataset", true),
        opt("A checklist is required by pandas before you can clean any data", false, "Nothing about pandas requires a checklist, it's a practical habit, not a technical requirement."),
        opt("One-off scripts always run faster than a checklist approach", false, "Speed isn't the tradeoff here, a checklist is about not re-deriving the same diagnosis from scratch every time.") ] },
    { id: "m4q6", type: "application", difficulty: "medium",
      objective: "Handle a missing-value decision",
      text: "A column has 3% of its values missing. What should inform whether you drop those rows, fill them, or flag them?",
      opts: [ opt("Whether the missingness is random or systematic, and what the downstream analysis actually needs", true),
        opt("Always drop rows with any missing value, no exceptions", false, "Always dropping can quietly bias your analysis if the missing values aren't random, e.g. if higher-value orders are more likely to have a missing field."),
        opt("Always fill missing values with zero", false, "Filling with zero can badly distort averages and totals if zero isn't a meaningful value for that column.") ] },
  ] },

  5: { title: "Exploratory Data Analysis & Statistics", questions: [
    { id: "m5q1", type: "recall", difficulty: "easy",
      objective: "Choose median over mean appropriately",
      text: "A dataset of household incomes has a few extremely high values. Which statistic better represents the 'typical' household?",
      opts: [ opt("The median, since it isn't pulled by extreme outliers the way the mean is", true),
        opt("The mean, it's always the more accurate measure", false, "The mean is sensitive to extreme values, a few very high incomes can pull it well above what's actually typical."),
        opt("The mode, since income is always evenly distributed", false, "Income is rarely evenly distributed, and mode (most frequent value) doesn't summarize a spread of unique numeric values well.") ] },
    { id: "m5q2", type: "scenario", difficulty: "medium",
      objective: "Distinguish correlation from causation",
      text: "Ice cream sales and drowning incidents both rise in summer, and are correlated. Does ice cream cause drowning?",
      opts: [ opt("No, both are driven by a third factor, warm weather, correlation alone doesn't establish causation", true),
        opt("Yes, correlation this strong always implies causation", false, "Correlation never guarantees causation on its own, a shared underlying cause is a very common alternative explanation."),
        opt("It's impossible to say without more ice cream data", false, "More ice cream data wouldn't resolve this, the issue is a missing confounding variable (season/temperature), not sample size.") ] },
    { id: "m5q3", type: "application", difficulty: "medium",
      objective: "Recognize when a difference might be noise",
      text: "Version A of a webpage converts at 5.2%, version B at 5.4%, from 40 visitors each. Should you conclude B is better?",
      opts: [ opt("Not yet, a sample this small makes that gap plausible as random noise, not a real effect", true),
        opt("Yes, any higher number means B is definitively better", false, "With only 40 visitors per version, a small percentage-point gap is easily explained by chance, not a proven real difference."),
        opt("The comparison is meaningless unless both versions convert at exactly the same rate", false, "The comparison isn't meaningless, it's just inconclusive at this sample size, a hypothesis test could clarify whether the gap is likely real.") ] },
    { id: "m5q4", type: "recall", difficulty: "easy",
      objective: "State what Anscombe's quartet demonstrates",
      text: "Anscombe's quartet shows four datasets with nearly identical mean, variance, and correlation. What's the lesson?",
      opts: [ opt("Identical summary statistics can hide completely different underlying shapes, always look at the data, not just its summary numbers", true),
        opt("Summary statistics are always sufficient on their own", false, "That's the opposite of the lesson, the quartet exists specifically to show summary statistics can mislead."),
        opt("Datasets with the same statistics are always identical", false, "The entire point of the quartet is that they're visibly, dramatically different despite matching statistics.") ] },
    { id: "m5q5", type: "recall", difficulty: "easy",
      objective: "Define standard deviation intuitively",
      text: "What does a small standard deviation tell you about a dataset?",
      opts: [ opt("Values are clustered close to the mean, not spread out", true),
        opt("The dataset has very few rows", false, "Standard deviation measures spread of values, not the count of rows in the dataset."),
        opt("The mean is definitely wrong", false, "Standard deviation says nothing about whether the mean is 'wrong', it describes how spread out the values are around it.") ] },
    { id: "m5q6", type: "application", difficulty: "medium",
      objective: "Apply percentiles to a business question",
      text: "You want to know the response time that 95% of support tickets beat. What should you compute?",
      opts: [ opt("The 95th percentile of response times", true),
        opt("The average response time", false, "The average alone doesn't tell you a threshold that 95% of cases fall under, especially if the distribution has a long tail."),
        opt("The mode of response times", false, "The most frequent single value doesn't answer a percentile-based threshold question.") ] },
  ] },

  7: { title: "Data Visualization & Storytelling", questions: [
    { id: "m6q1", type: "application", difficulty: "medium",
      objective: "Choose the right chart type",
      text: "You want to show how monthly revenue changed over the last two years. Which chart fits best?",
      opts: [ opt("A line chart, it's built for showing a trend over time", true),
        opt("A pie chart, it's built for showing a whole broken into parts", false, "A pie chart shows proportions of a single whole at one point in time, not a trend across many time periods."),
        opt("A single bar with no categories", false, "A single unlabeled bar can't show change over multiple time periods at all.") ] },
    { id: "m6q2", type: "recall", difficulty: "easy",
      objective: "Explain the common pie-chart problem",
      text: "Why do experienced analysts avoid pie charts for more than 2-3 categories?",
      opts: [ opt("Human eyes are bad at comparing the area of similarly-sized wedges, a bar chart makes the same comparison easier", true),
        opt("Pie charts can only display exactly 2 categories, ever", false, "Pie charts can technically render many slices, the problem is readability, not a hard technical limit."),
        opt("Pie charts are only for financial data", false, "There's no such restriction, the issue is purely about how easy the chart is to read accurately.") ] },
    { id: "m6q3", type: "scenario", difficulty: "hard",
      objective: "Spot a misleading chart",
      text: "A bar chart's y-axis starts at 90 instead of 0, making a change from 92 to 95 look like a huge jump. What's the problem?",
      opts: [ opt("A truncated axis exaggerates the visual size of a small real difference, misleading the reader", true),
        opt("Nothing, starting the axis anywhere is always fine", false, "A truncated axis is one of the most common ways charts mislead, it distorts the visual magnitude of a real but small change."),
        opt("The chart is wrong because bar charts can't use a y-axis at all", false, "Bar charts absolutely use a y-axis, the specific problem here is where that axis starts, not whether it exists.") ] },
    { id: "m6q4", type: "recall", difficulty: "easy",
      objective: "Explain the point of a one-page summary visual",
      text: "What is a one-page 'so what' visual supposed to do for a non-technical stakeholder?",
      opts: [ opt("Let them grasp the key finding and its implication in seconds, without needing to interpret raw data themselves", true),
        opt("Show every data point in the dataset, for completeness", false, "That's the opposite goal, a good summary visual deliberately leaves out detail that would slow the reader down."),
        opt("Replace the need for any written explanation at all", false, "A good visual supports a written recommendation, it doesn't eliminate the need to state the recommendation in words.") ] },
    { id: "m6q5", type: "application", difficulty: "medium",
      objective: "Choose a chart for distribution",
      text: "You want to show the distribution of order values (are they clustered low, spread out, skewed?). What chart fits best?",
      opts: [ opt("A histogram", true),
        opt("A line chart", false, "Line charts are built for trends over a sequence (usually time), not for showing the shape of a single distribution."),
        opt("A single number, the average order value", false, "A single average hides the shape entirely, that's exactly what a histogram reveals instead.") ] },
    { id: "m6q6", type: "recall", difficulty: "easy",
      objective: "Recognize a dual-axis trick",
      text: "A chart overlays two lines with different y-axes (one on the left, one on the right) to imply they move together. Why is this a red flag?",
      opts: [ opt("The two axes' scales can be chosen to make unrelated trends visually appear correlated", true),
        opt("Dual-axis charts are always technically invalid and can't be rendered", false, "They render fine technically, the concern is about how easily they can be used to mislead, not a rendering limitation."),
        opt("It's only a problem if both lines are the same color", false, "The color of the lines isn't the issue, the manipulable relationship between the two independent scales is.") ] },
  ] },

  6: { title: "SQL for Analysts", questions: [
    { id: "m7q1", type: "application", difficulty: "medium",
      objective: "Write a basic aggregation query",
      text: "You want total revenue per region from an `orders` table. Which query is correct?",
      opts: [ opt("SELECT region, SUM(revenue) FROM orders GROUP BY region", true),
        opt("SELECT region, revenue FROM orders ORDER BY region", false, "This sorts individual rows, it doesn't sum revenue per region at all."),
        opt("SELECT SUM(revenue) FROM orders WHERE region = ALL", false, "This isn't valid SQL for a per-group total, GROUP BY is what produces one summed row per region.") ] },
    { id: "m7q2", type: "recall", difficulty: "easy",
      objective: "Explain what JOIN does",
      text: "What does a JOIN between two tables fundamentally accomplish?",
      opts: [ opt("Combines rows from two tables based on a related column between them", true),
        opt("Deletes rows that exist in only one of the two tables", false, "Some join types (like INNER JOIN) do exclude non-matching rows, but the core purpose of a join is combining matched data, not deleting."),
        opt("Sorts a single table by multiple columns", false, "Sorting is what ORDER BY does, a JOIN's job is combining tables, not sorting one.") ] },
    { id: "m7q3", type: "scenario", difficulty: "hard",
      objective: "Translate a business question into SQL",
      text: "Business question: 'which customers haven't ordered in the last 90 days?' What SQL concept is central to answering this?",
      opts: [ opt("Filtering with WHERE on a date comparison, likely combined with a JOIN or subquery against the most recent order per customer", true),
        opt("A single SELECT * with no filtering at all", false, "Selecting everything with no filter or date logic doesn't isolate customers who stopped ordering, it just returns all data."),
        opt("DELETE FROM customers WHERE inactive = true", false, "This is a destructive write operation, and the business question is about identifying customers for outreach, not deleting them.") ] },
    { id: "m7q4", type: "recall", difficulty: "medium",
      objective: "Explain a window function's purpose",
      text: "What can a window function do that a plain GROUP BY can't?",
      opts: [ opt("Compute a running total or rank across rows while still returning every individual row, not just one row per group", true),
        opt("Filter rows before they're selected", false, "That's WHERE's job, window functions compute values across a set of rows, they don't filter which rows appear."),
        opt("Join two tables together", false, "Joining tables is JOIN's job, window functions operate on rows that are already selected/joined.") ] },
    { id: "m7q5", type: "debugging", difficulty: "medium",
      objective: "Diagnose a query returning too many rows",
      text: "A query joins orders to customers and returns way more rows than there are orders. What's the likely cause?",
      opts: [ opt("The join key isn't unique on the customers side, so each order matches multiple customer rows", true),
        opt("SQL always returns extra rows on a join by design", false, "Extra rows aren't a default behavior of joins, they specifically indicate a non-unique join key somewhere."),
        opt("The WHERE clause is missing a semicolon", false, "A missing semicolon is a syntax issue that would usually cause an error, not silently multiply the row count.") ] },
    { id: "m7q6", type: "recall", difficulty: "easy",
      objective: "Distinguish WHERE from HAVING",
      text: "Why can't you filter on an aggregated value (like SUM(revenue) > 1000) using WHERE?",
      opts: [ opt("WHERE filters rows before aggregation happens; HAVING filters groups after aggregation, which is what's needed here", true),
        opt("WHERE can only be used with SELECT *", false, "WHERE works with any column selection, that's not the actual restriction here."),
        opt("Aggregated values can never be filtered in SQL at all", false, "They can absolutely be filtered, just with HAVING instead of WHERE, since the aggregation happens first.") ] },
  ] },

  8: { title: "Dashboards & Business Communication", questions: [
    { id: "m8q1", type: "recall", difficulty: "easy",
      objective: "Explain what makes a dashboard 'good'",
      text: "What's the main test of whether a dashboard is well designed?",
      opts: [ opt("A non-technical stakeholder can understand the key point in under a minute", true),
        opt("It includes every metric that could possibly be computed from the data", false, "Cramming in every possible metric usually makes a dashboard harder to read, not more useful."),
        opt("It uses as many different chart types as possible", false, "Variety isn't the goal, clarity for the reader is, sometimes the same chart type repeated is the clearer choice.") ] },
    { id: "m8q2", type: "application", difficulty: "medium",
      objective: "Structure an executive summary",
      text: "What should the FIRST sentence of a written analysis memo lead with?",
      opts: [ opt("The recommendation or key finding, not the method used to get there", true),
        opt("A full description of every step of the analysis process", false, "Leading with methodology buries the actual finding, which is what a busy stakeholder needs first."),
        opt("An apology for how messy the raw data was", false, "This doesn't help the reader make a decision, and isn't the point of the summary at all.") ] },
    { id: "m8q3", type: "recall", difficulty: "easy",
      objective: "Explain metric selection for a dashboard",
      text: "Why is choosing which metrics NOT to include on a dashboard just as important as choosing which to include?",
      opts: [ opt("Too many metrics competing for attention makes it harder to see which ones actually matter for the decision at hand", true),
        opt("Dashboards have a hard technical limit of 3 metrics", false, "There's no such fixed technical limit, the reasoning is about reader attention and clarity, not a system constraint."),
        opt("Extra metrics always slow down the software rendering the dashboard", false, "Performance isn't the concern being tested here, comprehension is.") ] },
    { id: "m8q4", type: "scenario", difficulty: "medium",
      objective: "Handle a 'so what' follow-up question",
      text: "After presenting a finding, a stakeholder asks 'so what should we do about it?' What's the wrong way to respond?",
      opts: [ opt("Restating the numbers again without offering any recommendation", true),
        opt("Offering a specific, actionable recommendation tied to the finding", false, "This is exactly the right response, it's what turns an observation into something the business can act on."),
        opt("Acknowledging uncertainty while still proposing the most defensible next step", false, "This is a reasonable, honest way to answer, not the wrong one, being upfront about uncertainty while still recommending a next step is good practice.") ] },
    { id: "m8q5", type: "recall", difficulty: "easy",
      objective: "Explain why 'tool-agnostic' dashboard skill matters",
      text: "Why does this course teach dashboard-building in a tool-agnostic way instead of just one specific BI tool?",
      opts: [ opt("The underlying skill (choosing metrics, layout, and what to leave out) transfers across any tool, a specific tool's UI is easy to pick up afterward", true),
        opt("Because no company actually uses BI tools like Tableau or Power BI", false, "Many companies do use dedicated BI tools, the point is the transferable judgment, not that those tools are irrelevant."),
        opt("Because dashboards can only be built in Excel", false, "Dashboards can be built in many tools, the tool-agnostic framing is about transferable skill, not a restriction to one tool.") ] },
    { id: "m8q6", type: "application", difficulty: "medium",
      objective: "Choose what a dashboard should visually emphasize",
      text: "A dashboard is meant to flag when a KPI drops below target. What should visually stand out most?",
      opts: [ opt("The current status relative to target, e.g. a clear color or marker showing under/over target", true),
        opt("The exact formula used to calculate the KPI", false, "The formula is implementation detail, a reader checking a dashboard needs the status at a glance, not the calculation method."),
        opt("A full historical log of every past value, undifferentiated", false, "An undifferentiated log buries the one thing that matters, whether the KPI is currently off target, in noise.") ] },
  ] },
};

const MIXED_QUIZZES = [
  { id: "mix_1_3", title: "Mixed Quiz: Modules 1–3", modules: [1, 2, 3], perModule: 3 },
  { id: "mix_4_5", title: "Mixed Quiz: Modules 4–5", modules: [4, 5], perModule: 4 },
  { id: "mix_6_8", title: "Mixed Quiz: Modules 6–8", modules: [6, 7, 8], perModule: 3 },
];

function shuffle(arr) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function masteryBand(pct) {
  if (pct >= 90) return { label: "Mastered", cls: "mastered" };
  if (pct >= 80) return { label: "Strong", cls: "strong" };
  if (pct >= 70) return { label: "Needs review", cls: "review" };
  return { label: "Revisit module", cls: "revisit" };
}

global.QuizData = { POOLS, MIXED_QUIZZES, shuffle, masteryBand };
})(window);
