/* Checkpoint questions, five per module.

   These are written to test judgement rather than recall. A question whose
   answer is a definition can be passed by skimming; a question that puts
   you in front of a plausible-looking diff and asks what you do next
   cannot. Every wrong option carries an explanation, because the wrong
   answers are where the teaching is.

   Option order is shuffled at render time (module-kit.js), so position
   carries no information. */
(function (global) {
  function q(id, text, opts) { return { id: id, text: text, opts: opts }; }
  function o(t, correct, why) { return { t: t, correct: !!correct, why: why }; }

  const MODULE_QUIZZES = {
    1: [
      q("m1a", "Priya's ticket says patients are showing up to a locked door. What is the defect?",
        [o("The page states the clinic is closed on Saturday when it is open.", true, "Right. She reported a consequence; you named the cause."),
         o("Patients are not reading carefully enough.", false, "Blaming the user is not a diagnosis. The page is wrong."),
         o("The hours section needs a redesign.", false, "That is a solution to a different problem, and nobody asked for it.")]),
      q("m1b", "The ticket is about Saturday's hours. Your change also renames a CSS class and converts the list to a table. What happens in review?",
        [o("It gets sent back \u2014 the reviewer now has three unrelated changes to evaluate instead of one.", true, "One reason per change. This is the habit the whole course rests on."),
         o("It gets praised for initiative.", false, "Unrequested restructuring is the most common reason AI-assisted changes are rejected."),
         o("Nothing, as long as the page still looks right.", false, "Reviewability is not about whether it looks right. It is about whether anyone can check it.")]),
      q("m1c", "In <code>&lt;dd class=\"today\"&gt;Closed&lt;/dd&gt;</code>, which part does a patient read on screen?",
        [o("Closed \u2014 the content between the tags.", true, "Tags say what kind of thing it is; the content is what humans see."),
         o("class=\"today\" \u2014 the attribute.", false, "Attributes are metadata for CSS and JavaScript. They do not render."),
         o("dd \u2014 the tag name.", false, "The tag name describes the element's role, it is not displayed.")]),
      q("m1d", "The agent replies \u201cI have updated the Saturday hours.\u201d What is that worth as evidence?",
        [o("Nothing on its own. You open the page and look at it.", true, "The Run step exists precisely because confident summaries are not proof."),
         o("It is sufficient \u2014 the agent can see the file.", false, "Agents routinely report changes they did not make, or made in the wrong place."),
         o("It is sufficient if it also shows the diff.", false, "A diff is much better, but you still run it. Diffs can be right and still wrong in context.")]),
      q("m1e", "Which commit message will help someone six months from now?",
        [o("Correct Saturday hours to 09:00-13:00", true, "Imperative verb, the actual change, searchable words, short."),
         o("Modified dd element inside dl.hours", false, "That describes the diff, which the reader can already see. It hides the reason."),
         o("fix", false, "There will be forty of these and none of them will help anyone.")]),
    ],
    2: [
      q("m2a", "Dan writes \u201cthe client says booking is confusing, make it better.\u201d What is missing?",
        [o("Everything checkable \u2014 there is a symptom and a verdict, but no requirement.", true, "\u201cConfusing\u201d cannot be built or verified. Facts can."),
         o("Nothing; that is enough to start coding.", false, "It is enough to start asking. It is not enough to start building."),
         o("A visual mockup from the client.", false, "Priya is not a designer. Asking her to design is outsourcing your job.")]),
      q("m2b", "Why does a user story need the \u201cso that\u2026\u201d clause?",
        [o("It lets you rule solutions out \u2014 you can ask whether a proposed change actually achieves the outcome.", true, "The reason clause is a test for solutions, which is why dropping it is expensive."),
         o("It is a formatting convention reviewers expect.", false, "It earns its place functionally, not stylistically."),
         o("It tells the agent which framework to use.", false, "It has nothing to do with implementation.")]),
      q("m2c", "Which of these is an acceptance criterion?",
        [o("Given name, email and date are filled in, when I press Request appointment, then the form is replaced by \u201cRequest received \u2014 we will call you within one working day\u201d.", true, "A stranger could run that and reach a verdict without asking you what you meant."),
         o("The booking form should be intuitive and work properly.", false, "Nobody can check \u201cintuitive\u201d. This is a wish."),
         o("Refactor the booking form for better UX.", false, "That is a task, and a vague one. A criterion describes an observable outcome.")]),
      q("m2d", "The clinic is closed on Sundays. A patient requests a Sunday appointment. Why will an agent probably miss this edge case?",
        [o("It is a domain rule. The agent knows about empty strings and nulls; it has never met Priya.", true, "Famous edge cases are free. Edge cases that come from the business are yours to supply."),
         o("Agents cannot handle dates.", false, "Date handling is something they do well. Knowing the clinic's schedule is not."),
         o("It is not really an edge case.", false, "Accepting a booking you cannot honour is a promise you will break. That is a defect.")]),
      q("m2e", "The agent\u2019s plan addresses the confirmation and also rewrites auth.js, restyles the form, and adds a validation library. What do you do?",
        [o("Reject the plan. The extra files and the swapped validation are out of scope even if the confirmation is in it.", true, "A plan is free to change. A 400-line diff is not. Review at the cheapest point."),
         o("Approve it \u2014 more work for the same ticket is better value.", false, "Unrequested work is unreviewed work. Auth.js on a booking ticket is how incidents start."),
         o("Approve the plan and review the diff carefully afterwards.", false, "The diff is the expensive place to find scope creep. The plan is the cheap one.")]),
    ],
    3: [
      q("m3a", "Why choose <code>&lt;nav&gt;</code> over <code>&lt;div class=\"nav\"&gt;</code> when both can look identical?",
        [o("The element carries meaning that assistive technology and other tools can act on; the class carries none.", true, "Same pixels, different information. Semantics are machine-readable meaning."),
         o("Divs are deprecated.", false, "Divs are fine when there is genuinely no meaning to express."),
         o("It renders faster.", false, "Performance is not the reason.")]),
      q("m3b", "An agent gives you <code>&lt;div onclick=\"submitForm()\"&gt;Request&lt;/div&gt;</code>. What is wrong?",
        [o("A div is not a control \u2014 it is not focusable, not keyboard-operable, and not announced as a button.", true, "It looks like a button to a sighted mouse user and to nobody else. Use <button>."),
         o("onclick is invalid HTML.", false, "It is valid. The element is still the wrong one."),
         o("Nothing, if CSS makes it look like a button.", false, "Looking like a button is the least important property of a button.")]),
      q("m3c", "What does wrapping an input in a <code>&lt;label&gt;</code> (or linking with <code>for</code>) actually buy you?",
        [o("The field is announced with its name, and clicking the text focuses the input.", true, "Two concrete wins. Placeholder text gives you neither, and vanishes on typing."),
         o("It validates the input automatically.", false, "Labels do not validate. That is <code>required</code>, <code>type</code>, and your own checks."),
         o("It is purely a styling hook.", false, "That would be a class.")]),
      q("m3d", "Why should a page have exactly one <code>&lt;h1&gt;</code> and headings that descend in order?",
        [o("Headings are the document's outline, and people navigate by that outline rather than reading top to bottom.", true, "Skipping from h2 to h4 because it looked better is choosing font size over structure."),
         o("Search engines penalise extra h1 tags.", false, "SEO folklore is not the reason to get this right."),
         o("Browsers refuse to render two h1 elements.", false, "They render fine. The structure is what breaks.")]),
      q("m3e", "You asked for a contact form. The agent returns a form plus a newsletter signup, a cookie banner, and a map embed. What do you do?",
        [o("Reject the extras and restate the scope. Unrequested features are unreviewed features.", true, "Every line you keep, you own. You cannot defend what you did not ask for."),
         o("Keep it all \u2014 more functionality is better value.", false, "You now own a cookie banner with legal implications you never evaluated."),
         o("Keep it and open a ticket to review it later.", false, "\u201cReview later\u201d on code you already shipped is how defects become permanent.")]),
    ],
    4: [
      q("m4a", "An element has <code>width: 300px; padding: 20px; border: 2px solid</code>. Under the default box model, how wide is it on screen?",
        [o("344px \u2014 padding and border are added outside the declared width.", true, "300 + 20 + 20 + 2 + 2. This arithmetic is behind a large share of \u201cwhy is it overflowing\u201d."),
         o("300px \u2014 width means total rendered width.", false, "Only with <code>box-sizing: border-box</code>, which is not the default."),
         o("340px \u2014 borders are not counted.", false, "Borders count too.")]),
      q("m4b", "What is the actual difference between margin and padding?",
        [o("Padding is space inside the border, part of the element; margin is space outside it, between elements.", true, "Background colour reaches into padding and not into margin, which is the quickest way to tell them apart on screen."),
         o("Padding is vertical and margin is horizontal.", false, "Both work in all four directions."),
         o("They are interchangeable.", false, "They collapse differently, and backgrounds treat them differently.")]),
      q("m4c", "A card layout looks correct on your laptop and unreadable on a phone. What is the most likely cause?",
        [o("Fixed pixel widths that cannot shrink below the viewport.", true, "A 900px container on a 390px screen has nowhere to go. This is ticket NL-004 in one sentence."),
         o("The phone does not support flexbox.", false, "Flexbox has near-universal support."),
         o("Images are too large in file size.", false, "That is a speed problem, not a layout problem.")]),
      q("m4d", "The agent adds <code>!important</code> to four rules to make your fix take effect. Accept?",
        [o("No \u2014 it is silencing a specificity conflict rather than resolving it, and the next change will need five.", true, "It works today and makes every future change harder. Ask why the rule was losing."),
         o("Yes \u2014 it is the standard way to guarantee a style applies.", false, "It is the standard way to lose control of a stylesheet."),
         o("Yes, if the tests pass.", false, "There is no test that catches an unmaintainable stylesheet.")]),
      q("m4e", "You are asked for one breakpoint. How do you choose the number?",
        [o("Shrink the window until the layout actually breaks, and put the breakpoint there.", true, "Breakpoints come from your content, not from a list of device widths."),
         o("Use 768px because that is the standard.", false, "There is no standard. Devices come in every width."),
         o("Add breakpoints at every common device width to be safe.", false, "Six breakpoints you cannot justify is six times the maintenance.")]),
    ],
    5: [
      q("m5a", "Why does this course make you write the filtering logic by hand before letting an agent near it?",
        [o("You cannot review a diff in a shape you have never produced yourself.", true, "This is the whole argument for Stage 2. Reading is harder than writing, and you review far more than you write."),
         o("Because agents write JavaScript badly.", false, "They write it well. That is exactly why you need to be able to check it."),
         o("To make the course longer.", false, "Stage 2 is the part that makes Stage 3 possible.")]),
      q("m5b", "<code>items.reduce((total, item) =&gt; total + item.price, 0)</code> was written to total a cart. What is the bug?",
        [o("It ignores quantity \u2014 two units of a \u00a33 item total \u00a33.", true, "Plausible, idiomatic, well-formatted, and financially wrong. This is the signature AI defect."),
         o("reduce needs three arguments.", false, "The call is correct. The formula is not."),
         o("It should be a for loop.", false, "reduce is fine here. The arithmetic is the problem.")]),
      q("m5c", "A function returns nothing but changes a variable outside itself. Why prefer returning a value?",
        [o("A function that takes input and returns output can be tested in isolation; one that reaches outside cannot.", true, "Testability is the practical reason, and it is why Module 9 depends on this module."),
         o("Return values are faster.", false, "Speed is not the issue."),
         o("Because global variables do not exist in JavaScript.", false, "They very much do, which is the problem.")]),
      q("m5d", "What does <code>if (patient.name)</code> treat as false, that might surprise you?",
        [o("An empty string \u2014 and also 0, so the same pattern on a numeric field is a real bug.", true, "Falsy values are a top source of quiet defects. Be explicit about what you are testing for."),
         o("Only null and undefined.", false, "Empty string, 0, and NaN are also falsy."),
         o("Nothing \u2014 any property that exists is true.", false, "Existence and truthiness are different things.")]),
      q("m5e", "You need to know whether a filter works. What is the strongest move?",
        [o("Call it with a list you constructed, including an empty list, and check the returned value against what you expected.", true, "Deciding the expected answer in advance is what makes it a check rather than a look."),
         o("Read it carefully and reason about it.", false, "Necessary, and not sufficient. Reading is how bugs survive review."),
         o("Ask the agent whether it is correct.", false, "It will say yes. It said yes about the cart total too.")]),
    ],
    6: [
      q("m6a", "What is the DOM?",
        [o("The live tree of objects the browser built from your HTML, which JavaScript can read and change.", true, "The file is the starting point; the DOM is the running thing. Changing the DOM does not change the file."),
         o("Another name for the HTML file on disk.", false, "The file is static. The DOM is live, and can diverge from it immediately."),
         o("A CSS feature for positioning.", false, "Unrelated.")]),
      q("m6b", "Why is <code>element.textContent = userInput</code> safer than <code>element.innerHTML = userInput</code>?",
        [o("textContent inserts text; innerHTML parses it, so markup and scripts in the input become part of the page.", true, "This is cross-site scripting in one line, and agents reach for innerHTML by default."),
         o("innerHTML is deprecated.", false, "It is current and legitimate \u2014 for markup you control, not for user input."),
         o("textContent is faster.", false, "Marginally, and irrelevant next to the security difference.")]),
      q("m6c", "Loading appointments from a file is asynchronous. What does that mean for your code?",
        [o("The data is not there on the line after you request it, so anything depending on it has to wait.", true, "Reading a length before the response arrives is the classic \u201cwhy is it undefined\u201d moment."),
         o("The request blocks the page until it finishes.", false, "That is the behaviour asynchronous code exists to avoid."),
         o("It only matters for large files.", false, "It matters at every size. Timing is not about volume.")]),
      q("m6d", "The agent's data-loading code works perfectly in your test. Which case has it almost certainly not handled?",
        [o("The request failing, or returning an empty list \u2014 the states with nothing to render.", true, "Empty and error are the two states that only appear in production, and the two the happy path never exercises."),
         o("More than ten records.", false, "Volume rarely breaks this kind of code."),
         o("Being called twice.", false, "Worth checking, but far less common than an unhandled empty or failed response.")]),
      q("m6e", "A single form submit creates four booking requests. What is the likeliest cause?",
        [o("Nothing visible happened after the first press, so the patient pressed it again.", true, "A missing confirmation is not a cosmetic issue \u2014 it produces duplicate data. This is why NL-002's confirmation message mattered."),
         o("The server is duplicating records.", false, "Possible, but the user-side explanation is far more common and much cheaper to check."),
         o("A browser bug.", false, "Almost never the answer.")]),
    ],
    7: [
      q("m7a", "Which request will produce a diff you can actually review?",
        [o("\u201cIn dashboard.js only, add countOpen(appointments) returning the number of records whose status is \u2018open\u2019. Do not change existing functions. Show the diff.\u201d", true, "One named function, one named file, an explicit do-not-touch, and a diff. Reviewable in under a minute."),
         o("\u201cBuild me a dashboard for the clinic with the three key metrics.\u201d", false, "You will get several files and a design you did not choose. Nothing here is checkable line by line."),
         o("\u201cImprove the dashboard using best practices.\u201d", false, "There is no acceptance criterion in this sentence, so there is no way to be wrong \u2014 or right.")]),
      q("m7b", "The agent says \u201cAll tests pass and the feature works correctly.\u201d What is that worth?",
        [o("Nothing until you have run the tests yourself and read what they assert.", true, "A test asserting <code>true === true</code> passes. \u201cTests pass\u201d and \u201cthe code is right\u201d are unrelated claims."),
         o("It is reliable \u2014 it can execute the tests.", false, "It can also misreport, test the wrong thing, or write a test that cannot fail."),
         o("It is reliable if it lists the test names.", false, "Names are not assertions. Read the body.")]),
      q("m7c", "Why does this module make you paste the agent's code in and run our hidden tests against it?",
        [o("Because grading the artifact is honest and grading your claim about it is not.", true, "A checkbox saying \u201cI reviewed it\u201d proves nothing. Code that passes an independent test proves something."),
         o("To check you used a specific model.", false, "The course is vendor-neutral by design."),
         o("To store your code on our servers.", false, "It is graded in your browser.")]),
      q("m7d", "The agent's first attempt fails your tests. What is the professional response?",
        [o("Tell it exactly which case failed and what you expected, then review the next diff just as carefully.", true, "Iteration with specific evidence is the loop working. Vague \u201cthat is wrong, fix it\u201d gets you a random walk."),
         o("Start over with a longer, more detailed prompt.", false, "Sometimes right, but usually you are discarding a nearly-correct diff over one case."),
         o("Fix it yourself and say nothing.", false, "Fine occasionally, but you lose the chance to correct the context it is working from.")]),
      q("m7e", "You accept a hunk you do not fully understand because the tests are green. What have you actually done?",
        [o("Taken ownership of code you cannot explain, defend, or debug at 2am.", true, "If you cannot explain it, you cannot maintain it, and your name is on the commit."),
         o("Nothing risky \u2014 the tests are the authority.", false, "Tests check the cases you thought of. They say nothing about the ones you did not."),
         o("Saved time appropriately.", false, "You borrowed time from the person who has to fix it later, who is usually you.")]),
    ],
    8: [
      q("m8a", "You review an AI pull request and reject all eleven hunks to be safe. What is the problem?",
        [o("Indiscriminate rejection carries no information, so it is as useless as indiscriminate approval.", true, "A review's value is in discrimination. \u201cAll bad\u201d and \u201call fine\u201d are both refusals to think."),
         o("Nothing \u2014 caution is always correct.", false, "Caution that cannot distinguish good from bad is not caution, it is noise."),
         o("You should reject at most half.", false, "There is no quota. Each hunk gets judged on evidence.")]),
      q("m8b", "Which defect class is hardest to catch by reading, and why?",
        [o("Logic that is plausible and wrong \u2014 it reads as correct because it looks like the shape you expected.", true, "Crashes announce themselves. A total that silently omits quantity does not. This is why proving the fix is phase two."),
         o("Syntax errors \u2014 they are subtle.", false, "They are the easiest class; the code will not even run."),
         o("Bad indentation.", false, "Cosmetic, and a formatter fixes it.")]),
      q("m8c", "A hunk adds <code>console.log('patient', patient.email)</code> while debugging. Merge it?",
        [o("No. Personal data in logs is a real disclosure, and logs get copied, shipped, and read by people who should not see it.", true, "\u201cIt is only a log\u201d and \u201conly on staging\u201d are both how leaks happen."),
         o("Yes, logs are not part of the product.", false, "Logs are absolutely part of the product's security surface."),
         o("Yes, if it is removed before the next release.", false, "It will not be. Remove it now.")]),
      q("m8d", "The agent leaves <code>// TEMP: skipping expiry check so the demo works</code>. What is this?",
        [o("A product defect, not a comment issue \u2014 the disabled check is the thing that shipped.", true, "The comment is honest. The code is broken. Delete the shortcut, not the comment."),
         o("A helpful note for later.", false, "\u201cLater\u201d has no owner and no date."),
         o("Acceptable if you open a follow-up ticket.", false, "For a security check, no. Finish it or cut the feature.")]),
      q("m8e", "You spot a bug in AI-generated code. Why does the course make you also write the fix and pass hidden tests?",
        [o("Because identifying a defect and being able to prove you resolved it are different skills, and only the second one ships.", true, "Plenty of people can point at code and feel uneasy. Far fewer can produce a version that provably works."),
         o("To pad out the exercise.", false, "It is the half that makes the first half real."),
         o("Because the fix is always obvious once you see the bug.", false, "It frequently is not, which is precisely why it is graded.")]),
    ],
    9: [
      q("m9a", "Two patients say the booking form does nothing. It works when Priya tries it. What does that tell you?",
        [o("The behaviour depends on something that differs between them \u2014 input, browser, timing, or data.", true, "\u201cWorks on my machine\u201d is a clue about your machine, not a verdict on the bug."),
         o("The patients are mistaken.", false, "Two independent reports of the same symptom is evidence, not confusion."),
         o("It is intermittent and cannot be investigated.", false, "\u201cIntermittent\u201d usually means \u201cthe condition has not been found yet\u201d.")]),
      q("m9b", "What must a test be able to do before it is worth anything?",
        [o("Fail. If no possible defect makes it red, it is decoration.", true, "This is the whole idea: plant the bug, watch it go red, then fix it and watch it go green."),
         o("Run quickly.", false, "Nice, and worthless if it cannot fail."),
         o("Cover every line.", false, "Full coverage with weak assertions is a well-documented way to feel safe and not be safe.")]),
      q("m9c", "You have a bug report. What is the first thing to produce?",
        [o("A reliable reproduction \u2014 the exact steps and data that make it happen every time.", true, "Without it you cannot tell a fix from a coincidence, and you cannot write the failing test."),
         o("A fix.", false, "A fix for a bug you cannot reproduce is a guess you cannot verify."),
         o("A message to the client explaining the cause.", false, "You do not know the cause yet.")]),
      q("m9d", "Your test suite is green after a change. What does that establish?",
        [o("The cases you thought to write still behave as you expected. Nothing about the cases you did not write.", true, "Green is the absence of known failure, not the presence of correctness."),
         o("The code is correct.", false, "No test suite establishes that."),
         o("The change is safe to deploy.", false, "It is one input to that decision.")]),
      q("m9e", "The agent \u201cfixes\u201d a flaky test by adding a five-second wait. Accept?",
        [o("No \u2014 it hides a race instead of resolving it, and the failure will come back slower and less predictably.", true, "Wait for the condition, never for the clock."),
         o("Yes, waits are standard practice.", false, "They are a standard smell."),
         o("Yes, but make it ten seconds to be safe.", false, "Longer waits hide the race more thoroughly. That is worse.")]),
    ],
    10: [
      q("m10a", "What belongs in a single commit?",
        [o("One reason for change, across whatever related files that reason touches.", true, "\u201cOne reason\u201d, not \u201cone file\u201d. A rename that touches three files is still one commit."),
         o("Everything you did today.", false, "Unreviewable, and impossible to revert selectively."),
         o("Exactly one file, always.", false, "Splitting a single logical change across commits is just as confusing.")]),
      q("m10b", "Why work on a branch instead of committing straight to main?",
        [o("Main stays in a deployable state while your half-finished work is isolated.", true, "It also gives you a natural review unit before anything merges."),
         o("Branches make Git faster.", false, "Not the reason."),
         o("Beginners should avoid branches until they are confident.", false, "Backwards. Beginners benefit most from an undo boundary.")]),
      q("m10c", "A PR arrives with an empty description and 900 changed lines. What do you do first?",
        [o("Ask what changed, how to verify it, and what the risk is, before reading a single line.", true, "Reviewing 900 lines with no stated intent means you cannot tell deliberate from accidental."),
         o("Read it all carefully and form your own view.", false, "You will infer an intent that may not match, and review against the wrong target."),
         o("Approve it if CI is green.", false, "CI checks the tests that exist. It has no opinion on whether this was the right change.")]),
      q("m10d", "The diff includes a lockfile change you did not request. Significant?",
        [o("Yes \u2014 unrequested dependency changes alter what code actually runs, and deserve an explanation.", true, "Supply chain is part of review, even on a small project."),
         o("No, lockfiles are generated noise.", false, "Generated, yes. Noise, no \u2014 they pin what executes."),
         o("Only in large companies.", false, "The mechanism does not care how big your team is.")]),
      q("m10e", "You do not understand one hunk. CI is green and the author is confident. Approve?",
        [o("No. Ask for a walkthrough, or decline until you can explain it.", true, "Approval means you vouch for it. You cannot vouch for what you cannot explain."),
         o("Yes \u2014 holding up the PR over one hunk is obstructive.", false, "Asking a question is not obstruction. Rubber-stamping is negligence."),
         o("Yes, since the tests cover it.", false, "You do not know that, because you do not understand it.")]),
    ],
    11: [
      q("m11a", "What is the defining constraint of a refactor?",
        [o("Observable behaviour does not change \u2014 only the structure does.", true, "If behaviour changes, it is a feature or a fix, and it needs its own review and its own tests."),
         o("It must make the code shorter.", false, "Shorter is often better and is not the definition. Clarity is the goal."),
         o("It must be done before adding features.", false, "Sequencing preference, not definition.")]),
      q("m11b", "What makes a refactor safe to attempt at all?",
        [o("Tests that would fail if behaviour changed \u2014 they are the only way to tell a refactor from a rewrite.", true, "Refactoring without tests is rearranging code and hoping."),
         o("Doing it in small commits.", false, "Genuinely helps, and does not tell you whether behaviour moved."),
         o("Having the agent do it, since it will not make mistakes.", false, "It will happily change behaviour while tidying, and describe it as cleanup.")]),
      q("m11c", "There are three near-identical date-formatting functions in the codebase. Why does that matter beyond tidiness?",
        [o("A bug fixed in one stays broken in the other two, and nobody knows which callers use which.", true, "Duplication is a correctness problem that presents as an aesthetic one."),
         o("It makes the files larger.", false, "File size is not the cost."),
         o("It does not matter if all three work.", false, "They will drift. That is what duplicated logic does.")]),
      q("m11d", "Where do secrets like API keys belong?",
        [o("In environment configuration that is never committed, with the file listed in .gitignore.", true, "Committed secrets are effectively public, and remain in history after you delete them."),
         o("In the source, if the repository is private.", false, "Private today, forked, cloned, or opened tomorrow. History is permanent."),
         o("In a comment marked DO NOT SHARE.", false, "A comment is not a control.")]),
      q("m11e", "The agent renames a function used in two files, but only updates one call site. What happens?",
        [o("It breaks at runtime, in whichever path uses the stale name \u2014 possibly not the path you tested.", true, "Half-completed renames are a common agent failure and are invisible until that code path runs."),
         o("JavaScript resolves the old name automatically.", false, "It does not. You get an error when that line executes."),
         o("The formatter will catch it.", false, "Formatters do not resolve identifiers.")]),
    ],
    12: [
      q("m12a", "Priya's team cleans a duplicate-ridden export by hand every Monday. Why is that the right thing to automate?",
        [o("It is repetitive, rule-based, and currently costing a person hours \u2014 the exact profile a small script fixes.", true, "Automate the boring, well-defined, recurring thing. That is where scripts pay for themselves immediately."),
         o("Because Python is a better language than JavaScript.", false, "Fit for the task, not a ranking."),
         o("Because manual work is always wrong.", false, "Manual work is fine when it is rare or requires judgement.")]),
      q("m12b", "Why should a data-cleaning script exit with a non-zero status when its input is malformed?",
        [o("So whatever runs it can tell that it failed, instead of silently continuing with bad data.", true, "A script that fails quietly is worse than one that crashes loudly."),
         o("It is required by Python.", false, "Python defaults to zero; you have to do it deliberately."),
         o("To make error messages shorter.", false, "Unrelated.")]),
      q("m12c", "You ask an agent for a script to deduplicate a patient list. What must you decide, that it cannot?",
        [o("What counts as a duplicate \u2014 same email? same name and date of birth? case-insensitive? trimmed?", true, "That is a domain decision with real consequences, and it is exactly the kind of thing an agent will silently guess."),
         o("Which Python version to use.", false, "It can advise on that perfectly well."),
         o("How to loop over a list.", false, "Purely mechanical.")]),
      q("m12d", "What does this course explicitly not cover in Python?",
        [o("Retrieval, tool-calling agents, and model evaluation \u2014 that is the AI Engineering course.", true, "Here Python is for small tools that kill manual chores."),
         o("Functions and dictionaries.", false, "Both are covered."),
         o("Reading and writing files.", false, "Covered \u2014 it is the core of the ticket.")]),
      q("m12e", "Your deduplication script works on the sample file. What is the next thing to do?",
        [o("Write a test with a deliberately planted duplicate and confirm the script catches it.", true, "Working on one sample is an anecdote. A test that fails when dedup breaks is a guarantee."),
         o("Run it on the real export.", false, "Not until something proves it works on a case you constructed."),
         o("Hand it to Priya to try.", false, "Do not make the client your test suite.")]),
    ],
    13: [
      q("m13a", "What has to be true before you tell Dan the release is ready?",
        [o("A live URL someone else can open, tests that fail if the main feature breaks, and a written record of what you decided.", true, "Working locally is not shipping. Someone else being able to use it is."),
         o("The code is finished on your machine.", false, "That is where shipping starts, not where it ends."),
         o("The agent confirmed everything works.", false, "By now you know what that claim is worth.")]),
      q("m13b", "Why does a release note matter on a project this small?",
        [o("It records what changed and which decisions were deliberate, so the next person \u2014 usually you \u2014 does not re-litigate them.", true, "Undocumented decisions get accidentally reversed."),
         o("It is a formality clients expect.", false, "It is primarily for whoever maintains this next."),
         o("It replaces the need for commit messages.", false, "Different granularity, both useful.")]),
      q("m13c", "Your capstone tests all pass. Sam asks how you know they are worth anything. Best answer?",
        [o("\u201cI broke the feature on purpose and watched the test go red, then reverted.\u201d", true, "That is a demonstration that the test can fail, which is the only thing that makes green meaningful."),
         o("\u201cCoverage is high.\u201d", false, "Coverage measures execution, not assertion strength."),
         o("\u201cThe agent wrote them and it is good at tests.\u201d", false, "Unread agent-written tests are exactly where empty assertions come from.")]),
      q("m13d", "Which of these is honest to put on your portfolio after this course?",
        [o("\u201cBuilt and deployed a small web app with an AI coding agent; wrote the spec, reviewed every diff, and the tests that catch a regression.\u201d", true, "Specific, verifiable, and it matches what you can actually demonstrate."),
         o("\u201cSenior full-stack engineer.\u201d", false, "One course is not seniority, and the first technical conversation will establish that."),
         o("\u201cExpert in AI engineering and LLM systems.\u201d", false, "That is a different discipline that this course does not teach.")]),
      q("m13e", "Six months from now the site breaks. Who is accountable?",
        [o("You. The agent wrote the characters; you specified it, reviewed it, tested it, and shipped it.", true, "This is the sentence the whole course exists to earn. Authorship is not the same as ownership."),
         o("The model vendor.", false, "They have no relationship with Priya."),
         o("Nobody, if the tests were green at release.", false, "Green tests at release are not a transfer of responsibility.")]),
    ],
  };

  /* Extra pool for the Quiz Center, so retaking is not just the same
     five questions again. */
  const CENTER_EXTRA = {
    1: [q("m1x", "What is the smallest useful definition of \u201cshipped\u201d?",
      [o("Someone other than you can see the change and benefit from it.", true, "Local success is not shipping."),
       o("The file is saved.", false, "Nobody is affected by a saved file."),
       o("The agent said it was done.", false, "That is a claim, not a change.")])],
    3: [q("m3x", "Placeholder text instead of a label. What breaks?",
      [o("The name of the field disappears as soon as the user types, and it may never be announced at all.", true, "Placeholders are hints, not labels."),
       o("Nothing, they are equivalent.", false, "They are not."),
       o("Only the styling.", false, "It is a usability and accessibility defect.")])],
    5: [q("m5x", "An agent writes <code>return list.filter(x =&gt; x.status = 'open')</code>. What happens?",
      [o("Single equals assigns instead of comparing, so every record is mutated and every one is kept.", true, "One character. Every row silently rewritten."),
       o("A syntax error.", false, "It is valid JavaScript, which is what makes it dangerous."),
       o("It filters correctly.", false, "It filters nothing and corrupts the data.")])],
    8: [q("m8x", "An agent's function is 200 lines and passes all tests. Reasonable review response?",
      [o("Ask for it to be split into named steps, because nobody can review or maintain 200 lines as one unit.", true, "Passing tests and being maintainable are unrelated properties."),
       o("Approve it \u2014 tests are what matter.", false, "You will inherit it."),
       o("Reject it for being long, with no further comment.", false, "Name the problem and what would resolve it.")])],
    9: [q("m9x", "A test reads <code>expect(true).toBe(true)</code>. What is it worth?",
      [o("Nothing \u2014 it cannot fail, so it detects nothing.", true, "It exists to make a number go up."),
       o("It verifies the test runner works.", false, "That is not why it is in the suite."),
       o("It is a reasonable placeholder.", false, "A placeholder that reports success is worse than no test.")])],
    11: [q("m11x", "Your refactor makes the code clearly better and changes one edge-case behaviour. What is it now?",
      [o("Not a refactor. It is a behaviour change and needs its own review and test.", true, "The label matters because it sets what reviewers check."),
       o("Still a refactor, since the intent was cleanup.", false, "Intent does not determine the category; effect does."),
       o("A bug fix, automatically.", false, "Only if the old behaviour was wrong, which you would need to establish.")])],
  };

  global.AISEQuizData = { MODULE_QUIZZES, CENTER_EXTRA };
})(window);
