# -*- coding: utf-8 -*-
"""Append extra JS + detective tasks to reach a richer 200-task catalog."""
from pathlib import Path

COURSE = Path(__file__).resolve().parents[1] / "courses" / "ai-assisted-software-engineering"
SRC = COURSE / "practice-tasks.js"
text = SRC.read_text(encoding="utf-8")
if "js-f41" in text:
    print("already appended")
    raise SystemExit(0)

extra = r'''
  { id: "js-f41", skill: "js-arrays", tool: "js", level: "guided", kind: "js", title: "open only", prompt: "Return rows whose status is exactly open.", functionName: "open_only", starter: "function open_only(rows){\n  return rows;\n}", testCases: [{"name": "mix", "args": [[{"status": "open"}, {"status": "done"}]], "expected": [{"status": "open"}]}, {"name": "empty", "args": [[]], "expected": []}], prerequisite: [] },
  { id: "js-f42", skill: "js-strings", tool: "js", level: "guided", kind: "js", title: "clinic greeting", prompt: "greeting(name) is 'Welcome to Northline, Ada.' when name is Ada. Empty name is 'Welcome to Northline.'", functionName: "greeting", starter: "function greeting(name){\n  return '';\n}", testCases: [{"name": "named", "args": ["Ada"], "expected": "Welcome to Northline, Ada."}, {"name": "blank", "args": [""], "expected": "Welcome to Northline."}], prerequisite: [] },
  { id: "js-f43", skill: "js-functions", tool: "js", level: "semiguided", kind: "js", title: "is open today", prompt: "is_open_today(days, today) where days is like ['Tue','Wed'] and today is 'Wed'. True if today is listed.", functionName: "is_open_today", starter: "function is_open_today(days, today){\n  return false;\n}", testCases: [{"name": "open", "args": [["Tue", "Wed"], "Wed"], "expected": true}, {"name": "closed", "args": [["Tue", "Wed"], "Sun"], "expected": false}], prerequisite: [] },
  { id: "js-f44", skill: "js-arrays", tool: "js", level: "semiguided", kind: "js", title: "filter clinician", prompt: "Keep rows whose clinician equals the name.", functionName: "filter_clinician", starter: "function filter_clinician(rows, name){\n  return rows;\n}", testCases: [{"name": "one", "args": [[{"clinician": "Sam"}, {"clinician": "Priya"}], "Sam"], "expected": [{"clinician": "Sam"}]}, {"name": "none", "args": [[{"clinician": "Sam"}], "Dan"], "expected": []}], prerequisite: [] },
  { id: "js-f45", skill: "js-objects", tool: "js", level: "semiguided", kind: "js", title: "hours map", prompt: "hours_map([['Tue','9-17']]) -> {Tue:'9-17'}.", functionName: "hours_map", starter: "function hours_map(pairs){\n  return {};\n}", testCases: [{"name": "two", "args": [[["Tue", "9-17"], ["Sat", "9-13"]]], "expected": {"Tue": "9-17", "Sat": "9-13"}}], prerequisite: [] },
  { id: "js-f46", skill: "js-strings", tool: "js", level: "challenge", kind: "js", title: "normalise email", prompt: "Trim and lowercase. Empty or missing becomes ''.", functionName: "normalise_email", starter: "function normalise_email(s){\n  return s;\n}", testCases: [{"name": "pad", "args": ["  A@X.CO "], "expected": "a@x.co"}, {"name": "empty", "args": [""], "expected": ""}, {"name": "null", "args": [null], "expected": ""}], prerequisite: [] },
  { id: "js-f47", skill: "js-arrays", tool: "js", level: "challenge", kind: "js", title: "next open slot", prompt: "First row with status open, or null.", functionName: "next_open_slot", starter: "function next_open_slot(rows){\n  return null;\n}", testCases: [{"name": "second", "args": [[{"status": "done"}, {"status": "open", "id": 2}]], "expected": {"status": "open", "id": 2}}, {"name": "none", "args": [[{"status": "done"}]], "expected": null}], prerequisite: [] },
  { id: "js-f48", skill: "js-functions", tool: "js", level: "challenge", kind: "js", title: "can book date", prompt: "can_book_date(date, today, closedDates). False if date < today or date is in closedDates. ISO date strings only.", functionName: "can_book_date", starter: "function can_book_date(date, today, closedDates){\n  return true;\n}", testCases: [{"name": "future", "args": ["2026-09-01", "2026-08-30", []], "expected": true}, {"name": "past", "args": ["2026-08-29", "2026-08-30", []], "expected": false}, {"name": "listed closed", "args": ["2026-09-01", "2026-08-30", ["2026-09-01"]], "expected": false}, {"name": "today ok", "args": ["2026-08-30", "2026-08-30", []], "expected": true}], prerequisite: [] },
  { id: "js-f49", skill: "js-objects", tool: "js", level: "mastery", kind: "js", title: "tally statuses", prompt: "tally_statuses(rows) -> {open:n, done:n, other:n}. Missing status is other.", functionName: "tally_statuses", starter: "function tally_statuses(rows){\n  return {};\n}", testCases: [{"name": "mix", "args": [[{"status": "open"}, {"status": "open"}, {"status": "done"}, {}]], "expected": {"open": 2, "done": 1, "other": 1}}, {"name": "empty", "args": [[]], "expected": {"open": 0, "done": 0, "other": 0}}], prerequisite: [] },
  { id: "js-f50", skill: "js-arrays", tool: "js", level: "mastery", kind: "js", title: "window last n days", prompt: "in_window(rows, today, n) keeps rows whose date string is >= minDate and <= today. Compute minDate as the ISO date n-1 days before today using Date.UTC. n<=0 returns [].", functionName: "in_window", starter: "function in_window(rows, today, n){\n  return rows;\n}", testCases: [{"name": "keeps today", "args": [[{"date": "2026-08-30"}, {"date": "2026-08-22"}], "2026-08-30", 7], "expected": [{"date": "2026-08-30"}]}, {"name": "n zero", "args": [[{"date": "2026-08-30"}], "2026-08-30", 0], "expected": []}], prerequisite: [] },
  { id: "det-09", skill: "ai-failure-detection", tool: "detective", level: "guided", kind: "detective", title: "The Book control that is a div", prompt: "Ship a Book control in the header.", case: {"ticket": "NL-D09", "author": "Written by the coding agent", "ask": "Add a Book control that opens the contact form.", "lang": "html", "code": "<div class=\"btn\" onclick=\"openBook()\">Book</div>", "findings": [{"id": "f1", "cat": "a11y", "real": true, "label": "a div is not a control", "why": "Not focusable, not keyboard-operable, not announced as a button."}, {"id": "f2", "cat": "naming", "real": false, "label": "class btn is too short", "why": "A style preference. The element is the defect."}, {"id": "f3", "cat": "security", "real": false, "label": "onclick is illegal HTML", "why": "It is legal. It is still the wrong element."}], "fix": {"functionName": "isRealControl", "note": "Return true only for button or a[href].", "starter": "function isRealControl(tag, href){\n\n}", "testCases": [{"name": "button", "args": ["button", null], "expected": true}, {"name": "link", "args": ["a", "#contact"], "expected": true}, {"name": "div", "args": ["div", null], "expected": false}]}}, prerequisite: [] },
  { id: "det-10", skill: "ai-failure-detection", tool: "detective", level: "guided", kind: "detective", title: "The email check that accepts @", prompt: "Validate an email before submit.", case: {"ticket": "NL-D10", "author": "Written by the coding agent", "ask": "Reject empty or obviously invalid emails.", "lang": "js", "code": "function okEmail(s) {\n  return s.includes(\"@\");\n}", "findings": [{"id": "f1", "cat": "validation", "real": true, "label": "a lone @ passes", "why": "includes('@') is a presence check, not a mailbox."}, {"id": "f2", "cat": "edge", "real": true, "label": "null throws", "why": "A field the user never touched is not a string."}, {"id": "f3", "cat": "complexity", "real": false, "label": "should use a library", "why": "A tighter rule here is enough for class."}], "fix": {"functionName": "okEmail", "note": "True only if trimmed string has a character, then @, then a character. Never throw.", "starter": "function okEmail(s){\n\n}", "testCases": [{"name": "ok", "args": ["ada@site.com"], "expected": true}, {"name": "at only", "args": ["@"], "expected": false}, {"name": "empty", "args": [""], "expected": false}, {"name": "null", "args": [null], "expected": false}]}}, prerequisite: [] },
  { id: "det-11", skill: "ai-failure-detection", tool: "detective", level: "semiguided", kind: "detective", title: "The log that prints a card number", prompt: "Debug checkout.", case: {"ticket": "NL-D11", "author": "Written by the coding agent", "ask": "Log enough to debug a failed payment.", "lang": "js", "code": "console.log('card', payload.cardNumber);", "findings": [{"id": "f1", "cat": "security", "real": true, "label": "card number in the log", "why": "Logs leak. CI green does not make a secret safe."}, {"id": "f2", "cat": "comment", "real": false, "label": "should use debugger instead", "why": "A preference. The secret is the defect."}, {"id": "f3", "cat": "perf", "real": false, "label": "console.log is slow", "why": "Not why this is rejected."}], "fix": {"functionName": "safeLogPayload", "note": "Return a copy with cardNumber, cvv, and password removed.", "starter": "function safeLogPayload(p){\n\n}", "testCases": [{"name": "strips card", "args": [{"cardNumber": "4111", "ok": true}], "expected": {"ok": true}}, {"name": "keeps id", "args": [{"id": 3}], "expected": {"id": 3}}]}}, prerequisite: [] },
  { id: "det-12", skill: "ai-failure-detection", tool: "detective", level: "semiguided", kind: "detective", title: "The filter that assigns", prompt: "Keep open appointments.", case: {"ticket": "NL-D12", "author": "Written by the coding agent", "ask": "Return only open rows.", "lang": "js", "code": "return list.filter(x => x.status = 'open');", "findings": [{"id": "f1", "cat": "logic", "real": true, "label": "single equals assigns", "why": "Every row is mutated to open and kept. One character."}, {"id": "f2", "cat": "naming", "real": false, "label": "x is a poor name", "why": "Not the defect."}, {"id": "f3", "cat": "complexity", "real": false, "label": "filter is always wrong", "why": "filter is fine. The operator is not."}], "fix": {"functionName": "onlyOpen", "note": "Compare with ===. Do not mutate.", "starter": "function onlyOpen(list){\n\n}", "testCases": [{"name": "keeps open", "args": [[{"status": "open"}, {"status": "done"}]], "expected": [{"status": "open"}]}, {"name": "does not rewrite done", "args": [[{"status": "done"}]], "expected": []}]}}, prerequisite: [] },
  { id: "det-13", skill: "ai-failure-detection", tool: "detective", level: "challenge", kind: "detective", title: "The TEMP skip that shipped", prompt: "Expiry check on a gift voucher.", case: {"ticket": "NL-D13", "author": "Written by the coding agent", "ask": "Reject expired vouchers.", "lang": "js", "code": "// TEMP: skip expiry check so the demo works\nfunction voucherOk(v, today) {\n  return true;\n}", "findings": [{"id": "f1", "cat": "comment", "real": true, "label": "demo skip left in", "why": "A leftover skip is a product defect, not a comment style issue."}, {"id": "f2", "cat": "logic", "real": true, "label": "always returns true", "why": "Every voucher is accepted, including expired ones."}, {"id": "f3", "cat": "naming", "real": false, "label": "voucherOk should be isVoucherValid", "why": "A rename does not restore the check."}], "fix": {"functionName": "voucherOk", "note": "False if expiry is before today. Missing expiry is false. Never throw.", "starter": "function voucherOk(v, today){\n\n}", "testCases": [{"name": "future ok", "args": [{"expiry": "2026-09-02"}, "2026-08-30"], "expected": true}, {"name": "past no", "args": [{"expiry": "2026-08-01"}, "2026-08-30"], "expected": false}, {"name": "missing", "args": [{}, "2026-08-30"], "expected": false}]}}, prerequisite: [] },
  { id: "det-14", skill: "ai-failure-detection", tool: "detective", level: "challenge", kind: "detective", title: "The heading levels chosen by size", prompt: "Clinic page outline.", case: {"ticket": "NL-D14", "author": "Written by the coding agent", "ask": "Mark up hours under the clinic name.", "lang": "html", "code": "<h1>Northline Clinic</h1>\n<h4>Opening hours</h4>\n<h2>Tuesday to Saturday</h2>", "findings": [{"id": "f1", "cat": "a11y", "real": true, "label": "heading levels skip and invert", "why": "Outline is document structure, not font size."}, {"id": "f2", "cat": "naming", "real": false, "label": "h4 is deprecated", "why": "It is not. It is misused here."}, {"id": "f3", "cat": "complexity", "real": false, "label": "you may only use h1 and h2", "why": "All six levels are fine if they nest in order."}], "fix": {"functionName": "headingOk", "note": "True if levels are non-decreasing by at most 1 after the first h1. Input is an array of levels.", "starter": "function headingOk(levels){\n\n}", "testCases": [{"name": "1 then 2", "args": [[1, 2, 2]], "expected": true}, {"name": "skip", "args": [[1, 4]], "expected": false}, {"name": "invert", "args": [[1, 4, 2]], "expected": false}]}}, prerequisite: [] },
  { id: "det-15", skill: "ai-failure-detection", tool: "detective", level: "challenge", kind: "detective", title: "The empty catch on save", prompt: "Save clinician notes.", case: {"ticket": "NL-D15", "author": "Written by the coding agent", "ask": "Persist notes and tell the user if save fails.", "lang": "js", "code": "try {\n  saveNotes(notes);\n} catch (e) {}", "findings": [{"id": "f1", "cat": "logic", "real": true, "label": "empty catch swallows failure", "why": "The clinician sees success and the note is gone."}, {"id": "f2", "cat": "complexity", "real": false, "label": "try/catch is always wrong", "why": "Catching is fine. Swallowing is not."}, {"id": "f3", "cat": "naming", "real": false, "label": "e should be error", "why": "Not the defect."}], "fix": {"functionName": "saveOutcome", "note": "Return 'saved' or 'failed'. Never throw out.", "starter": "function saveOutcome(ok){\n\n}", "testCases": [{"name": "ok", "args": [true], "expected": "saved"}, {"name": "fail", "args": [false], "expected": "failed"}]}}, prerequisite: [] },
  { id: "det-16", skill: "ai-failure-detection", tool: "detective", level: "mastery", kind: "detective", title: "The innerHTML note render", prompt: "Show a clinician note.", case: {"ticket": "NL-D16", "author": "Written by the coding agent", "ask": "Render note.text into a paragraph.", "lang": "js", "code": "el.innerHTML = note.text;", "findings": [{"id": "f1", "cat": "security", "real": true, "label": "innerHTML with typed text", "why": "Markup in the note executes. textContent is the fix."}, {"id": "f2", "cat": "perf", "real": false, "label": "innerHTML is slower", "why": "Not why you reject it on a patient page."}, {"id": "f3", "cat": "naming", "real": false, "label": "el is too short", "why": "A preference."}], "fix": {"functionName": "safeText", "note": "Return the string to assign to textContent. Never keep tags as HTML — strip < and > to spaces.", "starter": "function safeText(s){\n\n}", "testCases": [{"name": "plain", "args": ["hello"], "expected": "hello"}, {"name": "tag", "args": ["<b>x</b>"], "expected": " b x /b "}, {"name": "null", "args": [null], "expected": ""}]}}, prerequisite: [] },
  { id: "det-17", skill: "ai-failure-detection", tool: "detective", level: "mastery", kind: "detective", title: "The placeholder that is not a label", prompt: "Email field on the Book form.", case: {"ticket": "NL-D17", "author": "Written by the coding agent", "ask": "Add an email field patients can recognise.", "lang": "html", "code": "<input type=\"email\" placeholder=\"Email address\">", "findings": [{"id": "f1", "cat": "a11y", "real": true, "label": "placeholder is not a label", "why": "It vanishes on type and is not a reliable name."}, {"id": "f2", "cat": "logic", "real": false, "label": "type email is not real", "why": "It is real and useful."}, {"id": "f3", "cat": "naming", "real": false, "label": "needs a title attribute", "why": "title is a tooltip, not a label."}], "fix": {"functionName": "hasLabel", "note": "True if labelFor === inputId and both are non-empty.", "starter": "function hasLabel(labelFor, inputId){\n\n}", "testCases": [{"name": "match", "args": ["email", "email"], "expected": true}, {"name": "miss", "args": ["", "email"], "expected": false}]}}, prerequisite: [] },
  { id: "det-18", skill: "ai-failure-detection", tool: "detective", level: "semiguided", kind: "detective", title: "The duplicated date helper", prompt: "Three copies of the same date parse.", case: {"ticket": "NL-D18", "author": "Written by the coding agent", "ask": "Parse ISO dates in booking, notes, and export.", "lang": "js", "code": "function p1(s){ return Date.parse(s); }\nfunction p2(s){ return Date.parse(s); }\nfunction p3(s){ return Date.parse(s); }", "findings": [{"id": "f1", "cat": "duplication", "real": true, "label": "three identical parsers", "why": "A bug will be fixed in one copy and live in the others."}, {"id": "f2", "cat": "perf", "real": false, "label": "Date.parse is slow", "why": "Not the finding."}, {"id": "f3", "cat": "naming", "real": false, "label": "p1 is fine in a demo", "why": "The duplication is the defect, not the demo names."}], "fix": {"functionName": "parseIso", "note": "One helper. Return ms or null if unparseable.", "starter": "function parseIso(s){\n\n}", "testCases": [{"name": "ok", "args": ["2026-08-30"], "expected": 1793059200000}, {"name": "bad", "args": ["nope"], "expected": null}]}}, prerequisite: [] },
  { id: "det-19", skill: "ai-failure-detection", tool: "detective", level: "guided", kind: "detective", title: "The alt text that says image", prompt: "Clinic front photo.", case: {"ticket": "NL-D19", "author": "Written by the coding agent", "ask": "Add the clinic photo with useful alt.", "lang": "html", "code": "<img src=\"clinic-front.jpg\" alt=\"image\">", "findings": [{"id": "f1", "cat": "a11y", "real": true, "label": "alt describes the file type", "why": "Alt should say what a sighted user gets from the image."}, {"id": "f2", "cat": "naming", "real": false, "label": "jpg should be webp", "why": "Format is not the defect."}, {"id": "f3", "cat": "complexity", "real": false, "label": "images are banned", "why": "They are not."}], "fix": {"functionName": "altUseful", "note": "False if alt is empty-of-meaning: image, photo, picture, or empty after trim. True otherwise.", "starter": "function altUseful(alt){\n\n}", "testCases": [{"name": "bad", "args": ["image"], "expected": false}, {"name": "good", "args": ["Northline Clinic front door"], "expected": true}]}}, prerequisite: [] },
  { id: "det-20", skill: "ai-failure-detection", tool: "detective", level: "mastery", kind: "detective", title: "The test that cannot fail", prompt: "Agent-written test for booking.", case: {"ticket": "NL-D20", "author": "Written by the coding agent", "ask": "Add a test that booking rejects an empty name.", "lang": "js", "code": "expect(true).toBe(true);", "findings": [{"id": "f1", "cat": "logic", "real": true, "label": "the assertion cannot fail", "why": "It detects nothing. Green is a lie."}, {"id": "f2", "cat": "comment", "real": false, "label": "needs more comments", "why": "Comments will not make it fail on a bug."}, {"id": "f3", "cat": "complexity", "real": false, "label": "toBe is deprecated", "why": "It is not."}], "fix": {"functionName": "testEmptyName", "note": "Return true only if impl({name:''}) is false and impl({name:'Ada'}) is true.", "starter": "function testEmptyName(impl){\n\n}", "testCases": [{"name": "good impl", "args": [null], "expected": true}]}}, prerequisite: [] },
'''

# det-20 testCases with a function arg won't work via JSON. Fix to a simpler function.
extra = extra.replace(
    '{ id: "det-20"',
    '{ id: "det-20-PLACEHOLDER"',
)
# rewrite det-20 as a simple boolean helper instead
extra = extra.replace(
    '{ id: "det-20-PLACEHOLDER", skill: "ai-failure-detection", tool: "detective", level: "mastery", kind: "detective", title: "The test that cannot fail", prompt: "Agent-written test for booking.", case: {"ticket": "NL-D20", "author": "Written by the coding agent", "ask": "Add a test that booking rejects an empty name.", "lang": "js", "code": "expect(true).toBe(true);", "findings": [{"id": "f1", "cat": "logic", "real": true, "label": "the assertion cannot fail", "why": "It detects nothing. Green is a lie."}, {"id": "f2", "cat": "comment", "real": false, "label": "needs more comments", "why": "Comments will not make it fail on a bug."}, {"id": "f3", "cat": "complexity", "real": false, "label": "toBe is deprecated", "why": "It is not."}], "fix": {"functionName": "testEmptyName", "note": "Return true only if impl({name:\'\'}) is false and impl({name:\'Ada\'}) is true.", "starter": "function testEmptyName(impl){\\n\\n}", "testCases": [{"name": "good impl", "args": [null], "expected": true}]}}, prerequisite: [] },',
    '{ id: "det-20", skill: "ai-failure-detection", tool: "detective", level: "mastery", kind: "detective", title: "The test that cannot fail", prompt: "Agent-written test for booking.", case: {"ticket": "NL-D20", "author": "Written by the coding agent", "ask": "Add a test that booking rejects an empty name.", "lang": "js", "code": "expect(true).toBe(true);", "findings": [{"id": "f1", "cat": "logic", "real": true, "label": "the assertion cannot fail", "why": "It detects nothing. Green is a lie."}, {"id": "f2", "cat": "comment", "real": false, "label": "needs more comments", "why": "Comments will not make it fail on a bug."}, {"id": "f3", "cat": "complexity", "real": false, "label": "toBe is deprecated", "why": "It is not."}], "fix": {"functionName": "assertionCanFail", "note": "Return false for expect(true).toBe(true). Return true for a check that compares impl output to a real value.", "starter": "function assertionCanFail(kind){\\n\\n}", "testCases": [{"name": "tautology", "args": ["always-true"], "expected": false}, {"name": "real", "args": ["compares-output"], "expected": true}]}}, prerequisite: [] },'
)

# js-f48 can_book_date depends on Date weekday — 2026-09-01 is Tuesday. Keep it simple; the first case may flake if we check weekday. Simplify expected to only past/today if weekday is messy.
# 2026-09-01 is Tuesday. closedDays [0] is Sunday. Fine.

# parseIso expected ms is timezone-dependent. Drop det-18 fix expected or use a relative check.
# Safer: change parseIso tests to return 0 for bad and 1 for any parseable.
extra = extra.replace(
    '"functionName": "parseIso", "note": "One helper. Return ms or null if unparseable.", "starter": "function parseIso(s){\\n\\n}", "testCases": [{"name": "ok", "args": ["2026-08-30"], "expected": 1793059200000}, {"name": "bad", "args": ["nope"], "expected": null}]',
    '"functionName": "parseIsoOk", "note": "Return true if Date.parse(s) is a finite number.", "starter": "function parseIsoOk(s){\\n\\n}", "testCases": [{"name": "ok", "args": ["2026-08-30"], "expected": true}, {"name": "bad", "args": ["nope"], "expected": false}]'
)

needle = "];\nglobal.AISE_TASKS = TASKS;"
if needle not in text:
    raise SystemExit("end marker not found")
SRC.write_text(text.replace(needle, extra.rstrip() + "\n" + needle, 1), encoding="utf-8")
print("appended js-f41..50 and det-09..20")
