"""Generate practice-tasks.js for AI-Assisted Software Engineering."""
from pathlib import Path

OUT = Path(r"d:\zenith-studio\courses\ai-assisted-software-engineering\practice-tasks.js")

def obj(d: dict) -> str:
    parts = []
    for k, v in d.items():
        if k in ("checks", "testCases", "options", "goodImpl", "badImpl") and isinstance(v, str):
            parts.append(f"{k}: {v}")
        elif isinstance(v, bool):
            parts.append(f"{k}: {'true' if v else 'false'}")
        elif isinstance(v, (int, float)):
            parts.append(f"{k}: {v}")
        elif v is None:
            continue
        else:
            s = str(v).replace("\\", "\\\\").replace("`", "\\`")
            parts.append(f"{k}: {js_str(v)}" if not (isinstance(v, str) and v.startswith("[")) else f"{k}: {v}")
    return "{ " + ", ".join(parts) + " }"

def js_str(v) -> str:
    return json_dumps(v)

import json
def json_dumps(v):
    return json.dumps(v, ensure_ascii=False)

tasks = []

# ---- HTML 20 ----
html_items = [
    ("html-f01", "html-structure", "guided", "A single heading",
     "Write a page whose only heading is an <h1> with the exact text Welcome.",
     "<!DOCTYPE html><html><body></body></html>",
     "[{ name: 'has h1', hint: 'Add an h1.', test: d => !!d.querySelector('h1') }, { name: 'text is Welcome', hint: 'The h1 text must be exactly Welcome.', test: d => (d.querySelector('h1')||{}).textContent.trim() === 'Welcome' }]"),
    ("html-f02", "html-structure", "guided", "Paragraph under the heading",
     "Add an h1 'Clinic hours' and a <p> that contains the word Saturday.",
     "<!DOCTYPE html><html><body></body></html>",
     "[{ name: 'h1', test: d => (d.querySelector('h1')||{}).textContent.includes('Clinic hours'), hint: 'h1 must include Clinic hours' }, { name: 'paragraph mentions Saturday', test: d => (d.querySelector('p')||{}).textContent.includes('Saturday'), hint: 'Need a p that mentions Saturday' }]"),
    ("html-f03", "html-structure", "guided", "Unordered list of three items",
     "Make a <ul> with exactly three <li> elements.",
     "<!DOCTYPE html><html><body></body></html>",
     "[{ name: 'ul exists', test: d => !!d.querySelector('ul'), hint: 'Use ul, not ol' }, { name: 'three li', test: d => d.querySelectorAll('ul li').length === 3, hint: 'Exactly three li inside the ul' }]"),
    ("html-f04", "html-links", "guided", "A real link",
     "Add an <a> whose href is https://example.com and whose text is Docs.",
     "<!DOCTYPE html><html><body></body></html>",
     "[{ name: 'anchor', test: d => !!d.querySelector('a'), hint: 'Need an a tag' }, { name: 'href', test: d => (d.querySelector('a')||{}).getAttribute('href') === 'https://example.com', hint: 'href must be https://example.com' }, { name: 'text', test: d => (d.querySelector('a')||{}).textContent.trim() === 'Docs', hint: 'Link text must be Docs' }]"),
    ("html-f05", "html-forms", "guided", "Labeled email field",
     "A form with a label for='email' and an input id='email' type='email'.",
     "<!DOCTYPE html><html><body></body></html>",
     "[{ name: 'input email', test: d => { const i=d.querySelector('#email'); return i && i.getAttribute('type')==='email'; }, hint: 'id=email type=email' }, { name: 'label for', test: d => { const l=d.querySelector('label[for=email]'); return !!l; }, hint: 'label for=email' }]"),
    ("html-f06", "html-structure", "semiguided", "Header, main, footer",
     "Use <header>, <main>, and <footer> once each. Put an h1 inside header.",
     "<!DOCTYPE html><html><body></body></html>",
     "[{ name: 'header', test: d => d.querySelectorAll('header').length===1, hint: 'One header' }, { name: 'main', test: d => d.querySelectorAll('main').length===1, hint: 'One main' }, { name: 'footer', test: d => d.querySelectorAll('footer').length===1, hint: 'One footer' }, { name: 'h1 in header', test: d => !!d.querySelector('header h1'), hint: 'h1 belongs in the header' }]"),
    ("html-f07", "html-images", "semiguided", "Image with alt",
     "Add an img with src='clinic.jpg' and a non-empty alt attribute.",
     "<!DOCTYPE html><html><body></body></html>",
     "[{ name: 'img src', test: d => (d.querySelector('img')||{}).getAttribute('src')==='clinic.jpg', hint: 'src=clinic.jpg' }, { name: 'alt present', test: d => { const a=(d.querySelector('img')||{}).getAttribute('alt'); return typeof a==='string' && a.trim().length>0; }, hint: 'alt must not be empty' }]"),
    ("html-f08", "html-forms", "semiguided", "Required name field",
     "A form with input name='fullName' that is required.",
     "<!DOCTYPE html><html><body><form></form></body></html>",
     "[{ name: 'named input', test: d => !!d.querySelector('input[name=fullName]'), hint: 'name=fullName' }, { name: 'required', test: d => d.querySelector('input[name=fullName]') && d.querySelector('input[name=fullName]').hasAttribute('required'), hint: 'Add the required attribute' }]"),
    ("html-f09", "html-tables", "semiguided", "Two-column table",
     "A table with a thead row of Day and Hours, and at least one tbody row.",
     "<!DOCTYPE html><html><body></body></html>",
     "[{ name: 'table', test: d => !!d.querySelector('table'), hint: 'Need a table' }, { name: 'thead cells', test: d => { const t=[...d.querySelectorAll('thead th, thead td')].map(x=>x.textContent.trim()); return t.includes('Day') && t.includes('Hours'); }, hint: 'thead must include Day and Hours' }, { name: 'tbody row', test: d => d.querySelectorAll('tbody tr').length>=1, hint: 'At least one tbody tr' }]"),
    ("html-f10", "html-structure", "challenge", "Skip-link",
     "First focusable thing in body is an a.href='#main'. A main#main exists.",
     "<!DOCTYPE html><html><body></body></html>",
     "[{ name: 'skip href', test: d => { const a=d.querySelector('body a'); return a && a.getAttribute('href')==='#main'; }, hint: 'First body link should be href=#main' }, { name: 'main id', test: d => !!d.querySelector('main#main'), hint: 'Need main id=main' }]"),
    ("html-f11", "html-forms", "challenge", "Fieldset for hours",
     "A fieldset whose legend text is Hours, containing two radio inputs that share name='shift'.",
     "<!DOCTYPE html><html><body></body></html>",
     "[{ name: 'legend', test: d => (d.querySelector('fieldset legend')||{}).textContent.trim()==='Hours', hint: 'legend Hours' }, { name: 'two radios', test: d => d.querySelectorAll('fieldset input[type=radio][name=shift]').length===2, hint: 'Two radios named shift' }]"),
    ("html-f12", "html-links", "challenge", "New-tab link is safe",
     "An a[target=_blank] must also have rel that includes noopener.",
     "<!DOCTYPE html><html><body></body></html>",
     "[{ name: 'target blank', test: d => !!d.querySelector('a[target=_blank]'), hint: 'Need target=_blank' }, { name: 'noopener', test: d => { const r=(d.querySelector('a[target=_blank]')||{}).getAttribute('rel')||''; return r.split(/\\s+/).includes('noopener'); }, hint: 'rel must include noopener' }]"),
    ("html-f13", "html-structure", "guided", "Language on html",
     "The html element must have lang='en'.",
     "<html><body><p>Hi</p></body></html>",
     "[{ name: 'lang en', test: d => d.documentElement.getAttribute('lang')==='en', hint: 'Set html lang=en' }]"),
    ("html-f14", "html-structure", "semiguided", "One h1 only",
     "Exactly one h1. You may use h2 after it.",
     "<!DOCTYPE html><html><body><h1>A</h1><h1>B</h1></body></html>",
     "[{ name: 'exactly one h1', test: d => d.querySelectorAll('h1').length===1, hint: 'Remove the extra h1' }]"),
    ("html-f15", "html-forms", "guided", "Button submits",
     "A form with a button type='submit' whose text is Send.",
     "<!DOCTYPE html><html><body><form></form></body></html>",
     "[{ name: 'submit button', test: d => { const b=d.querySelector('form button[type=submit], form input[type=submit]'); return !!b; }, hint: 'type=submit' }, { name: 'Send', test: d => { const b=d.querySelector('form button'); return b && b.textContent.trim()==='Send'; }, hint: 'Button text Send' }]"),
    ("html-f16", "html-images", "guided", "Decorative image",
     "An img with empty alt='' (decorative) and src='line.svg'.",
     "<!DOCTYPE html><html><body></body></html>",
     "[{ name: 'src', test: d => (d.querySelector('img')||{}).getAttribute('src')==='line.svg', hint: 'src=line.svg' }, { name: 'empty alt', test: d => (d.querySelector('img')||{}).getAttribute('alt')==='', hint: 'alt must be present and empty' }]"),
    ("html-f17", "html-structure", "challenge", "Nav with two links",
     "A nav containing exactly two a tags.",
     "<!DOCTYPE html><html><body></body></html>",
     "[{ name: 'nav', test: d => !!d.querySelector('nav'), hint: 'Need nav' }, { name: 'two links', test: d => d.querySelectorAll('nav a').length===2, hint: 'Exactly two anchors in nav' }]"),
    ("html-f18", "html-tables", "challenge", "Scope on headers",
     "A table th with scope='col'.",
     "<!DOCTYPE html><html><body></body></html>",
     "[{ name: 'th scope col', test: d => !!d.querySelector('th[scope=col]'), hint: 'Add th scope=col' }]"),
    ("html-f19", "html-forms", "mastery", "Accessible search",
     "A form with role or an input type=search labeled via aria-label='Search site'.",
     "<!DOCTYPE html><html><body></body></html>",
     "[{ name: 'search input', test: d => !!d.querySelector('input[type=search]'), hint: 'type=search' }, { name: 'aria-label', test: d => (d.querySelector('input[type=search]')||{}).getAttribute('aria-label')==='Search site', hint: 'aria-label=Search site' }]"),
    ("html-f20", "html-structure", "mastery", "Article with time",
     "An article that contains a time datetime='2026-08-01' and an h2.",
     "<!DOCTYPE html><html><body></body></html>",
     "[{ name: 'article', test: d => !!d.querySelector('article'), hint: 'Need article' }, { name: 'time', test: d => (d.querySelector('article time')||{}).getAttribute('datetime')==='2026-08-01', hint: 'time datetime=2026-08-01' }, { name: 'h2', test: d => !!d.querySelector('article h2'), hint: 'h2 inside article' }]"),
]
for t in html_items:
    tasks.append({
        "id": t[0], "skill": t[1], "tool": "html", "level": t[2], "kind": "html",
        "title": t[3], "prompt": t[4], "starter": t[5], "checks": t[6],
        "prerequisite": "[]",
    })

# ---- CSS 20 ----
css_items = [
    ("css-f01", "css-selectors", "guided", "Paint the title blue",
     "Make h1 color #60a5fa.",
     "<h1 id='t'>Title</h1>",
     "h1 { }",
     "[{ name: 'h1 color', test: (root) => getComputedStyle(root.querySelector('h1')).color.replace(/\\s/g,'') === 'rgb(96,165,250)', hint: 'color: #60a5fa on h1' }]"),
    ("css-f02", "css-box", "guided", "Padding on the card",
     "Give .card padding of 24px.",
     "<div class='card'>Hi</div>",
     ".card { }",
     "[{ name: 'padding', test: (root) => getComputedStyle(root.querySelector('.card')).paddingTop === '24px', hint: 'padding: 24px' }]"),
    ("css-f03", "css-box", "guided", "Border not outline",
     "Give .card a 1px solid border. Color can be any non-transparent.",
     "<div class='card'>Hi</div>",
     ".card { }",
     "[{ name: 'border width', test: (root) => getComputedStyle(root.querySelector('.card')).borderTopWidth === '1px', hint: 'border: 1px solid ...' }]"),
    ("css-f04", "css-layout", "guided", "Flex row",
     "Make .row display flex.",
     "<div class='row'><span>a</span><span>b</span></div>",
     ".row { }",
     "[{ name: 'flex', test: (root) => getComputedStyle(root.querySelector('.row')).display === 'flex', hint: 'display: flex' }]"),
    ("css-f05", "css-layout", "semiguided", "Gap between items",
     ".row is flex with a 16px gap.",
     "<div class='row'><span>a</span><span>b</span></div>",
     ".row { }",
     "[{ name: 'flex', test: (root) => getComputedStyle(root.querySelector('.row')).display === 'flex', hint: 'display:flex' }, { name: 'gap', test: (root) => getComputedStyle(root.querySelector('.row')).gap === '16px' || getComputedStyle(root.querySelector('.row')).columnGap === '16px', hint: 'gap: 16px' }]"),
    ("css-f06", "css-typography", "guided", "Readable body",
     "p font-size 16px and line-height 1.5 (24px).",
     "<p>Hello</p>",
     "p { }",
     "[{ name: 'size', test: (root) => getComputedStyle(root.querySelector('p')).fontSize === '16px', hint: 'font-size: 16px' }, { name: 'leading', test: (root) => getComputedStyle(root.querySelector('p')).lineHeight === '24px', hint: 'line-height: 1.5' }]"),
    ("css-f07", "css-selectors", "semiguided", "Button hover is not required",
     "button.primary background #60a5fa.",
     "<button class='primary'>Go</button>",
     "button { }",
     "[{ name: 'bg', test: (root) => getComputedStyle(root.querySelector('button.primary')).backgroundColor.replace(/\\s/g,'') === 'rgb(96,165,250)', hint: 'button.primary { background: #60a5fa }' }]"),
    ("css-f08", "css-box", "semiguided", "Max width wrap",
     ".wrap max-width 720px and margin-left auto (centered).",
     "<div class='wrap'>x</div>",
     ".wrap { }",
     "[{ name: 'max-width', test: (root) => getComputedStyle(root.querySelector('.wrap')).maxWidth === '720px', hint: 'max-width: 720px' }, { name: 'ml auto', test: (root) => getComputedStyle(root.querySelector('.wrap')).marginLeft === 'auto', hint: 'margin-left: auto' }]"),
    ("css-f09", "css-layout", "challenge", "Grid two columns",
     ".grid display grid with two equal columns (1fr 1fr).",
     "<div class='grid'><div>a</div><div>b</div></div>",
     ".grid { }",
     "[{ name: 'grid', test: (root) => getComputedStyle(root.querySelector('.grid')).display === 'grid', hint: 'display:grid' }, { name: 'two cols', test: (root) => { const t=getComputedStyle(root.querySelector('.grid')).gridTemplateColumns; return t.split(' ').filter(Boolean).length===2; }, hint: 'grid-template-columns: 1fr 1fr' }]"),
    ("css-f10", "css-visibility", "guided", "Hide visually",
     ".sr-only should have position absolute and a clip or 1px size (any common sr-only pattern). Accept width 1px.",
     "<div class='sr-only'>skip</div>",
     ".sr-only { }",
     "[{ name: 'absolute or clip', test: (root) => { const s=getComputedStyle(root.querySelector('.sr-only')); return s.position==='absolute' || s.width==='1px' || s.clip !== 'auto'; }, hint: 'Use a screen-reader-only pattern: position:absolute; width:1px; overflow:hidden' }]"),
    ("css-f11", "css-box", "challenge", "Box sizing",
     "html or * uses border-box.",
     "<div class='box'>x</div>",
     "",
     "[{ name: 'border-box on box', test: (root, css) => /box-sizing\\s*:\\s*border-box/.test(css), hint: 'Write box-sizing: border-box in your CSS' }]"),
    ("css-f12", "css-typography", "semiguided", "Mono for code",
     "code uses a monospace font family (must include the word monospace).",
     "<code>x</code>",
     "code { }",
     "[{ name: 'mono', test: (root) => /mono/i.test(getComputedStyle(root.querySelector('code')).fontFamily), hint: 'font-family: ... monospace' }]"),
    ("css-f13", "css-selectors", "challenge", "Descendant only",
     "Only p inside .card should be color #9aa6c2. A p outside stays default (not that color).",
     "<div class='card'><p id='in'>in</p></div><p id='out'>out</p>",
     "",
     "[{ name: 'inside', test: (root) => getComputedStyle(root.querySelector('#in')).color.replace(/\\s/g,'')==='rgb(154,166,194)', hint: '.card p { color:#9aa6c2 }' }, { name: 'outside unchanged', test: (root) => getComputedStyle(root.querySelector('#out')).color.replace(/\\s/g,'')!=='rgb(154,166,194)', hint: 'Do not style all p' }]"),
    ("css-f14", "css-layout", "guided", "Center text",
     ".hero text-align center.",
     "<div class='hero'>Hi</div>",
     ".hero { }",
     "[{ name: 'center', test: (root) => getComputedStyle(root.querySelector('.hero')).textAlign === 'center', hint: 'text-align: center' }]"),
    ("css-f15", "css-box", "guided", "Margin below heading",
     "h2 margin-bottom 12px.",
     "<h2>Sec</h2>",
     "h2 { }",
     "[{ name: 'mb', test: (root) => getComputedStyle(root.querySelector('h2')).marginBottom === '12px', hint: 'margin-bottom: 12px' }]"),
    ("css-f16", "css-layout", "semiguided", "Space-between",
     ".bar is flex and justify-content space-between.",
     "<div class='bar'><span>L</span><span>R</span></div>",
     ".bar { }",
     "[{ name: 'flex', test: (root) => getComputedStyle(root.querySelector('.bar')).display==='flex', hint: 'display:flex' }, { name: 'between', test: (root) => getComputedStyle(root.querySelector('.bar')).justifyContent==='space-between', hint: 'justify-content: space-between' }]"),
    ("css-f17", "css-visibility", "semiguided", "Hide the extra",
     ".extra { display: none }",
     "<div class='extra'>no</div>",
     "",
     "[{ name: 'none', test: (root) => getComputedStyle(root.querySelector('.extra')).display==='none', hint: 'display: none' }]"),
    ("css-f18", "css-typography", "challenge", "Letter spacing eyebrow",
     ".eyebrow letter-spacing at least 1px and text-transform uppercase.",
     "<div class='eyebrow'>lab</div>",
     ".eyebrow { }",
     "[{ name: 'upper', test: (root) => getComputedStyle(root.querySelector('.eyebrow')).textTransform==='uppercase', hint: 'text-transform: uppercase' }, { name: 'tracking', test: (root) => parseFloat(getComputedStyle(root.querySelector('.eyebrow')).letterSpacing) >= 1, hint: 'letter-spacing: 0.1em or 2px' }]"),
    ("css-f19", "css-layout", "mastery", "Sticky header",
     ".top { position: sticky; top: 0 }",
     "<div class='top'>bar</div>",
     ".top { }",
     "[{ name: 'sticky', test: (root) => getComputedStyle(root.querySelector('.top')).position==='sticky', hint: 'position: sticky' }, { name: 'top 0', test: (root) => getComputedStyle(root.querySelector('.top')).top==='0px', hint: 'top: 0' }]"),
    ("css-f20", "css-box", "mastery", "Full-bleed section",
     ".bleed width 100% and no max-width (max-width none or 0 or empty).",
     "<div class='bleed'>x</div>",
     ".bleed { }",
     "[{ name: 'width 100%', test: (root, css) => /width\\s*:\\s*100%/.test(css), hint: 'width: 100%' }]"),
]
for t in css_items:
    tasks.append({
        "id": t[0], "skill": t[1], "tool": "css", "level": t[2], "kind": "css",
        "title": t[3], "prompt": t[4], "fixtureHtml": t[5], "starter": t[6], "checks": t[7],
        "prerequisite": "[]",
    })

# ---- JS 40 ----
js_funcs = [
    ("js-f01", "js-functions", "guided", "total_revenue", "Sum amount on a list of {amount} objects. Empty list is 0.",
     "def total_revenue",  # placeholder
     "function total_revenue(orders){\n  return 0;\n}",
     "[{ name: 'two', args: [[{amount:10},{amount:2.5}]], expected: 12.5 }, { name: 'empty', args: [[]], expected: 0 }]"),
    ("js-f02", "js-functions", "guided", "greet", "greet('Ada') returns 'Hello, Ada'.",
     None, "function greet(name){\n  return '';\n}",
     "[{ name: 'Ada', args: ['Ada'], expected: 'Hello, Ada' }, { name: 'Sam', args: ['Sam'], expected: 'Hello, Sam' }]"),
    ("js-f03", "js-functions", "guided", "is_even", "Return true if n is even.",
     None, "function is_even(n){\n  return false;\n}",
     "[{ name: '2', args: [2], expected: True }, { name: '3', args: [3], expected: False }, { name: '0', args: [0], expected: True }]"),
    ("js-f04", "js-arrays", "guided", "pluck_names", "From [{name}], return an array of names.",
     None, "function pluck_names(rows){\n  return [];\n}",
     "[{ name: 'two', args: [[{name:'A'},{name:'B'}]], expected: ['A','B'] }, { name: 'empty', args: [[]], expected: [] }]"),
    ("js-f05", "js-arrays", "guided", "count_status", "Count how many items have status === target.",
     None, "function count_status(rows, target){\n  return 0;\n}",
     "[{ name: 'open', args: [[{status:'open'},{status:'done'},{status:'open'}],'open'], expected: 2 }, { name: 'none', args: [[{status:'done'}],'open'], expected: 0 }]"),
    ("js-f06", "js-functions", "semiguided", "clamp", "clamp(n, lo, hi) keeps n in [lo, hi].",
     None, "function clamp(n, lo, hi){\n  return n;\n}",
     "[{ name: 'mid', args: [5,0,10], expected: 5 }, { name: 'low', args: [-1,0,10], expected: 0 }, { name: 'high', args: [99,0,10], expected: 10 }]"),
    ("js-f07", "js-strings", "guided", "slugify", "Lowercase, spaces to hyphens. 'Hello World' -> 'hello-world'.",
     None, "function slugify(s){\n  return s;\n}",
     "[{ name: 'basic', args: ['Hello World'], expected: 'hello-world' }, { name: 'already', args: ['ok'], expected: 'ok' }]"),
    ("js-f08", "js-strings", "semiguided", "initials", "'Ada Lovelace' -> 'AL'. Split on spaces, take first char of each word, upper.",
     None, "function initials(name){\n  return '';\n}",
     "[{ name: 'two', args: ['Ada Lovelace'], expected: 'AL' }, { name: 'one', args: ['Cher'], expected: 'C' }]"),
    ("js-f09", "js-arrays", "semiguided", "unique", "Return unique values preserving first-seen order.",
     None, "function unique(xs){\n  return xs;\n}",
     "[{ name: 'dups', args: [[1,1,2,1]], expected: [1,2] }, { name: 'none', args: [['a','b']], expected: ['a','b'] }]"),
    ("js-f10", "js-objects", "guided", "get_path", "get_path({a:{b:2}}, 'a.b') returns 2. Missing is null.",
     None, "function get_path(obj, path){\n  return null;\n}",
     "[{ name: 'nested', args: [{'a': {'b': 2}}, 'a.b'], expected: 2 }, { name: 'miss', args: [{'a': 1}, 'a.z'], expected: None }]"),
    ("js-f11", "js-functions", "semiguided", "average", "Mean of numbers. Empty list returns 0.",
     None, "function average(xs){\n  return 0;\n}",
     "[{ name: 'two', args: [[2,4]], expected: 3 }, { name: 'empty', args: [[]], expected: 0 }]"),
    ("js-f12", "js-arrays", "challenge", "group_by", "group_by([{k:'a'},{k:'b'},{k:'a'}], 'k') -> {a:[...], b:[...] } with original objects.",
     None, "function group_by(rows, key){\n  return {};\n}",
     "[{ name: 'two keys', args: [[{k:'a',n:1},{k:'b',n:2},{k:'a',n:3}],'k'], expected: {'a':[{'k':'a','n':1},{'k':'a','n':3}],'b':[{'k':'b','n':2}]} }]"),
    ("js-f13", "js-functions", "challenge", "parse_query", "parse_query('a=1&b=hi') -> {a:'1', b:'hi'}. No leading ?",
     None, "function parse_query(q){\n  return {};\n}",
     "[{ name: 'two', args: ['a=1&b=hi'], expected: {'a':'1','b':'hi'} }, { name: 'one', args: ['x=9'], expected: {'x':'9'} }]"),
    ("js-f14", "js-strings", "guided", "starts_with_http", "True if s starts with http:// or https://.",
     None, "function starts_with_http(s){\n  return false;\n}",
     "[{ name: 'https', args: ['https://x.com'], expected: True }, { name: 'ftp', args: ['ftp://x'], expected: False }, { name: 'http', args: ['http://x'], expected: True }]"),
    ("js-f15", "js-arrays", "guided", "sum_range", "Sum numbers from lo to hi inclusive.",
     None, "function sum_range(lo, hi){\n  return 0;\n}",
     "[{ name: '1-3', args: [1,3], expected: 6 }, { name: 'same', args: [4,4], expected: 4 }]"),
    ("js-f16", "js-objects", "semiguided", "pick", "pick({a:1,b:2,c:3}, ['a','c']) -> {a:1,c:3}.",
     None, "function pick(obj, keys){\n  return {};\n}",
     "[{ name: 'two', args: [{'a':1,'b':2,'c':3},['a','c']], expected: {'a':1,'c':3} }]"),
    ("js-f17", "js-functions", "challenge", "retry_ok", "retry_ok(fn, n) calls fn until it returns true or n times. Return true if any call was true.",
     None, "function retry_ok(fn, n){\n  return false;\n}",
     None),  # special - skip complex, replace
    ("js-f18", "js-arrays", "semiguided", "chunk", "chunk([1,2,3,4,5], 2) -> [[1,2],[3,4],[5]].",
     None, "function chunk(xs, n){\n  return [];\n}",
     "[{ name: '2', args: [[1,2,3,4,5],2], expected: [[1,2],[3,4],[5]] }]"),
    ("js-f19", "js-strings", "challenge", "mask_email", "mask_email('ada@site.com') -> 'a**@site.com' (first char + ** + @domain).",
     None, "function mask_email(e){\n  return e;\n}",
     "[{ name: 'ada', args: ['ada@site.com'], expected: 'a**@site.com' }]"),
    ("js-f20", "js-functions", "mastery", "deep_equal", "deep_equal on JSON-like values (no functions).",
     None, "function deep_equal(a, b){\n  return a === b;\n}",
     "[{ name: 'obj', args: [{'x':[1]}, {'x':[1]}], expected: True }, { name: 'diff', args: [{'x':1},{'x':2}], expected: False }]"),
]

# fix js-f17 with simple cases using a note - use increment instead
js_funcs[16] = (
    "js-f17", "js-functions", "challenge", "times",
    "times(n, fn) calls fn with 0..n-1 and returns the array of results.",
    None, "function times(n, fn){\n  return [];\n}",
    "[{ name: 'triple', args: [3, '(i)=>i*2'], expected: 'SPECIAL' }]",
)

# I'll implement js tasks more carefully without function args in JSON

js_clean = [
    ("js-f01","js-functions","guided","total_revenue","Sum .amount. Empty is 0.","function total_revenue(orders){\n  return 0;\n}",
     [{"name":"two","args":[[{"amount":10},{"amount":2.5}]],"expected":12.5},{"name":"empty","args":[[]],"expected":0}]),
    ("js-f02","js-functions","guided","greet","greet('Ada') is 'Hello, Ada'.","function greet(name){\n  return '';\n}",
     [{"name":"Ada","args":["Ada"],"expected":"Hello, Ada"}]),
    ("js-f03","js-functions","guided","is_even","True if n is even.","function is_even(n){\n  return false;\n}",
     [{"name":"2","args":[2],"expected":True},{"name":"3","args":[3],"expected":False}]),
    ("js-f04","js-arrays","guided","pluck_names","Map to .name.","function pluck_names(rows){\n  return [];\n}",
     [{"name":"two","args":[[{"name":"A"},{"name":"B"}]],"expected":["A","B"]}]),
    ("js-f05","js-arrays","guided","count_status","Count status === target.","function count_status(rows, target){\n  return 0;\n}",
     [{"name":"open","args":[[{"status":"open"},{"status":"done"},{"status":"open"}],"open"],"expected":2}]),
    ("js-f06","js-functions","semiguided","clamp","Keep n in [lo,hi].","function clamp(n, lo, hi){\n  return n;\n}",
     [{"name":"low","args":[-1,0,10],"expected":0},{"name":"high","args":[99,0,10],"expected":10}]),
    ("js-f07","js-strings","guided","slugify","Lowercase, spaces to -.","function slugify(s){\n  return s;\n}",
     [{"name":"basic","args":["Hello World"],"expected":"hello-world"}]),
    ("js-f08","js-strings","semiguided","initials","First letters uppercased.","function initials(name){\n  return '';\n}",
     [{"name":"two","args":["Ada Lovelace"],"expected":"AL"}]),
    ("js-f09","js-arrays","semiguided","unique","Unique, first-seen order.","function unique(xs){\n  return xs;\n}",
     [{"name":"dups","args":[[1,1,2,1]],"expected":[1,2]}]),
    ("js-f10","js-objects","guided","has_key","has_key(obj,k) true if k in obj.","function has_key(obj, k){\n  return false;\n}",
     [{"name":"yes","args":[{"a":1},"a"],"expected":True},{"name":"no","args":[{"a":1},"b"],"expected":False}]),
    ("js-f11","js-functions","semiguided","average","Mean, empty is 0.","function average(xs){\n  return 0;\n}",
     [{"name":"two","args":[[2,4]],"expected":3},{"name":"empty","args":[[]],"expected":0}]),
    ("js-f12","js-arrays","challenge","max_by_amount","Return the object with the largest amount.","function max_by_amount(rows){\n  return null;\n}",
     [{"name":"pick","args":[[{"id":1,"amount":3},{"id":2,"amount":9}]],"expected":{"id":2,"amount":9}}]),
    ("js-f13","js-strings","challenge","parse_kv","'a=1' -> {a:'1'}. Only one pair.","function parse_kv(s){\n  return {};\n}",
     [{"name":"one","args":["a=1"],"expected":{"a":"1"}}]),
    ("js-f14","js-strings","guided","starts_with_https","True if starts with https://.","function starts_with_https(s){\n  return false;\n}",
     [{"name":"ok","args":["https://x.com"],"expected":True},{"name":"http","args":["http://x"],"expected":False}]),
    ("js-f15","js-arrays","guided","sum_range","Inclusive sum lo..hi.","function sum_range(lo, hi){\n  return 0;\n}",
     [{"name":"1-3","args":[1,3],"expected":6}]),
    ("js-f16","js-objects","semiguided","pick","Keep only listed keys.","function pick(obj, keys){\n  return {};\n}",
     [{"name":"ac","args":[{"a":1,"b":2,"c":3},["a","c"]],"expected":{"a":1,"c":3}}]),
    ("js-f17","js-arrays","challenge","chunk","chunk(xs,2).","function chunk(xs, n){\n  return [];\n}",
     [{"name":"five","args":[[1,2,3,4,5],2],"expected":[[1,2],[3,4],[5]]}]),
    ("js-f18","js-arrays","semiguided","flatten_one","Flatten one level.","function flatten_one(xs){\n  return xs;\n}",
     [{"name":"mix","args":[[[1,2],3]],"expected":[1,2,3]}]),
    ("js-f19","js-strings","challenge","mask_email","a**@domain.","function mask_email(e){\n  return e;\n}",
     [{"name":"ada","args":["ada@site.com"],"expected":"a**@site.com"}]),
    ("js-f20","js-functions","mastery","deep_equal","JSON-like equality.","function deep_equal(a, b){\n  return a === b;\n}",
     [{"name":"obj","args":[{"x":[1]},{"x":[1]}],"expected":True},{"name":"diff","args":[{"x":1},{"x":2}],"expected":False}]),
    ("js-f21","js-functions","guided","triple","Return n * 3.","function triple(n){\n  return 0;\n}",
     [{"name":"4","args":[4],"expected":12}]),
    ("js-f22","js-arrays","guided","last","Last element or null.","function last(xs){\n  return null;\n}",
     [{"name":"has","args":[[1,2,9]],"expected":9},{"name":"empty","args":[[]],"expected":None}]),
    ("js-f23","js-strings","guided","title_case","First letter upper, rest lower, per word.","function title_case(s){\n  return s;\n}",
     [{"name":"two","args":["ada lovelace"],"expected":"Ada Lovelace"}]),
    ("js-f24","js-objects","guided","values_sum","Sum numeric Object.values.","function values_sum(obj){\n  return 0;\n}",
     [{"name":"ab","args":[{"a":2,"b":5}],"expected":7}]),
    ("js-f25","js-arrays","semiguided","zip_sum","zip_sum([1,2],[3,4]) -> [4,6]. Same length.","function zip_sum(a, b){\n  return [];\n}",
     [{"name":"two","args":[[1,2],[3,4]],"expected":[4,6]}]),
    ("js-f26","js-functions","semiguided","safe_div","a/b, or null if b is 0.","function safe_div(a, b){\n  return 0;\n}",
     [{"name":"ok","args":[10,2],"expected":5},{"name":"zero","args":[1,0],"expected":None}]),
    ("js-f27","js-arrays","challenge","index_by_id","[{id:'a',n:1}] -> {a:{id:'a',n:1}}.","function index_by_id(rows){\n  return {};\n}",
     [{"name":"one","args":[[{"id":"a","n":1}]],"expected":{"a":{"id":"a","n":1}}}]),
    ("js-f28","js-strings","semiguided","count_vowels","Count aeiou, case-insensitive.","function count_vowels(s){\n  return 0;\n}",
     [{"name":"Ada","args":["Ada"],"expected":2}]),
    ("js-f29","js-functions","challenge","compose_sum","compose_sum(f,g)(x) is f(g(x)) for numeric f,g passed as... wait skip"),
    ("js-f30","js-arrays","mastery","median","Median of numbers. Odd length.","function median(xs){\n  return 0;\n}",
     [{"name":"three","args":[[9,1,5]],"expected":5}]),
]

# replace broken f29
js_clean[28] = ("js-f29","js-objects","challenge","omit","omit({a:1,b:2}, ['b']) -> {a:1}.","function omit(obj, keys){\n  return obj;\n}",
    [{"name":"drop b","args":[{"a":1,"b":2},["b"]],"expected":{"a":1}}])

js_more = [
    ("js-f31","js-arrays","guided","includes_id","True if some row.id === id.","function includes_id(rows, id){\n  return false;\n}",
     [{"name":"yes","args":[[{"id":"x"}],"x"],"expected":True},{"name":"no","args":[[{"id":"x"}],"z"],"expected":False}]),
    ("js-f32","js-functions","guided","pct","pct(part, whole) rounded to 1 decimal. 1,4 -> 25.","function pct(part, whole){\n  return 0;\n}",
     [{"name":"quarter","args":[1,4],"expected":25}]),
    ("js-f33","js-strings","guided","trim_lower","trim + lower.","function trim_lower(s){\n  return s;\n}",
     [{"name":"pad","args":["  Hi "],"expected":"hi"}]),
    ("js-f34","js-arrays","semiguided","sort_by_name","Sort copy by name ascending.","function sort_by_name(rows){\n  return rows;\n}",
     [{"name":"ab","args":[[{"name":"b"},{"name":"a"}]],"expected":[{"name":"a"},{"name":"b"}]}]),
    ("js-f35","js-objects","semiguided","merge","Shallow merge, b wins.","function merge(a, b){\n  return a;\n}",
     [{"name":"win","args":[{"a":1,"b":2},{"b":9}],"expected":{"a":1,"b":9}}]),
    ("js-f36","js-functions","challenge","range","range(3) -> [0,1,2].","function range(n){\n  return [];\n}",
     [{"name":"3","args":[3],"expected":[0,1,2]}]),
    ("js-f37","js-arrays","challenge","partition","partition(xs, predName) — skip, use even/odd: evens first then odds, preserve order.","function partition_even(xs){\n  return xs;\n}",
     [{"name":"mix","args":[[1,2,3,4]],"expected":[[2,4],[1,3]]}]),
    ("js-f38","js-strings","mastery","is_palindrome","Ignore case and spaces.","function is_palindrome(s){\n  return false;\n}",
     [{"name":"race","args":["Race car"],"expected":True},{"name":"no","args":["hello"],"expected":False}]),
    ("js-f39","js-functions","mastery","memo_add","Just add(a,b) correctly.","function add(a, b){\n  return 0;\n}",
     [{"name":"2+3","args":[2,3],"expected":5}]),
    ("js-f40","js-arrays","mastery","running_total","[1,2,3] -> [1,3,6].","function running_total(xs){\n  return [];\n}",
     [{"name":"three","args":[[1,2,3]],"expected":[1,3,6]}]),
]
js_clean.extend(js_more)

for t in js_clean:
    tid, skill, level, fname, prompt, starter, cases = t[0], t[1], t[2], t[3], t[4], t[5], t[6]
    tasks.append({
        "id": tid, "skill": skill, "tool": "js", "level": level, "kind": "js",
        "title": fname.replace("_", " "), "prompt": prompt, "functionName": fname,
        "starter": starter, "testCases": json.dumps(cases), "prerequisite": "[]",
    })

def choice_task(tid, skill, tool, level, title, prompt, options, correct, why_ok, why_bad):
    opts = json.dumps(options)
    return {
        "id": tid, "skill": skill, "tool": tool, "level": level, "kind": "choice",
        "title": title, "prompt": prompt, "options": opts, "correct": correct,
        "whyOk": why_ok, "whyBad": why_bad, "prerequisite": "[]",
    }

# Specs 20
spec_prompts = [
    ("spec-f01","Write acceptance criteria, not a vibe. Which is a real criterion?",
     [{"value":"correct","label":"Given an empty email, the form shows 'Email is required' and does not submit."},
      {"value":"w1","label":"The form should feel polished."},
      {"value":"w2","label":"Use Tailwind and make it pop."}],
     "correct","A stranger can implement and test that.","Feelings and tool choices are not acceptance criteria."),
    ("spec-f02","A ticket says 'make login better'. What do you do first?",
     [{"value":"correct","label":"Ask what 'better' means in one measurable way (time, errors, or a specific screen)."},
      {"value":"w1","label":"Tell Cursor to rewrite auth."},
      {"value":"w2","label":"Add a new CSS library."}],
     "correct","Unmeasured 'better' is how agents invent scope.","The agent will happily invent a rewrite you cannot review."),
    ("spec-f03","Which prompt is safer to give a coding agent?",
     [{"value":"correct","label":"In auth.js, add a function isEmail(s) that returns true only if s contains @ and a dot after it. Do not change other files. Show a diff."},
      {"value":"w1","label":"Fix everything related to users."},
      {"value":"w2","label":"You are a senior engineer, go."}],
     "correct","File, function, rule, and a diff request.","Unbounded prompts produce unbounded diffs."),
    ("spec-f04","The agent offers to 'also clean up' nearby files. You should:",
     [{"value":"correct","label":"Say no. Ask for the one requested change, then a second pass if you want cleanup."},
      {"value":"w1","label":"Accept. Cleanup is free."},
      {"value":"w2","label":"Delete the repo and start over."}],
     "correct","Drive-by edits hide regressions.","Cleanup is where untested behavior dies."),
    ("spec-f05","A good spec names:",
     [{"value":"correct","label":"Actor, action, result, and what must not happen."},
      {"value":"w1","label":"Only the library you hope to use."},
      {"value":"w2","label":"A mood board."}],
     "correct","Those four are testable.","Tools and vibes are not the behavior."),
    ("spec-f06","You need a cancel button. Best criterion?",
     [{"value":"correct","label":"Clicking Cancel closes the dialog and does not call save()."},
      {"value":"w1","label":"Cancel should be intuitive."},
      {"value":"w2","label":"Use a red button maybe."}],
     "correct","You can write a test for save not being called.","Color is not the behavior."),
    ("spec-f07","The agent pasted a 400-line file. Next move?",
     [{"value":"correct","label":"Ask it to split the diff by file and explain each hunk in one sentence."},
      {"value":"w1","label":"Commit it. Length means quality."},
      {"value":"w2","label":"Copy it into production without reading."}],
     "correct","You cannot review what you cannot see.","Size is not evidence."),
    ("spec-f08","Out of scope for a 'add logout button' ticket:",
     [{"value":"correct","label":"Rewriting the database schema."},
      {"value":"w1","label":"A button that calls the existing logout function."},
      {"value":"w2","label":"Hiding the button when already logged out."}],
     "correct","Schema work is a different ticket.","The other two are the feature."),
    ("spec-f09","Acceptance criteria should be written:",
     [{"value":"correct","label":"Before you ask the agent to write code."},
      {"value":"w1","label":"After deploy, from memory."},
      {"value":"w2","label":"Never, if you trust the model."}],
     "correct","Criteria are the contract.","Trust is not a test."),
    ("spec-f10","'Looks good to me' is:",
     [{"value":"correct","label":"Not a review. Name one behavior you checked."},
      {"value":"w1","label":"The gold standard of senior review."},
      {"value":"w2","label":"Required by GitHub."}],
     "correct","LGTM without a check is a shrug.","Review means you can name a risk you looked for."),
    ("spec-f11","Best @-mention habit:",
     [{"value":"correct","label":"Point at the 1–3 files that must change."},
      {"value":"w1","label":"Attach the entire monorepo every time."},
      {"value":"w2","label":"Never mention files; keep it mysterious."}],
     "correct","Context should be scarce and relevant.","The whole repo is noise."),
    ("spec-f12","A spec that says 'use whatever':",
     [{"value":"correct","label":"Forces you to review architecture you did not choose on purpose."},
      {"value":"w1","label":"Is how professionals work."},
      {"value":"w2","label":"Guarantees the cheapest model."}],
     "correct","You still own the stack.","Agents pick fashionable defaults."),
    ("spec-f13","When the agent invents an API that does not exist:",
     [{"value":"correct","label":"Reject the hunk. Ask it to use the function that already exists in the file you @-mentioned."},
      {"value":"w1","label":"Ship it; the compiler will invent the API."},
      {"value":"w2","label":"Add the fake API to production to match."}],
     "correct","Hallucinated helpers are a classic miss.","Compilers do not invent endpoints."),
    ("spec-f14","Definition of done for a tiny feature includes:",
     [{"value":"correct","label":"A test that fails if you break the feature, plus the feature itself."},
      {"value":"w1","label":"A screenshot only."},
      {"value":"w2","label":"A commit message that says WIP forever."}],
     "correct","Without a failing test you only have a demo.","Screenshots do not catch regressions."),
    ("spec-f15","You should refuse to implement when:",
     [{"value":"correct","label":"The requester cannot name a user-visible result."},
      {"value":"w1","label":"The CSS is not using the newest framework."},
      {"value":"w2","label":"The ticket is only one paragraph."}],
     "correct","No result means no ticket.","Short can still be precise."),
    ("spec-f16","A constraint example:",
     [{"value":"correct","label":"Do not add new dependencies."},
      {"value":"w1","label":"Make it world-class."},
      {"value":"w2","label":"Use AI a lot."}],
     "correct","Constraints are checkable.","Adjectives are not."),
    ("spec-f17","Asking for a diff matters because:",
     [{"value":"correct","label":"You review changes, not a whole rewritten file dumped in chat."},
      {"value":"w1","label":"Diffs are only for Git experts."},
      {"value":"w2","label":"The agent cannot produce diffs."}],
     "correct","Diffs are the review surface.","You will learn to read them in Module 5."),
    ("spec-f18","Second-pass prompt after a good first change:",
     [{"value":"correct","label":"Add a test for the empty-string case. Do not change the implementation unless a test fails."},
      {"value":"w1","label":"Now rebuild the app in Rust."},
      {"value":"w2","label":"Also redesign the logo."}],
     "correct","One job per prompt.","Scope creep is how reviews die."),
    ("spec-f19","Who is accountable if the agent writes a security bug?",
     [{"value":"correct","label":"You. The agent is a tool. You shipped it."},
      {"value":"w1","label":"The model vendor, automatically."},
      {"value":"w2","label":"Nobody, if it compiled."}],
     "correct","This is the job.","Compilation is not safety."),
    ("spec-f20","A mastery-level spec for search:",
     [{"value":"correct","label":"Given 3 clinic names, typing 'nor' shows Northline and nothing else, case-insensitive, updates on each keyup, and clearing the box shows all 3."},
      {"value":"w1","label":"Add search."},
      {"value":"w2","label":"Search should be smart."}],
     "correct","Examples + update rule + empty state.","Smart is not a test."),
]
for i, sp in enumerate(spec_prompts, 1):
    level = "guided" if i <= 8 else ("semiguided" if i <= 14 else ("challenge" if i <= 18 else "mastery"))
    tasks.append(choice_task(sp[0], "specs-criteria", "specs", level, sp[0].replace("spec-f","Spec "), sp[1], sp[2], sp[3], sp[4], sp[5]))

# Git 20
git_prompts = [
    ("git-f01","A commit should contain:",
     [{"value":"correct","label":"One reason for the change, in related files."},
      {"value":"w1","label":"Every file you touched this month."},
      {"value":"w2","label":"node_modules, always."}],
     "correct","Atomic commits are reviewable.","Noise is not history."),
    ("git-f02","main vs a feature branch:",
     [{"value":"correct","label":"Do the work on a branch, keep main deployable."},
      {"value":"w1","label":"Commit straight to main with no message."},
      {"value":"w2","label":"Never use branches if you are a beginner."}],
     "correct","Branches isolate risk.","Beginners need branches more, not less."),
    ("git-f03","This hunk adds console.log of a password. You:",
     [{"value":"correct","label":"Reject it. Ask to remove the log."},
      {"value":"w1","label":"Merge. Logs are fine in production."},
      {"value":"w2","label":"Change the password in the log to be funnier."}],
     "correct","Secrets in logs are a ship-stopper.","Humor is not a control."),
    ("git-f04","git status tells you:",
     [{"value":"correct","label":"What is staged, unstaged, and untracked right now."},
      {"value":"w1","label":"Whether the code is correct."},
      {"value":"w2","label":"The production error rate."}],
     "correct","Status is the map.","It does not grade logic."),
    ("git-f05","A good first commit message for this course's lab:",
     [{"value":"correct","label":"Add visiting-hours list to the Northline landing page."},
      {"value":"w1","label":"updates"},
      {"value":"w2","label":"asdf"}],
     "correct","Future you can search that.","updates means nothing."),
    ("git-f06","origin usually means:",
     [{"value":"correct","label":"The GitHub (or other host) copy of the repo."},
      {"value":"w1","label":"Your Downloads folder."},
      {"value":"w2","label":"The CSS framework."}],
     "correct","Push/pull talk to origin.","Not a local scratch pad."),
    ("git-f07","A PR is for:",
     [{"value":"correct","label":"Asking another brain (or future you) to review a branch before it hits main."},
      {"value":"w1","label":"Hiding work forever."},
      {"value":"w2","label":"Deleting Git."}],
     "correct","PRs are the review ritual.","They are not a trash can."),
    ("git-f08","You committed on the wrong branch. First instinct:",
     [{"value":"correct","label":"Stop. Do not force-push yet. Move the commit or cherry-pick after you understand status."},
      {"value":"w1","label":"force push --hard to main immediately."},
      {"value":"w2","label":"Delete .git to start a new life."}],
     "correct","Force-push to main is how you wipe teammates.","Panic is expensive."),
    ("git-f09","Untracked files:",
     [{"value":"correct","label":"Exist on disk but Git is not versioning them yet."},
      {"value":"w1","label":"Are already on GitHub."},
      {"value":"w2","label":"Cannot be committed, ever."}],
     "correct","git add starts tracking.","They are not published."),
    ("git-f10","A conflict means:",
     [{"value":"correct","label":"Two changes touched the same lines. You must choose or combine."},
      {"value":"w1","label":"Git is broken forever."},
      {"value":"w2","label":"You should add both copies and ship the conflict markers."}],
     "correct","Markers in production are a defect.","Conflicts are normal."),
    ("git-f11","README belongs:",
     [{"value":"correct","label":"In the repo root, with how to run the project."},
      {"value":"w1","label":"Only in a private Notion."},
      {"value":"w2","label":"Inside node_modules."}],
     "correct","This lab requires a README.","Reviewers start there."),
    ("git-f12","Which diff is safer to accept?",
     [{"value":"correct","label":"Three lines in hours.html adding a Saturday row you asked for."},
      {"value":"w1","label":"A rewrite of 12 unrelated files plus a new lockfile you did not request."},
      {"value":"w2","label":"Deletion of the tests folder 'for cleanliness'."}],
     "correct","Small, requested, test-preserving.","Surprise rewrites fail reviews."),
    ("git-f13",".gitignore should include:",
     [{"value":"correct","label":"Secrets, OS junk, and install artifacts like node_modules."},
      {"value":"w1","label":"Your source HTML."},
      {"value":"w2","label":"The README."}],
     "correct","Source stays tracked.","Dependencies are installed, not committed."),
    ("git-f14","fetch vs pull:",
     [{"value":"correct","label":"fetch downloads; pull fetches and merges (or rebases) into your branch."},
      {"value":"w1","label":"They are identical in every workflow."},
      {"value":"w2","label":"pull deletes your repo."}],
     "correct","Know which one moves your files.","pull is not a factory reset."),
    ("git-f15","Detached HEAD means:",
     [{"value":"correct","label":"You checked out a commit, not a branch. New commits can get lost if you do not branch."},
      {"value":"w1","label":"Your computer is overheating."},
      {"value":"w2","label":"GitHub is down."}],
     "correct","Create a branch if you meant to work there.","It is a pointer state."),
    ("git-f16","Blame is for:",
     [{"value":"correct","label":"Seeing who last changed a line so you can ask why, not to punish."},
      {"value":"w1","label":"Firing people automatically."},
      {"value":"w2","label":"Deleting history."}],
     "correct","History is a tool.","Culture matters."),
    ("git-f17","Squash merge does what?",
     [{"value":"correct","label":"Turns the PR's commits into one commit on the target branch."},
      {"value":"w1","label":"Deletes GitHub."},
      {"value":"w2","label":"Removes the working tree."}],
     "correct","Useful for a messy feature branch.","It is optional policy."),
    ("git-f18","You should not commit:",
     [{"value":"correct","label":".env files with live API keys."},
      {"value":"w1","label":"index.html for a static site."},
      {"value":"w2","label":"A failing test you are about to fix on the same branch."}],
     "correct","Keys in git are a breach.","Tests can be committed red then green."),
    ("git-f19","clone vs fork:",
     [{"value":"correct","label":"clone copies a repo locally; fork copies it under your GitHub account."},
      {"value":"w1","label":"They are the same button."},
      {"value":"w2","label":"fork only works on CSS."}],
     "correct","This lab uses a repo you own (fork or create).","Local vs GitHub-namespace."),
    ("git-f20","After you push a fix, reviewers need:",
     [{"value":"correct","label":"The PR link and what you want them to verify."},
      {"value":"w1","label":"A screenshot of your wallpaper."},
      {"value":"w2","label":"Nothing; they will guess."}],
     "correct","Review is a conversation.","Guessing is not a process."),
]
for i, g in enumerate(git_prompts, 1):
    level = "guided" if i <= 8 else ("semiguided" if i <= 14 else ("challenge" if i <= 18 else "mastery"))
    tasks.append(choice_task(g[0], "git-workflow", "git", level, g[0].replace("git-f","Git "), g[1], g[2], g[3], g[4], g[5]))

# Review 20
rev_prompts = [
    ("rv-f01","AI added eval(userInput). You:",
     [{"value":"correct","label":"Reject. That executes attacker strings."},
      {"value":"w1","label":"Approve; eval is a classic."},
      {"value":"w2","label":"Only reject if the variable is named evil."}],
     "correct","eval on user input is a red flag even in a tiny app.","Names do not make it safe."),
    ("rv-f02","The diff removes all tests 'to ship faster'. You:",
     [{"value":"correct","label":"Reject. Speed without tests is a demo, not a ship."},
      {"value":"w1","label":"Approve the delete."},
      {"value":"w2","label":"Replace tests with a GIF."}],
     "correct","This course treats deleting tests as a failure.","GIFs do not regress."),
    ("rv-f03","A change matches the spec and adds one test. You:",
     [{"value":"correct","label":"Accept, and still read the test to see what it actually asserts."},
      {"value":"w1","label":"Accept without opening the test file."},
      {"value":"w2","label":"Reject because it is too small."}],
     "correct","Small + tested is the goal. Still read.","Unread tests can test nothing."),
    ("rv-f04","innerHTML = userName is:",
     [{"value":"correct","label":"Dangerous if userName is untrusted. Prefer textContent."},
      {"value":"w1","label":"Always fine."},
      {"value":"w2","label":"Required for accessibility."}],
     "correct","XSS is a beginner-accessible bug.","textContent is the default."),
    ("rv-f05","The agent renamed a public function used in two files but only updated one. You:",
     [{"value":"correct","label":"Reject until both call sites match or the rename is reverted."},
      {"value":"w1","label":"Ship the half-rename."},
      {"value":"w2","label":"Ignore; JavaScript will invent the name."}],
     "correct","Half-renames crash at runtime.","JS does not forgive this."),
    ("rv-f06","A PR adds a TODO: 'fix later' on a payment path. You:",
     [{"value":"correct","label":"Do not merge payment TODOs. Finish or cut the feature."},
      {"value":"w1","label":"TODOs are a merge requirement."},
      {"value":"w2","label":"Payment paths do not need tests."}],
     "correct","Money paths stay complete.","TODO is not a control."),
    ("rv-f07","Lockfile change you did not request:",
     [{"value":"correct","label":"Ask why. Unexpected dependency churn is a review item."},
      {"value":"w1","label":"Always approve lockfiles."},
      {"value":"w2","label":"Delete package.json instead."}],
     "correct","Supply chain is in scope.","Rubber stamps leak."),
    ("rv-f08","The new function is 200 lines. You ask for:",
     [{"value":"correct","label":"A split into named helpers, or a comment that explains the one hard part — not a lecture."},
      {"value":"w1","label":"More lines to be thorough."},
      {"value":"w2","label":"Minification before review."}],
     "correct","Reviewability first.","Minified review is hostile."),
    ("rv-f09","Comments that restate the code ('increment i') should be:",
     [{"value":"correct","label":"Removed. Comments should say why, not what."},
      {"value":"w1","label":"Required on every line."},
      {"value":"w2","label":"Translated into Latin."}],
     "correct","Noise hides real warnings.","Why is the scarce comment."),
    ("rv-f10","Magic number 86400000 appears. You:",
     [{"value":"correct","label":"Ask for a named constant (ms in a day) if it is not obvious in context."},
      {"value":"w1","label":"Add more magic numbers for symmetry."},
      {"value":"w2","label":"Reject the entire language."}],
     "correct","Names prevent off-by-hour bugs.","Proportional review."),
    ("rv-f11","The UI change has no keyboard path. You:",
     [{"value":"correct","label":"Request a button or link that works without a mouse, or reject the interaction."},
      {"value":"w1","label":"Approve; mice are universal."},
      {"value":"w2","label":"Require a hover-only control."}],
     "correct","This course treats keyboard as required for interactive UI.","Hover-only is worse."),
    ("rv-f12","Agent added @ts-ignore on a type error. You:",
     [{"value":"correct","label":"Reject unless there is a one-line reason and a follow-up ticket."},
      {"value":"w1","label":"Ignore is a best practice."},
      {"value":"w2","label":"Add more ignores preventively."}],
     "correct","Silencing the checker hides the bug.","Not a habit."),
    ("rv-f13","A CSS change uses !important three times. You:",
     [{"value":"correct","label":"Ask to fix specificity instead, unless they can explain a third-party override."},
      {"value":"w1","label":"!important means senior."},
      {"value":"w2","label":"Require !important on every rule."}],
     "correct","Specificity fights are a smell.","Not a rank badge."),
    ("rv-f14","The feature works in Chrome only because of a nonstandard API. You:",
     [{"value":"correct","label":"Ask for a fallback or a documented browser cut."},
      {"value":"w1","label":"Ship; other browsers are fake."},
      {"value":"w2","label":"Block Safari users with an alert."}],
     "correct","Document the cut or polyfill.","Alerts are not a strategy."),
    ("rv-f15","Copied Stack Overflow snippet with a license comment removed. You:",
     [{"value":"correct","label":"Put attribution back or rewrite. Do not launder comments."},
      {"value":"w1","label":"Removing comments is cleanup."},
      {"value":"w2","label":"Licenses do not apply to beginners."}],
     "correct","Attribution is part of review.","Beginners are not exempt."),
    ("rv-f16","Performance: the agent nested a querySelector in a 10k loop. You:",
     [{"value":"correct","label":"Ask to cache the node unless they measured it is fine."},
      {"value":"w1","label":"More queries are more thorough."},
      {"value":"w2","label":"Loops are always banned."}],
     "correct","Easy win, still proportional.","Not a religion."),
    ("rv-f17","The PR description is empty. You:",
     [{"value":"correct","label":"Ask for what changed, how to test, and risk."},
      {"value":"w1","label":"Empty PRs are cleaner."},
      {"value":"w2","label":"Merge to save time."}],
     "correct","Descriptions are for the reviewer.","Empty is a smell."),
    ("rv-f18","Snapshot test that asserts the entire page HTML:",
     [{"value":"correct","label":"Too brittle. Prefer a test for the user-visible string or role."},
      {"value":"w1","label":"The bigger the snapshot the better."},
      {"value":"w2","label":"Delete all tests instead."}],
     "correct","Assert the behavior.","Gigantic snapshots always flake."),
    ("rv-f19","Agent 'fixed' a flake by adding a 5 second sleep. You:",
     [{"value":"correct","label":"Reject. Wait for the condition, not the clock."},
      {"value":"w1","label":"Sleeps are professional."},
      {"value":"w2","label":"Make it 50 seconds to be sure."}],
     "correct","Sleeps hide races.","Longer is worse."),
    ("rv-f20","You personally do not understand a hunk. You:",
     [{"value":"correct","label":"Do not approve it. Ask for a walkthrough or reject until you can explain it."},
      {"value":"w1","label":"Approve to look fast."},
      {"value":"w2","label":"Approve if the model said LGTM."}],
     "correct","You cannot own what you cannot explain.","The model is not the reviewer of record."),
]
for i, r in enumerate(rev_prompts, 1):
    level = "guided" if i <= 8 else ("semiguided" if i <= 14 else ("challenge" if i <= 18 else "mastery"))
    tasks.append(choice_task(r[0], "review-judgment", "review", level, r[0].replace("rv-f","Review "), r[1], r[2], r[3], r[4], r[5]))

# Testing 20
test_items = [
    ("ts-f01","testing-assertions","guided","test_sum","Write test_sum(impl) that returns true if impl(2,3)===5 and false if impl(2,3)!==5.",
     "function test_sum(impl){\n  return true;\n}",
     "function(a,b){return a+b;}", "function(a,b){return a-b;}",
     "The bad impl subtracts. Your test must return false."),
    ("ts-f02","testing-assertions","guided","test_greet","test_greet(impl): impl('Ada') should be 'Hello, Ada'.",
     "function test_greet(impl){\n  return true;\n}",
     "function(n){return 'Hello, '+n;}", "function(n){return n;}",
     "Bad impl returns the name only."),
    ("ts-f03","testing-assertions","guided","test_empty_sum","test_empty_sum(impl): impl([]) === 0.",
     "function test_empty_sum(impl){\n  return true;\n}",
     "function(xs){return xs.reduce((a,b)=>a+b,0);}", "function(xs){return 99;}",
     "Empty list must be 0, not a leftover."),
    ("ts-f04","testing-assertions","semiguided","test_clamp_high","test_clamp_high(impl): impl(50,0,10)===10.",
     "function test_clamp_high(impl){\n  return true;\n}",
     "function(n,lo,hi){return Math.min(hi,Math.max(lo,n));}", "function(n,lo,hi){return n;}",
     "Bad impl ignores the high bound."),
    ("ts-f05","testing-assertions","semiguided","test_unique","test_unique(impl): impl([1,1,2]) deep-equals [1,2].",
     "function test_unique(impl){\n  return true;\n}",
     "function(xs){return [...new Set(xs)];}", "function(xs){return xs;}",
     "Bad impl keeps duplicates. Use JSON.stringify to compare."),
    ("ts-f06","testing-assertions","semiguided","test_slug","test_slug(impl): impl('Hi There')==='hi-there'.",
     "function test_slug(impl){\n  return true;\n}",
     "function(s){return s.toLowerCase().replace(/ /g,'-');}", "function(s){return s.toLowerCase();}",
     "Bad impl forgets hyphens."),
    ("ts-f07","testing-mutations","challenge","test_safe_div","test_safe_div(impl): impl(1,0)===null and impl(8,2)===4.",
     "function test_safe_div(impl){\n  return true;\n}",
     "function(a,b){return b===0?null:a/b;}", "function(a,b){return a/b;}",
     "Bad impl divides by zero (Infinity). You must check the zero case."),
    ("ts-f08","testing-mutations","challenge","test_last","test_last(impl): impl([])===null and impl([1,2])===2.",
     "function test_last(impl){\n  return true;\n}",
     "function(xs){return xs.length?xs[xs.length-1]:null;}", "function(xs){return xs[0];}",
     "Bad impl returns the first element."),
    ("ts-f09","testing-assertions","guided","test_is_even","impl(2)===true, impl(3)===false.",
     "function test_is_even(impl){\n  return true;\n}",
     "function(n){return n%2===0;}", "function(n){return true;}",
     "Bad impl always returns true."),
    ("ts-f10","testing-assertions","guided","test_triple","impl(3)===9.",
     "function test_triple(impl){\n  return true;\n}",
     "function(n){return n*3;}", "function(n){return n+3;}",
     "Bad impl adds 3."),
    ("ts-f11","testing-mutations","semiguided","test_pick","impl({a:1,b:2},['a']) deep-equals {a:1}.",
     "function test_pick(impl){\n  return true;\n}",
     "function(o,ks){const r={};ks.forEach(k=>r[k]=o[k]);return r;}", "function(o,ks){return o;}",
     "Bad impl returns the whole object."),
    ("ts-f12","testing-mutations","semiguided","test_starts_https","impl('https://x')===true, impl('http://x')===false.",
     "function test_starts_https(impl){\n  return true;\n}",
     "function(s){return s.startsWith('https://');}", "function(s){return s.startsWith('http');}",
     "Bad impl treats http as https."),
    ("ts-f13","testing-mutations","challenge","test_mask","impl('ada@site.com')==='a**@site.com'.",
     "function test_mask(impl){\n  return true;\n}",
     "function(e){const [u,d]=e.split('@');return u[0]+'**@'+d;}", "function(e){return e;}",
     "Bad impl returns the raw email."),
    ("ts-f14","testing-assertions","guided","test_pct","impl(1,4)===25.",
     "function test_pct(impl){\n  return true;\n}",
     "function(p,w){return (p/w)*100;}", "function(p,w){return p/w;}",
     "Bad impl forgets *100."),
    ("ts-f15","testing-assertions","semiguided","test_title","impl('ada lovelace')==='Ada Lovelace'.",
     "function test_title(impl){\n  return true;\n}",
     "function(s){return s.split(' ').map(w=>w[0].toUpperCase()+w.slice(1).toLowerCase()).join(' ');}", "function(s){return s.toUpperCase();}",
     "Bad impl screams the whole string."),
    ("ts-f16","testing-mutations","challenge","test_running","impl([1,2,3]) deep-equals [1,3,6].",
     "function test_running(impl){\n  return true;\n}",
     "function(xs){let t=0;return xs.map(x=>t+=x);}", "function(xs){return xs;}",
     "Bad impl returns the input unchanged."),
    ("ts-f17","testing-mutations","mastery","test_palindrome","impl('Race car')===true, impl('hello')===false.",
     "function test_palindrome(impl){\n  return true;\n}",
     "function(s){const n=s.toLowerCase().replace(/ /g,'');return n===n.split('').reverse().join('');}", "function(s){return s===s.split('').reverse().join('');}",
     "Bad impl is case-sensitive and fails on Race car."),
    ("ts-f18","testing-assertions","guided","test_has_key","impl({a:1},'a')===true, impl({a:1},'z')===false.",
     "function test_has_key(impl){\n  return true;\n}",
     "function(o,k){return Object.prototype.hasOwnProperty.call(o,k);}", "function(o,k){return true;}",
     "Bad impl always true."),
    ("ts-f19","testing-assertions","semiguided","test_chunk","impl([1,2,3,4,5],2) deep-equals [[1,2],[3,4],[5]].",
     "function test_chunk(impl){\n  return true;\n}",
     "function(xs,n){const o=[];for(let i=0;i<xs.length;i+=n)o.push(xs.slice(i,i+n));return o;}", "function(xs,n){return [xs];}",
     "Bad impl wraps the whole array once."),
    ("ts-f20","testing-mutations","mastery","test_omit","impl({a:1,b:2},['b']) deep-equals {a:1}.",
     "function test_omit(impl){\n  return true;\n}",
     "function(o,ks){const r={};Object.keys(o).forEach(k=>{if(!ks.includes(k))r[k]=o[k];});return r;}", "function(o,ks){return o;}",
     "Bad impl returns the original object."),
]
for t in test_items:
    tasks.append({
        "id": t[0], "skill": t[1], "tool": "testing", "level": t[2], "kind": "testing",
        "title": t[3].replace("_", " "), "prompt": t[4], "functionName": t[3],
        "starter": t[5], "goodImpl": t[6], "badImpl": t[7], "bugHint": t[8],
        "prerequisite": "[]",
    })

# Python 25
py_items = [
    ("py-f01","python-basics","guided","total_revenue","Sum order['amount']. Empty is 0.",
     "def total_revenue(orders):\n    return 0\n",
     [[{"amount": 10}, {"amount": 2.5}], []], [12.5, 0]),
    ("py-f02","python-basics","guided","greet","greet('Ada') -> 'Hello, Ada'.",
     "def greet(name):\n    return ''\n",
     ["Ada"], ["Hello, Ada"]),
    ("py-f03","python-basics","guided","is_even","True if n even.",
     "def is_even(n):\n    return False\n",
     [2, 3], [True, False]),
    ("py-f04","python-json","guided","pluck_names","List of name fields.",
     "def pluck_names(rows):\n    return []\n",
     [[{"name": "A"}, {"name": "B"}]], [["A", "B"]]),
    ("py-f05","python-json","semiguided","count_status","Count matching status.",
     "def count_status(rows, target):\n    return 0\n",
     None, None),
    ("py-f06","python-basics","semiguided","clamp","Keep n in [lo, hi].",
     "def clamp(n, lo, hi):\n    return n\n",
     None, None),
    ("py-f07","python-strings","guided","slugify","Lowercase, spaces to -.",
     "def slugify(s):\n    return s\n",
     ["Hello World"], ["hello-world"]),
    ("py-f08","python-strings","semiguided","initials","'Ada Lovelace' -> 'AL'.",
     "def initials(name):\n    return ''\n",
     ["Ada Lovelace"], ["AL"]),
    ("py-f09","python-json","semiguided","unique","Unique first-seen.",
     "def unique(xs):\n    return xs\n",
     [[1, 1, 2, 1]], [[1, 2]]),
    ("py-f10","python-files","guided","parse_kv_line","'a=1' -> {'a':'1'}.",
     "def parse_kv_line(s):\n    return {}\n",
     ["a=1"], [{"a": "1"}]),
    ("py-f11","python-basics","guided","average","Mean, empty 0.",
     "def average(xs):\n    return 0\n",
     [[2, 4], []], [3, 0]),
    ("py-f12","python-json","challenge","max_by_amount","Object with max amount.",
     "def max_by_amount(rows):\n    return None\n",
     [[{"id": 1, "amount": 3}, {"id": 2, "amount": 9}]], [{"id": 2, "amount": 9}]),
    ("py-f13","python-files","challenge","load_ids","From lines of text, return stripped non-empty lines.",
     "def load_ids(text):\n    return []\n",
     ["a\n\nb\n"], [["a", "b"]]),
    ("py-f14","python-strings","guided","starts_with_https","True if startswith https://.",
     "def starts_with_https(s):\n    return False\n",
     ["https://x.com", "http://x"], [True, False]),
    ("py-f15","python-basics","semiguided","safe_div","None if b==0 else a/b.",
     "def safe_div(a, b):\n    return 0\n",
     None, None),
    ("py-f16","python-json","semiguided","pick","Keep listed keys.",
     "def pick(obj, keys):\n    return {}\n",
     None, None),
    ("py-f17","python-json","challenge","chunk","chunk(xs, 2).",
     "def chunk(xs, n):\n    return []\n",
     [[1, 2, 3, 4, 5], 2], [[[1, 2], [3, 4], [5]]]),
    ("py-f18","python-strings","challenge","mask_email","a**@domain.",
     "def mask_email(e):\n    return e\n",
     ["ada@site.com"], ["a**@site.com"]),
    ("py-f19","python-files","mastery","word_count","Count whitespace-separated words.",
     "def word_count(text):\n    return 0\n",
     ["one two three"], [3]),
    ("py-f20","python-json","mastery","merge","Shallow merge, b wins.",
     "def merge(a, b):\n    return a\n",
     [{"a": 1, "b": 2}, {"b": 9}], [{"a": 1, "b": 9}]),
    ("py-f21","python-basics","guided","triple","n * 3.",
     "def triple(n):\n    return 0\n",
     [4], [12]),
    ("py-f22","python-basics","guided","last","Last or None.",
     "def last(xs):\n    return None\n",
     [[1, 2, 9], []], [9, None]),
    ("py-f23","python-strings","semiguided","title_case","Title case words.",
     "def title_case(s):\n    return s\n",
     ["ada lovelace"], ["Ada Lovelace"]),
    ("py-f24","python-json","challenge","index_by_id","id -> object.",
     "def index_by_id(rows):\n    return {}\n",
     [[{"id": "a", "n": 1}]], [{"a": {"id": "a", "n": 1}}]),
    ("py-f25","python-files","mastery","running_total","[1,2,3] -> [1,3,6].",
     "def running_total(xs):\n    return []\n",
     [[1, 2, 3]], [[1, 3, 6]]),
]

# Python tasks with simple single/multi cases encoded as JS testCases for the browser JS grader
# Module 8 uses Pyodide; practice-python will use JS-equivalent via a python-in-comment? 
# We'll grade Python practice with Pyodide harness in the page. Store ref as testCases for a JS twin? 
# Simpler: grade Python with the same JS functionName pattern but student writes Python
# and practice-python.html uses Pyodide. For the generator, emit testCases as JSON
# plus kind: python.

for t in py_items:
    tid, skill, level, fname, prompt, starter = t[0], t[1], t[2], t[3], t[4], t[5]
    args_list, exp_list = t[6], t[7]
    cases = []
    if args_list is None:
        # specials
        if fname == "count_status":
            cases = [{"name": "open", "args": [[{"status": "open"}, {"status": "done"}], "open"], "expected": 1}]
        elif fname == "clamp":
            cases = [{"name": "hi", "args": [50, 0, 10], "expected": 10}]
        elif fname == "safe_div":
            cases = [{"name": "z", "args": [1, 0], "expected": None}, {"name": "ok", "args": [8, 2], "expected": 4}]
        elif fname == "pick":
            cases = [{"name": "a", "args": [{"a": 1, "b": 2}, ["a"]], "expected": {"a": 1}}]
        elif fname == "chunk":
            cases = [{"name": "2", "args": [[1, 2, 3, 4, 5], 2], "expected": [[1, 2], [3, 4], [5]]}]
        elif fname == "merge":
            cases = [{"name": "win", "args": [{"a": 1, "b": 2}, {"b": 9}], "expected": {"a": 1, "b": 9}}]
    else:
        # pair args with expected - args_list may be list of args OR list of single args
        if fname in ("total_revenue", "average", "last"):
            for a, e in zip(args_list, exp_list):
                cases.append({"name": str(e), "args": [a], "expected": e})
        elif fname in ("is_even", "triple", "starts_with_https"):
            for a, e in zip(args_list, exp_list):
                cases.append({"name": str(a), "args": [a], "expected": e})
        elif fname == "max_by_amount":
            cases = [{"name": "pick", "args": args_list, "expected": exp_list[0]}]
        elif fname == "chunk":
            cases = [{"name": "2", "args": args_list, "expected": exp_list[0]}]
        elif fname == "merge":
            cases = [{"name": "win", "args": args_list, "expected": exp_list[0]}]
        elif fname == "index_by_id":
            cases = [{"name": "one", "args": args_list, "expected": exp_list[0]}]
        elif isinstance(args_list[0], list) and fname in ("pluck_names", "unique", "running_total"):
            cases = [{"name": "main", "args": [args_list[0]], "expected": exp_list[0]}]
        else:
            cases = [{"name": "main", "args": args_list if isinstance(args_list, list) and args_list and not isinstance(args_list[0], (str, int, dict)) else [args_list[0]] if len(args_list)==1 or isinstance(args_list[0], str) else args_list, "expected": exp_list[0] if exp_list else None}]
            if fname in ("greet", "slugify", "initials", "parse_kv_line", "load_ids", "mask_email", "word_count", "title_case"):
                cases = [{"name": "main", "args": [args_list[0]], "expected": exp_list[0]}]
    tasks.append({
        "id": tid, "skill": skill, "tool": "python", "level": level, "kind": "python",
        "title": fname.replace("_", " "), "prompt": prompt, "functionName": fname,
        "starter": starter, "testCases": json.dumps(cases), "prerequisite": "[]",
    })

# Integrated 15
integ = [
    ("ct-01","integrated-flow","guided","Excel-to-JS mental model: SUM is a loop + add. Which JS matches SUM of amounts?",
     [{"value":"correct","label":"orders.reduce((s, o) => s + o.amount, 0)"},
      {"value":"w1","label":"orders.map(o => o.amount)"},
      {"value":"w2","label":"orders.length"}], "correct","Reduce accumulates.","Map returns a list, not a total."),
    ("ct-02","integrated-flow","guided","A spec says the button must not submit if email is empty. Which test proves it?",
     [{"value":"correct","label":"Call the validator with '' and expect false, then click handler must not call save."},
      {"value":"w1","label":"Look at the button color."},
      {"value":"w2","label":"Ask the agent if it works."}], "correct","A test names the empty case.","Color and vibes are not proof."),
    ("ct-03","integrated-flow","semiguided","You have a failing HTML practice task and a Cursor session. Order?",
     [{"value":"correct","label":"Read the failing check, fix the markup yourself or with a tiny prompt, re-run the grader."},
      {"value":"w1","label":"Paste the entire course into chat and hope."},
      {"value":"w2","label":"Mark the module complete in localStorage by hand."}], "correct","The grader is the contract.","Cheating the store is not skill."),
    ("ct-04","integrated-flow","semiguided","Git + review: the agent rewrote CSS you did not ask for. Ship?",
     [{"value":"correct","label":"No. Revert the CSS hunk, keep the requested HTML change, commit that."},
      {"value":"w1","label":"Yes, extra CSS is a gift."},
      {"value":"w2","label":"Delete Git."}], "correct","Unrequested diffs are out of scope.","Gifts hide regressions."),
    ("ct-05","integrated-flow","semiguided","Python script vs web page: when do you pick Python in this course?",
     [{"value":"correct","label":"When you transform a file or JSON list and print or write a result, not when you need a public UI."},
      {"value":"w1","label":"Always; Python is the only language."},
      {"value":"w2","label":"Never; Python is only for AI Engineering."}], "correct","Scripts vs UI. This course teaches both.","AI Engineering is RAG/agents, not 'any Python'."),
    ("ct-06","integrated-flow","challenge","A live URL returns 404. Capstone ready?",
     [{"value":"correct","label":"No. The deploy evidence must load. Fix the path or the host."},
      {"value":"w1","label":"Yes if the repo exists."},
      {"value":"w2","label":"Yes if Cursor said it deployed."}], "correct","404 is not shipped.","A repo is necessary but not sufficient."),
    ("ct-07","integrated-flow","challenge","You wrote tests after seeing the implementation. Risk?",
     [{"value":"correct","label":"The tests may copy the bug. Prefer writing the failing case from the spec first."},
      {"value":"w1","label":"No risk; later is smarter."},
      {"value":"w2","label":"Tests after code are illegal."}], "correct","Spec-first tests catch more.","Order is a habit, not a law."),
    ("ct-08","integrated-flow","challenge","HTML grader wants lang=en. Agent set lang=eng. You:",
     [{"value":"correct","label":"Change it to en. Match the spec/grader, do not invent a dialect code."},
      {"value":"w1","label":"Argue the grader is wrong and skip the task."},
      {"value":"w2","label":"Remove lang entirely."}], "correct","BCP 47 for English is en.","Skipping is not review."),
    ("ct-09","integrated-flow","guided","Which artifact is NOT enough alone for the capstone?",
     [{"value":"correct","label":"A chat log with Cursor and no repo."},
      {"value":"w1","label":"A GitHub repo with commits."},
      {"value":"w2","label":"A live https URL."}], "correct","Chat is not evidence of a ship.","Repo and URL are required together with tests."),
    ("ct-10","integrated-flow","semiguided","JS function works in the practice page but you never committed it. For a job:",
     [{"value":"correct","label":"It does not count. Employers look at GitHub and live sites, not your localStorage."},
      {"value":"w1","label":"localStorage is a portfolio."},
      {"value":"w2","label":"Practice passes replace a capstone."}], "correct","Practice is training. Desktop labs and projects are evidence.","Stores are private."),
    ("ct-11","integrated-flow","mastery","Best capstone README first line?",
     [{"value":"correct","label":"Northline landing: hours list, validated contact form, tests for empty email, deployed at https://..."},
      {"value":"w1","label":"I used AI a lot."},
      {"value":"w2","label":"TODO"}], "correct","What it does, how you know, where it lives.","AI use is a method note, not the product."),
    ("ct-12","integrated-flow","guided","CSS practice cannot replace Desktop Lab A because:",
     [{"value":"correct","label":"The grader does not open Cursor. Lab A needs a real GitHub commit from your machine."},
      {"value":"w1","label":"CSS is fake."},
      {"value":"w2","label":"GitHub bans CSS."}], "correct","Same honesty rule as Data Science Tableau.","The simulation is labeled on purpose."),
    ("ct-13","integrated-flow","challenge","Agent wrote tests that only assert true === true. You:",
     [{"value":"correct","label":"Reject. Tests must fail on a broken implementation."},
      {"value":"w1","label":"Green is green."},
      {"value":"w2","label":"Add more true === true for coverage."}], "correct","This is the testing library's whole point.","Coverage of tautologies is theater."),
    ("ct-14","integrated-flow","semiguided","You finished Module 3. May you skip to Cursor-only work and ignore Git?",
     [{"value":"correct","label":"No. Modules 5 and the GitHub lab are required before the capstone."},
      {"value":"w1","label":"Yes if you feel ready."},
      {"value":"w2","label":"Git is optional for AI-assisted engineers."}], "correct","The gates exist because the job uses Git.","Feeling ready is not a merge."),
    ("ct-15","integrated-flow","mastery","After this course, AI Engineering is for:",
     [{"value":"correct","label":"People who can already write and review code and now want to build LLM products (RAG, tools, eval)."},
      {"value":"w1","label":"Anyone who finished Module 0 of this course."},
      {"value":"w2","label":"A replacement for shipping web apps."}], "correct","Different job. This course is the on-ramp to being able to take that one.","Not a substitute."),
]
for i, c in enumerate(integ, 1):
    level = c[2]
    tasks.append(choice_task(c[0], c[1], "integrated", level, c[0], c[3], c[4], c[5], c[6], c[7]))

# Emit JS
lines = [
    "/* Generated task catalog. Do not hand-edit counts without re-running scripts/_gen_aise_tasks.py */",
    "(function (global) {",
    "const TASKS = [",
]
for t in tasks:
    fields = []
    for k, v in t.items():
        if k in ("checks", "testCases", "options", "goodImpl", "badImpl", "prerequisite") and isinstance(v, str):
            if k == "prerequisite":
                fields.append(f"{k}: {v}")
            elif k == "goodImpl" or k == "badImpl":
                fields.append(f"{k}: {json.dumps(v)}")
            elif k == "testCases" or k == "options" or k == "checks":
                fields.append(f"{k}: {v}")
            else:
                fields.append(f"{k}: {v}")
        else:
            fields.append(f"{k}: {json.dumps(v)}")
    lines.append("  { " + ", ".join(fields) + " },")
lines.append("];")
lines.append("global.AISE_TASKS = TASKS;")
lines.append("})(window);")
OUT.write_text("\n".join(lines), encoding="utf-8")
print("wrote", len(tasks), "tasks to", OUT)
from collections import Counter
print(Counter(t["tool"] for t in tasks))
